// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: merchant/v1/merchant.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MerchantService_ListMerchants_FullMethodName     = "/panda.merchant.v1.MerchantService/ListMerchants"
	MerchantService_GetMerchant_FullMethodName       = "/panda.merchant.v1.MerchantService/GetMerchant"
	MerchantService_CreateMerchant_FullMethodName    = "/panda.merchant.v1.MerchantService/CreateMerchant"
	MerchantService_UpdateMerchant_FullMethodName    = "/panda.merchant.v1.MerchantService/UpdateMerchant"
	MerchantService_ListStores_FullMethodName        = "/panda.merchant.v1.MerchantService/ListStores"
	MerchantService_Profile_FullMethodName           = "/panda.merchant.v1.MerchantService/Profile"
	MerchantService_Stores_FullMethodName            = "/panda.merchant.v1.MerchantService/Stores"
	MerchantService_GetBrandMerchant_FullMethodName  = "/panda.merchant.v1.MerchantService/GetBrandMerchant"
	MerchantService_GetStoreMerchant_FullMethodName  = "/panda.merchant.v1.MerchantService/GetStoreMerchant"
	MerchantService_ResolveScopeNames_FullMethodName = "/panda.merchant.v1.MerchantService/ResolveScopeNames"
)

// MerchantServiceClient is the client API for MerchantService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MerchantServiceClient interface {
	ListMerchants(ctx context.Context, in *ListMerchantsRequest, opts ...grpc.CallOption) (*ListMerchantsResponse, error)
	GetMerchant(ctx context.Context, in *GetMerchantRequest, opts ...grpc.CallOption) (*GetMerchantResponse, error)
	CreateMerchant(ctx context.Context, in *CreateMerchantRequest, opts ...grpc.CallOption) (*CreateMerchantResponse, error)
	UpdateMerchant(ctx context.Context, in *UpdateMerchantRequest, opts ...grpc.CallOption) (*UpdateMerchantResponse, error)
	ListStores(ctx context.Context, in *ListStoresRequest, opts ...grpc.CallOption) (*ListStoresResponse, error)
	Profile(ctx context.Context, in *MerchantProfileRequest, opts ...grpc.CallOption) (*MerchantProfileResponse, error)
	Stores(ctx context.Context, in *MerchantStoresRequest, opts ...grpc.CallOption) (*MerchantStoresResponse, error)
	GetBrandMerchant(ctx context.Context, in *GetBrandMerchantRequest, opts ...grpc.CallOption) (*GetBrandMerchantResponse, error)
	GetStoreMerchant(ctx context.Context, in *GetStoreMerchantRequest, opts ...grpc.CallOption) (*GetStoreMerchantResponse, error)
	// ResolveScopeNames replaces the brand/store join user-service used to run
	// against merchant tables that no longer live in its database.
	ResolveScopeNames(ctx context.Context, in *ResolveScopeNamesRequest, opts ...grpc.CallOption) (*ResolveScopeNamesResponse, error)
}

type merchantServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMerchantServiceClient(cc grpc.ClientConnInterface) MerchantServiceClient {
	return &merchantServiceClient{cc}
}

func (c *merchantServiceClient) ListMerchants(ctx context.Context, in *ListMerchantsRequest, opts ...grpc.CallOption) (*ListMerchantsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMerchantsResponse)
	err := c.cc.Invoke(ctx, MerchantService_ListMerchants_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *merchantServiceClient) GetMerchant(ctx context.Context, in *GetMerchantRequest, opts ...grpc.CallOption) (*GetMerchantResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMerchantResponse)
	err := c.cc.Invoke(ctx, MerchantService_GetMerchant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *merchantServiceClient) CreateMerchant(ctx context.Context, in *CreateMerchantRequest, opts ...grpc.CallOption) (*CreateMerchantResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateMerchantResponse)
	err := c.cc.Invoke(ctx, MerchantService_CreateMerchant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *merchantServiceClient) UpdateMerchant(ctx context.Context, in *UpdateMerchantRequest, opts ...grpc.CallOption) (*UpdateMerchantResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateMerchantResponse)
	err := c.cc.Invoke(ctx, MerchantService_UpdateMerchant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *merchantServiceClient) ListStores(ctx context.Context, in *ListStoresRequest, opts ...grpc.CallOption) (*ListStoresResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListStoresResponse)
	err := c.cc.Invoke(ctx, MerchantService_ListStores_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *merchantServiceClient) Profile(ctx context.Context, in *MerchantProfileRequest, opts ...grpc.CallOption) (*MerchantProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MerchantProfileResponse)
	err := c.cc.Invoke(ctx, MerchantService_Profile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *merchantServiceClient) Stores(ctx context.Context, in *MerchantStoresRequest, opts ...grpc.CallOption) (*MerchantStoresResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MerchantStoresResponse)
	err := c.cc.Invoke(ctx, MerchantService_Stores_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *merchantServiceClient) GetBrandMerchant(ctx context.Context, in *GetBrandMerchantRequest, opts ...grpc.CallOption) (*GetBrandMerchantResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBrandMerchantResponse)
	err := c.cc.Invoke(ctx, MerchantService_GetBrandMerchant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *merchantServiceClient) GetStoreMerchant(ctx context.Context, in *GetStoreMerchantRequest, opts ...grpc.CallOption) (*GetStoreMerchantResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStoreMerchantResponse)
	err := c.cc.Invoke(ctx, MerchantService_GetStoreMerchant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *merchantServiceClient) ResolveScopeNames(ctx context.Context, in *ResolveScopeNamesRequest, opts ...grpc.CallOption) (*ResolveScopeNamesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResolveScopeNamesResponse)
	err := c.cc.Invoke(ctx, MerchantService_ResolveScopeNames_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MerchantServiceServer is the server API for MerchantService service.
// All implementations must embed UnimplementedMerchantServiceServer
// for forward compatibility.
type MerchantServiceServer interface {
	ListMerchants(context.Context, *ListMerchantsRequest) (*ListMerchantsResponse, error)
	GetMerchant(context.Context, *GetMerchantRequest) (*GetMerchantResponse, error)
	CreateMerchant(context.Context, *CreateMerchantRequest) (*CreateMerchantResponse, error)
	UpdateMerchant(context.Context, *UpdateMerchantRequest) (*UpdateMerchantResponse, error)
	ListStores(context.Context, *ListStoresRequest) (*ListStoresResponse, error)
	Profile(context.Context, *MerchantProfileRequest) (*MerchantProfileResponse, error)
	Stores(context.Context, *MerchantStoresRequest) (*MerchantStoresResponse, error)
	GetBrandMerchant(context.Context, *GetBrandMerchantRequest) (*GetBrandMerchantResponse, error)
	GetStoreMerchant(context.Context, *GetStoreMerchantRequest) (*GetStoreMerchantResponse, error)
	// ResolveScopeNames replaces the brand/store join user-service used to run
	// against merchant tables that no longer live in its database.
	ResolveScopeNames(context.Context, *ResolveScopeNamesRequest) (*ResolveScopeNamesResponse, error)
	mustEmbedUnimplementedMerchantServiceServer()
}

// UnimplementedMerchantServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMerchantServiceServer struct{}

func (UnimplementedMerchantServiceServer) ListMerchants(context.Context, *ListMerchantsRequest) (*ListMerchantsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListMerchants not implemented")
}
func (UnimplementedMerchantServiceServer) GetMerchant(context.Context, *GetMerchantRequest) (*GetMerchantResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMerchant not implemented")
}
func (UnimplementedMerchantServiceServer) CreateMerchant(context.Context, *CreateMerchantRequest) (*CreateMerchantResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateMerchant not implemented")
}
func (UnimplementedMerchantServiceServer) UpdateMerchant(context.Context, *UpdateMerchantRequest) (*UpdateMerchantResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateMerchant not implemented")
}
func (UnimplementedMerchantServiceServer) ListStores(context.Context, *ListStoresRequest) (*ListStoresResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListStores not implemented")
}
func (UnimplementedMerchantServiceServer) Profile(context.Context, *MerchantProfileRequest) (*MerchantProfileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Profile not implemented")
}
func (UnimplementedMerchantServiceServer) Stores(context.Context, *MerchantStoresRequest) (*MerchantStoresResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Stores not implemented")
}
func (UnimplementedMerchantServiceServer) GetBrandMerchant(context.Context, *GetBrandMerchantRequest) (*GetBrandMerchantResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBrandMerchant not implemented")
}
func (UnimplementedMerchantServiceServer) GetStoreMerchant(context.Context, *GetStoreMerchantRequest) (*GetStoreMerchantResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStoreMerchant not implemented")
}
func (UnimplementedMerchantServiceServer) ResolveScopeNames(context.Context, *ResolveScopeNamesRequest) (*ResolveScopeNamesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResolveScopeNames not implemented")
}
func (UnimplementedMerchantServiceServer) mustEmbedUnimplementedMerchantServiceServer() {}
func (UnimplementedMerchantServiceServer) testEmbeddedByValue()                         {}

// UnsafeMerchantServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MerchantServiceServer will
// result in compilation errors.
type UnsafeMerchantServiceServer interface {
	mustEmbedUnimplementedMerchantServiceServer()
}

func RegisterMerchantServiceServer(s grpc.ServiceRegistrar, srv MerchantServiceServer) {
	// If the following call panics, it indicates UnimplementedMerchantServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MerchantService_ServiceDesc, srv)
}

func _MerchantService_ListMerchants_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMerchantsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MerchantServiceServer).ListMerchants(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MerchantService_ListMerchants_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MerchantServiceServer).ListMerchants(ctx, req.(*ListMerchantsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MerchantService_GetMerchant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMerchantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MerchantServiceServer).GetMerchant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MerchantService_GetMerchant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MerchantServiceServer).GetMerchant(ctx, req.(*GetMerchantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MerchantService_CreateMerchant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateMerchantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MerchantServiceServer).CreateMerchant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MerchantService_CreateMerchant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MerchantServiceServer).CreateMerchant(ctx, req.(*CreateMerchantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MerchantService_UpdateMerchant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateMerchantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MerchantServiceServer).UpdateMerchant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MerchantService_UpdateMerchant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MerchantServiceServer).UpdateMerchant(ctx, req.(*UpdateMerchantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MerchantService_ListStores_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListStoresRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MerchantServiceServer).ListStores(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MerchantService_ListStores_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MerchantServiceServer).ListStores(ctx, req.(*ListStoresRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MerchantService_Profile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MerchantProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MerchantServiceServer).Profile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MerchantService_Profile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MerchantServiceServer).Profile(ctx, req.(*MerchantProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MerchantService_Stores_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MerchantStoresRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MerchantServiceServer).Stores(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MerchantService_Stores_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MerchantServiceServer).Stores(ctx, req.(*MerchantStoresRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MerchantService_GetBrandMerchant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBrandMerchantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MerchantServiceServer).GetBrandMerchant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MerchantService_GetBrandMerchant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MerchantServiceServer).GetBrandMerchant(ctx, req.(*GetBrandMerchantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MerchantService_GetStoreMerchant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStoreMerchantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MerchantServiceServer).GetStoreMerchant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MerchantService_GetStoreMerchant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MerchantServiceServer).GetStoreMerchant(ctx, req.(*GetStoreMerchantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MerchantService_ResolveScopeNames_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveScopeNamesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MerchantServiceServer).ResolveScopeNames(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MerchantService_ResolveScopeNames_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MerchantServiceServer).ResolveScopeNames(ctx, req.(*ResolveScopeNamesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MerchantService_ServiceDesc is the grpc.ServiceDesc for MerchantService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MerchantService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "panda.merchant.v1.MerchantService",
	HandlerType: (*MerchantServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListMerchants",
			Handler:    _MerchantService_ListMerchants_Handler,
		},
		{
			MethodName: "GetMerchant",
			Handler:    _MerchantService_GetMerchant_Handler,
		},
		{
			MethodName: "CreateMerchant",
			Handler:    _MerchantService_CreateMerchant_Handler,
		},
		{
			MethodName: "UpdateMerchant",
			Handler:    _MerchantService_UpdateMerchant_Handler,
		},
		{
			MethodName: "ListStores",
			Handler:    _MerchantService_ListStores_Handler,
		},
		{
			MethodName: "Profile",
			Handler:    _MerchantService_Profile_Handler,
		},
		{
			MethodName: "Stores",
			Handler:    _MerchantService_Stores_Handler,
		},
		{
			MethodName: "GetBrandMerchant",
			Handler:    _MerchantService_GetBrandMerchant_Handler,
		},
		{
			MethodName: "GetStoreMerchant",
			Handler:    _MerchantService_GetStoreMerchant_Handler,
		},
		{
			MethodName: "ResolveScopeNames",
			Handler:    _MerchantService_ResolveScopeNames_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "merchant/v1/merchant.proto",
}
