// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: merchant/v1/merchant.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MerchantStatus is the lifecycle state of a merchant tenant.
// The existing Merchant.status string remains the wire-compatible representation.
type MerchantStatus int32

const (
	MerchantStatus_MERCHANT_STATUS_UNSPECIFIED MerchantStatus = 0
	MerchantStatus_MERCHANT_STATUS_PENDING     MerchantStatus = 1
	MerchantStatus_MERCHANT_STATUS_ACTIVE      MerchantStatus = 2
	MerchantStatus_MERCHANT_STATUS_SUSPENDED   MerchantStatus = 3
)

// Enum value maps for MerchantStatus.
var (
	MerchantStatus_name = map[int32]string{
		0: "MERCHANT_STATUS_UNSPECIFIED",
		1: "MERCHANT_STATUS_PENDING",
		2: "MERCHANT_STATUS_ACTIVE",
		3: "MERCHANT_STATUS_SUSPENDED",
	}
	MerchantStatus_value = map[string]int32{
		"MERCHANT_STATUS_UNSPECIFIED": 0,
		"MERCHANT_STATUS_PENDING":     1,
		"MERCHANT_STATUS_ACTIVE":      2,
		"MERCHANT_STATUS_SUSPENDED":   3,
	}
)

func (x MerchantStatus) Enum() *MerchantStatus {
	p := new(MerchantStatus)
	*p = x
	return p
}

func (x MerchantStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MerchantStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_merchant_v1_merchant_proto_enumTypes[0].Descriptor()
}

func (MerchantStatus) Type() protoreflect.EnumType {
	return &file_merchant_v1_merchant_proto_enumTypes[0]
}

func (x MerchantStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MerchantStatus.Descriptor instead.
func (MerchantStatus) EnumDescriptor() ([]byte, []int) {
	return file_merchant_v1_merchant_proto_rawDescGZIP(), []int{0}
}

// ResourceStatus is the operational state of a brand or store.
// Audit state is intentionally separate from operational availability.
type ResourceStatus int32

const (
	ResourceStatus_RESOURCE_STATUS_UNSPECIFIED ResourceStatus = 0
	ResourceStatus_RESOURCE_STATUS_ACTIVE      ResourceStatus = 1
	ResourceStatus_RESOURCE_STATUS_DISABLED    ResourceStatus = 2
)

// Enum value maps for ResourceStatus.
var (
	ResourceStatus_name = map[int32]string{
		0: "RESOURCE_STATUS_UNSPECIFIED",
		1: "RESOURCE_STATUS_ACTIVE",
		2: "RESOURCE_STATUS_DISABLED",
	}
	ResourceStatus_value = map[string]int32{
		"RESOURCE_STATUS_UNSPECIFIED": 0,
		"RESOURCE_STATUS_ACTIVE":      1,
		"RESOURCE_STATUS_DISABLED":    2,
	}
)

func (x ResourceStatus) Enum() *ResourceStatus {
	p := new(ResourceStatus)
	*p = x
	return p
}

func (x ResourceStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ResourceStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_merchant_v1_merchant_proto_enumTypes[1].Descriptor()
}

func (ResourceStatus) Type() protoreflect.EnumType {
	return &file_merchant_v1_merchant_proto_enumTypes[1]
}

func (x ResourceStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ResourceStatus.Descriptor instead.
func (ResourceStatus) EnumDescriptor() ([]byte, []int) {
	return file_merchant_v1_merchant_proto_rawDescGZIP(), []int{1}
}

// AuditStatus describes whether a brand or store change has passed review.
type AuditStatus int32

const (
	AuditStatus_AUDIT_STATUS_UNSPECIFIED AuditStatus = 0
	AuditStatus_AUDIT_STATUS_PENDING     AuditStatus = 1
	AuditStatus_AUDIT_STATUS_APPROVED    AuditStatus = 2
	AuditStatus_AUDIT_STATUS_REJECTED    AuditStatus = 3
)

// Enum value maps for AuditStatus.
var (
	AuditStatus_name = map[int32]string{
		0: "AUDIT_STATUS_UNSPECIFIED",
		1: "AUDIT_STATUS_PENDING",
		2: "AUDIT_STATUS_APPROVED",
		3: "AUDIT_STATUS_REJECTED",
	}
	AuditStatus_value = map[string]int32{
		"AUDIT_STATUS_UNSPECIFIED": 0,
		"AUDIT_STATUS_PENDING":     1,
		"AUDIT_STATUS_APPROVED":    2,
		"AUDIT_STATUS_REJECTED":    3,
	}
)

func (x AuditStatus) Enum() *AuditStatus {
	p := new(AuditStatus)
	*p = x
	return p
}

func (x AuditStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AuditStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_merchant_v1_merchant_proto_enumTypes[2].Descriptor()
}

func (AuditStatus) Type() protoreflect.EnumType {
	return &file_merchant_v1_merchant_proto_enumTypes[2]
}

func (x AuditStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AuditStatus.Descriptor instead.
func (AuditStatus) EnumDescriptor() ([]byte, []int) {
	return file_merchant_v1_merchant_proto_rawDescGZIP(), []int{2}
}

type Merchant struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name            string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ContactName     string                 `protobuf:"bytes,3,opt,name=contact_name,json=contactName,proto3" json:"contact_name,omitempty"`
	ContactPhone    string                 `protobuf:"bytes,4,opt,name=contact_phone,json=contactPhone,proto3" json:"contact_phone,omitempty"`
	BusinessLicense string                 `protobuf:"bytes,5,opt,name=business_license,json=businessLicense,proto3" json:"business_license,omitempty"`
	Address         string                 `protobuf:"bytes,6,opt,name=address,proto3" json:"address,omitempty"`
	// Deprecated in favor of status_code for new clients. Values are pending, active, or suspended.
	Status string `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	// Additive enum form of status; readers must continue accepting status.
	StatusCode    MerchantStatus `protobuf:"varint,8,opt,name=status_code,json=statusCode,proto3,enum=panda.merchant.v1.MerchantStatus" json:"status_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Merchant) Reset() {
	*x = Merchant{}
	mi := &file_merchant_v1_merchant_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Merchant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Merchant) ProtoMessage() {}

func (x *Merchant) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_v1_merchant_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Merchant.ProtoReflect.Descriptor instead.
func (*Merchant) Descriptor() ([]byte, []int) {
	return file_merchant_v1_merchant_proto_rawDescGZIP(), []int{0}
}

func (x *Merchant) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Merchant) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Merchant) GetContactName() string {
	if x != nil {
		return x.ContactName
	}
	return ""
}

func (x *Merchant) GetContactPhone() string {
	if x != nil {
		return x.ContactPhone
	}
	return ""
}

func (x *Merchant) GetBusinessLicense() string {
	if x != nil {
		return x.BusinessLicense
	}
	return ""
}

func (x *Merchant) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Merchant) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Merchant) GetStatusCode() MerchantStatus {
	if x != nil {
		return x.StatusCode
	}
	return MerchantStatus_MERCHANT_STATUS_UNSPECIFIED
}

type Brand struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Id          string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	MerchantId  string                 `protobuf:"bytes,2,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	Name        string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Logo        string                 `protobuf:"bytes,4,opt,name=logo,proto3" json:"logo,omitempty"`
	Banner      string                 `protobuf:"bytes,5,opt,name=banner,proto3" json:"banner,omitempty"`
	Description string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	Status      string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	AuditStatus string                 `protobuf:"bytes,8,opt,name=audit_status,json=auditStatus,proto3" json:"audit_status,omitempty"`
	Visible     bool                   `protobuf:"varint,9,opt,name=visible,proto3" json:"visible,omitempty"`
	// Additive enum forms; status and audit_status remain available for older readers.
	StatusCode      ResourceStatus `protobuf:"varint,10,opt,name=status_code,json=statusCode,proto3,enum=panda.merchant.v1.ResourceStatus" json:"status_code,omitempty"`
	AuditStatusCode AuditStatus    `protobuf:"varint,11,opt,name=audit_status_code,json=auditStatusCode,proto3,enum=panda.merchant.v1.AuditStatus" json:"audit_status_code,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Brand) Reset() {
	*x = Brand{}
	mi := &file_merchant_v1_merchant_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Brand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Brand) ProtoMessage() {}

func (x *Brand) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_v1_merchant_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Brand.ProtoReflect.Descriptor instead.
func (*Brand) Descriptor() ([]byte, []int) {
	return file_merchant_v1_merchant_proto_rawDescGZIP(), []int{1}
}

func (x *Brand) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Brand) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *Brand) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Brand) GetLogo() string {
	if x != nil {
		return x.Logo
	}
	return ""
}

func (x *Brand) GetBanner() string {
	if x != nil {
		return x.Banner
	}
	return ""
}

func (x *Brand) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Brand) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Brand) GetAuditStatus() string {
	if x != nil {
		return x.AuditStatus
	}
	return ""
}

func (x *Brand) GetVisible() bool {
	if x != nil {
		return x.Visible
	}
	return false
}

func (x *Brand) GetStatusCode() ResourceStatus {
	if x != nil {
		return x.StatusCode
	}
	return ResourceStatus_RESOURCE_STATUS_UNSPECIFIED
}

func (x *Brand) GetAuditStatusCode() AuditStatus {
	if x != nil {
		return x.AuditStatusCode
	}
	return AuditStatus_AUDIT_STATUS_UNSPECIFIED
}

type Store struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	MerchantId    string                 `protobuf:"bytes,2,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	BrandId       string                 `protobuf:"bytes,3,opt,name=brand_id,json=brandId,proto3" json:"brand_id,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Logo          string                 `protobuf:"bytes,5,opt,name=logo,proto3" json:"logo,omitempty"`
	Phone         string                 `protobuf:"bytes,6,opt,name=phone,proto3" json:"phone,omitempty"`
	Province      string                 `protobuf:"bytes,7,opt,name=province,proto3" json:"province,omitempty"`
	City          string                 `protobuf:"bytes,8,opt,name=city,proto3" json:"city,omitempty"`
	District      string                 `protobuf:"bytes,9,opt,name=district,proto3" json:"district,omitempty"`
	Address       string                 `protobuf:"bytes,10,opt,name=address,proto3" json:"address,omitempty"`
	BusinessHours string                 `protobuf:"bytes,11,opt,name=business_hours,json=businessHours,proto3" json:"business_hours,omitempty"`
	// Optional because the columns are: an uncollected coordinate is NULL, and a
	// plain double would carry it as 0 — a real point in the Atlantic that a
	// reader cannot tell from "nobody surveyed this store".
	Longitude *float64 `protobuf:"fixed64,12,opt,name=longitude,proto3,oneof" json:"longitude,omitempty"`
	Latitude  *float64 `protobuf:"fixed64,13,opt,name=latitude,proto3,oneof" json:"latitude,omitempty"`
	// Deprecated in favor of status_code for new clients. Values are active or disabled.
	Status          string         `protobuf:"bytes,14,opt,name=status,proto3" json:"status,omitempty"`
	Visible         bool           `protobuf:"varint,15,opt,name=visible,proto3" json:"visible,omitempty"`
	AuditStatus     string         `protobuf:"bytes,16,opt,name=audit_status,json=auditStatus,proto3" json:"audit_status,omitempty"`
	StatusCode      ResourceStatus `protobuf:"varint,17,opt,name=status_code,json=statusCode,proto3,enum=panda.merchant.v1.ResourceStatus" json:"status_code,omitempty"`
	AuditStatusCode AuditStatus    `protobuf:"varint,18,opt,name=audit_status_code,json=auditStatusCode,proto3,enum=panda.merchant.v1.AuditStatus" json:"audit_status_code,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Store) Reset() {
	*x = Store{}
	mi := &file_merchant_v1_merchant_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Store) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Store) ProtoMessage() {}

func (x *Store) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_v1_merchant_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Store.ProtoReflect.Descriptor instead.
func (*Store) Descriptor() ([]byte, []int) {
	return file_merchant_v1_merchant_proto_rawDescGZIP(), []int{2}
}

func (x *Store) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Store) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *Store) GetBrandId() string {
	if x != nil {
		return x.BrandId
	}
	return ""
}

func (x *Store) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Store) GetLogo() string {
	if x != nil {
		return x.Logo
	}
	return ""
}

func (x *Store) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *Store) GetProvince() string {
	if x != nil {
		return x.Province
	}
	return ""
}

func (x *Store) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *Store) GetDistrict() string {
	if x != nil {
		return x.District
	}
	return ""
}

func (x *Store) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Store) GetBusinessHours() string {
	if x != nil {
		return x.BusinessHours
	}
	return ""
}

func (x *Store) GetLongitude() float64 {
	if x != nil && x.Longitude != nil {
		return *x.Longitude
	}
	return 0
}

func (x *Store) GetLatitude() float64 {
	if x != nil && x.Latitude != nil {
		return *x.Latitude
	}
	return 0
}

func (x *Store) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Store) GetVisible() bool {
	if x != nil {
		return x.Visible
	}
	return false
}

func (x *Store) GetAuditStatus() string {
	if x != nil {
		return x.AuditStatus
	}
	return ""
}

func (x *Store) GetStatusCode() ResourceStatus {
	if x != nil {
		return x.StatusCode
	}
	return ResourceStatus_RESOURCE_STATUS_UNSPECIFIED
}

func (x *Store) GetAuditStatusCode() AuditStatus {
	if x != nil {
		return x.AuditStatusCode
	}
	return AuditStatus_AUDIT_STATUS_UNSPECIFIED
}

type MerchantAccount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	MerchantId    string                 `protobuf:"bytes,2,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	Username      string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MerchantAccount) Reset() {
	*x = MerchantAccount{}
	mi := &file_merchant_v1_merchant_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MerchantAccount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MerchantAccount) ProtoMessage() {}

func (x *MerchantAccount) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_v1_merchant_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MerchantAccount.ProtoReflect.Descriptor instead.
func (*MerchantAccount) Descriptor() ([]byte, []int) {
	return file_merchant_v1_merchant_proto_rawDescGZIP(), []int{3}
}

func (x *MerchantAccount) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *MerchantAccount) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *MerchantAccount) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *MerchantAccount) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ListMerchantsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMerchantsRequest) Reset() {
	*x = ListMerchantsRequest{}
	mi := &file_merchant_v1_merchant_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMerchantsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMerchantsRequest) ProtoMessage() {}

func (x *ListMerchantsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_v1_merchant_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMerchantsRequest.ProtoReflect.Descriptor instead.
func (*ListMerchantsRequest) Descriptor() ([]byte, []int) {
	return file_merchant_v1_merchant_proto_rawDescGZIP(), []int{4}
}

type ListMerchantsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Merchants     []*Merchant            `protobuf:"bytes,1,rep,name=merchants,proto3" json:"merchants,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMerchantsResponse) Reset() {
	*x = ListMerchantsResponse{}
	mi := &file_merchant_v1_merchant_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMerchantsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMerchantsResponse) ProtoMessage() {}

func (x *ListMerchantsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_v1_merchant_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMerchantsResponse.ProtoReflect.Descriptor instead.
func (*ListMerchantsResponse) Descriptor() ([]byte, []int) {
	return file_merchant_v1_merchant_proto_rawDescGZIP(), []int{5}
}

func (x *ListMerchantsResponse) GetMerchants() []*Merchant {
	if x != nil {
		return x.Merchants
	}
	return nil
}

type GetMerchantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMerchantRequest) Reset() {
	*x = GetMerchantRequest{}
	mi := &file_merchant_v1_merchant_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMerchantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMerchantRequest) ProtoMessage() {}

func (x *GetMerchantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_v1_merchant_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMerchantRequest.ProtoReflect.Descriptor instead.
func (*GetMerchantRequest) Descriptor() ([]byte, []int) {
	return file_merchant_v1_merchant_proto_rawDescGZIP(), []int{6}
}

func (x *GetMerchantRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetMerchantResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Merchant      *Merchant              `protobuf:"bytes,1,opt,name=merchant,proto3" json:"merchant,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMerchantResponse) Reset() {
	*x = GetMerchantResponse{}
	mi := &file_merchant_v1_merchant_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMerchantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMerchantResponse) ProtoMessage() {}

func (x *GetMerchantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_v1_merchant_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMerchantResponse.ProtoReflect.Descriptor instead.
func (*GetMerchantResponse) Descriptor() ([]byte, []int) {
	return file_merchant_v1_merchant_proto_rawDescGZIP(), []int{7}
}

func (x *GetMerchantResponse) GetMerchant() *Merchant {
	if x != nil {
		return x.Merchant
	}
	return nil
}

type CreateMerchantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Merchant      *Merchant              `protobuf:"bytes,1,opt,name=merchant,proto3" json:"merchant,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMerchantRequest) Reset() {
	*x = CreateMerchantRequest{}
	mi := &file_merchant_v1_merchant_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMerchantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMerchantRequest) ProtoMessage() {}

func (x *CreateMerchantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_v1_merchant_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMerchantRequest.ProtoReflect.Descriptor instead.
func (*CreateMerchantRequest) Descriptor() ([]byte, []int) {
	return file_merchant_v1_merchant_proto_rawDescGZIP(), []int{8}
}

func (x *CreateMerchantRequest) GetMerchant() *Merchant {
	if x != nil {
		return x.Merchant
	}
	return nil
}

type CreateMerchantResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Merchant      *Merchant              `protobuf:"bytes,1,opt,name=merchant,proto3" json:"merchant,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMerchantResponse) Reset() {
	*x = CreateMerchantResponse{}
	mi := &file_merchant_v1_merchant_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMerchantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMerchantResponse) ProtoMessage() {}

func (x *CreateMerchantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_v1_merchant_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMerchantResponse.ProtoReflect.Descriptor instead.
func (*CreateMerchantResponse) Descriptor() ([]byte, []int) {
	return file_merchant_v1_merchant_proto_rawDescGZIP(), []int{9}
}

func (x *CreateMerchantResponse) GetMerchant() *Merchant {
	if x != nil {
		return x.Merchant
	}
	return nil
}

type UpdateMerchantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Merchant      *Merchant              `protobuf:"bytes,2,opt,name=merchant,proto3" json:"merchant,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMerchantRequest) Reset() {
	*x = UpdateMerchantRequest{}
	mi := &file_merchant_v1_merchant_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMerchantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMerchantRequest) ProtoMessage() {}

func (x *UpdateMerchantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_v1_merchant_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMerchantRequest.ProtoReflect.Descriptor instead.
func (*UpdateMerchantRequest) Descriptor() ([]byte, []int) {
	return file_merchant_v1_merchant_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateMerchantRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateMerchantRequest) GetMerchant() *Merchant {
	if x != nil {
		return x.Merchant
	}
	return nil
}

type UpdateMerchantResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Merchant      *Merchant              `protobuf:"bytes,1,opt,name=merchant,proto3" json:"merchant,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMerchantResponse) Reset() {
	*x = UpdateMerchantResponse{}
	mi := &file_merchant_v1_merchant_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMerchantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMerchantResponse) ProtoMessage() {}

func (x *UpdateMerchantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_v1_merchant_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMerchantResponse.ProtoReflect.Descriptor instead.
func (*UpdateMerchantResponse) Descriptor() ([]byte, []int) {
	return file_merchant_v1_merchant_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateMerchantResponse) GetMerchant() *Merchant {
	if x != nil {
		return x.Merchant
	}
	return nil
}

type ListStoresRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MerchantId    string                 `protobuf:"bytes,1,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListStoresRequest) Reset() {
	*x = ListStoresRequest{}
	mi := &file_merchant_v1_merchant_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListStoresRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListStoresRequest) ProtoMessage() {}

func (x *ListStoresRequest) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_v1_merchant_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListStoresRequest.ProtoReflect.Descriptor instead.
func (*ListStoresRequest) Descriptor() ([]byte, []int) {
	return file_merchant_v1_merchant_proto_rawDescGZIP(), []int{12}
}

func (x *ListStoresRequest) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

type ListStoresResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stores        []*Store               `protobuf:"bytes,1,rep,name=stores,proto3" json:"stores,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListStoresResponse) Reset() {
	*x = ListStoresResponse{}
	mi := &file_merchant_v1_merchant_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListStoresResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListStoresResponse) ProtoMessage() {}

func (x *ListStoresResponse) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_v1_merchant_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListStoresResponse.ProtoReflect.Descriptor instead.
func (*ListStoresResponse) Descriptor() ([]byte, []int) {
	return file_merchant_v1_merchant_proto_rawDescGZIP(), []int{13}
}

func (x *ListStoresResponse) GetStores() []*Store {
	if x != nil {
		return x.Stores
	}
	return nil
}

type MerchantProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MerchantProfileRequest) Reset() {
	*x = MerchantProfileRequest{}
	mi := &file_merchant_v1_merchant_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MerchantProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MerchantProfileRequest) ProtoMessage() {}

func (x *MerchantProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_v1_merchant_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MerchantProfileRequest.ProtoReflect.Descriptor instead.
func (*MerchantProfileRequest) Descriptor() ([]byte, []int) {
	return file_merchant_v1_merchant_proto_rawDescGZIP(), []int{14}
}

type MerchantProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Merchant      *Merchant              `protobuf:"bytes,1,opt,name=merchant,proto3" json:"merchant,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MerchantProfileResponse) Reset() {
	*x = MerchantProfileResponse{}
	mi := &file_merchant_v1_merchant_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MerchantProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MerchantProfileResponse) ProtoMessage() {}

func (x *MerchantProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_v1_merchant_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MerchantProfileResponse.ProtoReflect.Descriptor instead.
func (*MerchantProfileResponse) Descriptor() ([]byte, []int) {
	return file_merchant_v1_merchant_proto_rawDescGZIP(), []int{15}
}

func (x *MerchantProfileResponse) GetMerchant() *Merchant {
	if x != nil {
		return x.Merchant
	}
	return nil
}

type MerchantStoresRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MerchantStoresRequest) Reset() {
	*x = MerchantStoresRequest{}
	mi := &file_merchant_v1_merchant_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MerchantStoresRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MerchantStoresRequest) ProtoMessage() {}

func (x *MerchantStoresRequest) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_v1_merchant_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MerchantStoresRequest.ProtoReflect.Descriptor instead.
func (*MerchantStoresRequest) Descriptor() ([]byte, []int) {
	return file_merchant_v1_merchant_proto_rawDescGZIP(), []int{16}
}

type MerchantStoresResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stores        []*Store               `protobuf:"bytes,1,rep,name=stores,proto3" json:"stores,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MerchantStoresResponse) Reset() {
	*x = MerchantStoresResponse{}
	mi := &file_merchant_v1_merchant_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MerchantStoresResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MerchantStoresResponse) ProtoMessage() {}

func (x *MerchantStoresResponse) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_v1_merchant_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MerchantStoresResponse.ProtoReflect.Descriptor instead.
func (*MerchantStoresResponse) Descriptor() ([]byte, []int) {
	return file_merchant_v1_merchant_proto_rawDescGZIP(), []int{17}
}

func (x *MerchantStoresResponse) GetStores() []*Store {
	if x != nil {
		return x.Stores
	}
	return nil
}

// GetBrandMerchantRequest resolves a brand to its owning merchant without exposing brand data.
type GetBrandMerchantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BrandId       string                 `protobuf:"bytes,1,opt,name=brand_id,json=brandId,proto3" json:"brand_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBrandMerchantRequest) Reset() {
	*x = GetBrandMerchantRequest{}
	mi := &file_merchant_v1_merchant_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBrandMerchantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBrandMerchantRequest) ProtoMessage() {}

func (x *GetBrandMerchantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_v1_merchant_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBrandMerchantRequest.ProtoReflect.Descriptor instead.
func (*GetBrandMerchantRequest) Descriptor() ([]byte, []int) {
	return file_merchant_v1_merchant_proto_rawDescGZIP(), []int{18}
}

func (x *GetBrandMerchantRequest) GetBrandId() string {
	if x != nil {
		return x.BrandId
	}
	return ""
}

type GetBrandMerchantResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MerchantId    string                 `protobuf:"bytes,1,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBrandMerchantResponse) Reset() {
	*x = GetBrandMerchantResponse{}
	mi := &file_merchant_v1_merchant_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBrandMerchantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBrandMerchantResponse) ProtoMessage() {}

func (x *GetBrandMerchantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_v1_merchant_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBrandMerchantResponse.ProtoReflect.Descriptor instead.
func (*GetBrandMerchantResponse) Descriptor() ([]byte, []int) {
	return file_merchant_v1_merchant_proto_rawDescGZIP(), []int{19}
}

func (x *GetBrandMerchantResponse) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

// GetStoreMerchantRequest resolves a store to its owning merchant without exposing store data.
type GetStoreMerchantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StoreId       string                 `protobuf:"bytes,1,opt,name=store_id,json=storeId,proto3" json:"store_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStoreMerchantRequest) Reset() {
	*x = GetStoreMerchantRequest{}
	mi := &file_merchant_v1_merchant_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStoreMerchantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStoreMerchantRequest) ProtoMessage() {}

func (x *GetStoreMerchantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_v1_merchant_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStoreMerchantRequest.ProtoReflect.Descriptor instead.
func (*GetStoreMerchantRequest) Descriptor() ([]byte, []int) {
	return file_merchant_v1_merchant_proto_rawDescGZIP(), []int{20}
}

func (x *GetStoreMerchantRequest) GetStoreId() string {
	if x != nil {
		return x.StoreId
	}
	return ""
}

type GetStoreMerchantResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MerchantId    string                 `protobuf:"bytes,1,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStoreMerchantResponse) Reset() {
	*x = GetStoreMerchantResponse{}
	mi := &file_merchant_v1_merchant_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStoreMerchantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStoreMerchantResponse) ProtoMessage() {}

func (x *GetStoreMerchantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_v1_merchant_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStoreMerchantResponse.ProtoReflect.Descriptor instead.
func (*GetStoreMerchantResponse) Descriptor() ([]byte, []int) {
	return file_merchant_v1_merchant_proto_rawDescGZIP(), []int{21}
}

func (x *GetStoreMerchantResponse) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

// GetStore reads one store. It answers the question GetStoreMerchant cannot:
// not just whose the store is, but whether it is usable right now.
//
// The caller is coffee-machine-service, which validates a device's deployment
// point before writing it. A store_id there is a value reference into this
// service, and a reference nobody checks is how a device ends up deployed to a
// store that never existed or has since been disabled.
type GetStoreRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StoreId       string                 `protobuf:"bytes,1,opt,name=store_id,json=storeId,proto3" json:"store_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStoreRequest) Reset() {
	*x = GetStoreRequest{}
	mi := &file_merchant_v1_merchant_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStoreRequest) ProtoMessage() {}

func (x *GetStoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_v1_merchant_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStoreRequest.ProtoReflect.Descriptor instead.
func (*GetStoreRequest) Descriptor() ([]byte, []int) {
	return file_merchant_v1_merchant_proto_rawDescGZIP(), []int{22}
}

func (x *GetStoreRequest) GetStoreId() string {
	if x != nil {
		return x.StoreId
	}
	return ""
}

// A store_id that does not exist is reported as NOT_FOUND, not as an empty
// Store: absent and empty are different answers, and a caller that has to treat
// them alike would have to guess which one it got.
type GetStoreResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Store         *Store                 `protobuf:"bytes,1,opt,name=store,proto3" json:"store,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStoreResponse) Reset() {
	*x = GetStoreResponse{}
	mi := &file_merchant_v1_merchant_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStoreResponse) ProtoMessage() {}

func (x *GetStoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_v1_merchant_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStoreResponse.ProtoReflect.Descriptor instead.
func (*GetStoreResponse) Descriptor() ([]byte, []int) {
	return file_merchant_v1_merchant_proto_rawDescGZIP(), []int{23}
}

func (x *GetStoreResponse) GetStore() *Store {
	if x != nil {
		return x.Store
	}
	return nil
}

// ResolveScopeNamesRequest asks for the display names of the brand and store
// scopes a set of merchant accounts points at. The two kinds travel as separate
// lists because they live in separate tables, and one call answers a whole page
// of accounts rather than one call per account.
type ResolveScopeNamesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BrandIds      []string               `protobuf:"bytes,1,rep,name=brand_ids,json=brandIds,proto3" json:"brand_ids,omitempty"`
	StoreIds      []string               `protobuf:"bytes,2,rep,name=store_ids,json=storeIds,proto3" json:"store_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveScopeNamesRequest) Reset() {
	*x = ResolveScopeNamesRequest{}
	mi := &file_merchant_v1_merchant_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveScopeNamesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveScopeNamesRequest) ProtoMessage() {}

func (x *ResolveScopeNamesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_v1_merchant_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveScopeNamesRequest.ProtoReflect.Descriptor instead.
func (*ResolveScopeNamesRequest) Descriptor() ([]byte, []int) {
	return file_merchant_v1_merchant_proto_rawDescGZIP(), []int{24}
}

func (x *ResolveScopeNamesRequest) GetBrandIds() []string {
	if x != nil {
		return x.BrandIds
	}
	return nil
}

func (x *ResolveScopeNamesRequest) GetStoreIds() []string {
	if x != nil {
		return x.StoreIds
	}
	return nil
}

// ResolveScopeNamesResponse maps an id to its name. An id that no longer exists
// is simply absent: a deleted scope must not fail an account listing, and the
// caller renders the account without a scope name.
type ResolveScopeNamesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BrandNames    map[string]string      `protobuf:"bytes,1,rep,name=brand_names,json=brandNames,proto3" json:"brand_names,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	StoreNames    map[string]string      `protobuf:"bytes,2,rep,name=store_names,json=storeNames,proto3" json:"store_names,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveScopeNamesResponse) Reset() {
	*x = ResolveScopeNamesResponse{}
	mi := &file_merchant_v1_merchant_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveScopeNamesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveScopeNamesResponse) ProtoMessage() {}

func (x *ResolveScopeNamesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_v1_merchant_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveScopeNamesResponse.ProtoReflect.Descriptor instead.
func (*ResolveScopeNamesResponse) Descriptor() ([]byte, []int) {
	return file_merchant_v1_merchant_proto_rawDescGZIP(), []int{25}
}

func (x *ResolveScopeNamesResponse) GetBrandNames() map[string]string {
	if x != nil {
		return x.BrandNames
	}
	return nil
}

func (x *ResolveScopeNamesResponse) GetStoreNames() map[string]string {
	if x != nil {
		return x.StoreNames
	}
	return nil
}

// ListStoreIDsRequest expands a merchant account's data scope into the set of
// stores it authorizes.
//
// It is the one place that knows how scope_type maps onto this service's own
// tables, so every consumer downstream can filter on a plain list of ids instead
// of re-deriving what "brand-scoped" means.
//
// merchant_id is not optional and is not derived from scope_id: a brand id or a
// store id from another tenant must not widen the answer, so every branch of the
// query is anchored on it.
type ListStoreIDsRequest struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	MerchantId string                 `protobuf:"bytes,1,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	// scope_type is "merchant", "brand" or "store". Anything else is rejected
	// rather than treated as merchant-level — guessing wide on an unrecognized
	// value is how a typo becomes a full listing.
	ScopeType string `protobuf:"bytes,2,opt,name=scope_type,json=scopeType,proto3" json:"scope_type,omitempty"`
	// scope_id is the brand or store; it must be empty at merchant level and
	// present otherwise.
	ScopeId       string `protobuf:"bytes,3,opt,name=scope_id,json=scopeId,proto3" json:"scope_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListStoreIDsRequest) Reset() {
	*x = ListStoreIDsRequest{}
	mi := &file_merchant_v1_merchant_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListStoreIDsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListStoreIDsRequest) ProtoMessage() {}

func (x *ListStoreIDsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_v1_merchant_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListStoreIDsRequest.ProtoReflect.Descriptor instead.
func (*ListStoreIDsRequest) Descriptor() ([]byte, []int) {
	return file_merchant_v1_merchant_proto_rawDescGZIP(), []int{26}
}

func (x *ListStoreIDsRequest) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *ListStoreIDsRequest) GetScopeType() string {
	if x != nil {
		return x.ScopeType
	}
	return ""
}

func (x *ListStoreIDsRequest) GetScopeId() string {
	if x != nil {
		return x.ScopeId
	}
	return ""
}

// ListStoreIDsResponse carries ids only. Callers need the set to filter their own
// tables, and returning whole Store rows would ship fields nothing reads.
type ListStoreIDsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StoreIds      []string               `protobuf:"bytes,1,rep,name=store_ids,json=storeIds,proto3" json:"store_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListStoreIDsResponse) Reset() {
	*x = ListStoreIDsResponse{}
	mi := &file_merchant_v1_merchant_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListStoreIDsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListStoreIDsResponse) ProtoMessage() {}

func (x *ListStoreIDsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_v1_merchant_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListStoreIDsResponse.ProtoReflect.Descriptor instead.
func (*ListStoreIDsResponse) Descriptor() ([]byte, []int) {
	return file_merchant_v1_merchant_proto_rawDescGZIP(), []int{27}
}

func (x *ListStoreIDsResponse) GetStoreIds() []string {
	if x != nil {
		return x.StoreIds
	}
	return nil
}

var File_merchant_v1_merchant_proto protoreflect.FileDescriptor

const file_merchant_v1_merchant_proto_rawDesc = "" +
	"\n" +
	"\x1amerchant/v1/merchant.proto\x12\x11panda.merchant.v1\"\x97\x02\n" +
	"\bMerchant\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12!\n" +
	"\fcontact_name\x18\x03 \x01(\tR\vcontactName\x12#\n" +
	"\rcontact_phone\x18\x04 \x01(\tR\fcontactPhone\x12)\n" +
	"\x10business_license\x18\x05 \x01(\tR\x0fbusinessLicense\x12\x18\n" +
	"\aaddress\x18\x06 \x01(\tR\aaddress\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12B\n" +
	"\vstatus_code\x18\b \x01(\x0e2!.panda.merchant.v1.MerchantStatusR\n" +
	"statusCode\"\xff\x02\n" +
	"\x05Brand\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vmerchant_id\x18\x02 \x01(\tR\n" +
	"merchantId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x12\n" +
	"\x04logo\x18\x04 \x01(\tR\x04logo\x12\x16\n" +
	"\x06banner\x18\x05 \x01(\tR\x06banner\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12!\n" +
	"\faudit_status\x18\b \x01(\tR\vauditStatus\x12\x18\n" +
	"\avisible\x18\t \x01(\bR\avisible\x12B\n" +
	"\vstatus_code\x18\n" +
	" \x01(\x0e2!.panda.merchant.v1.ResourceStatusR\n" +
	"statusCode\x12J\n" +
	"\x11audit_status_code\x18\v \x01(\x0e2\x1e.panda.merchant.v1.AuditStatusR\x0fauditStatusCode\"\xe2\x04\n" +
	"\x05Store\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vmerchant_id\x18\x02 \x01(\tR\n" +
	"merchantId\x12\x19\n" +
	"\bbrand_id\x18\x03 \x01(\tR\abrandId\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x12\n" +
	"\x04logo\x18\x05 \x01(\tR\x04logo\x12\x14\n" +
	"\x05phone\x18\x06 \x01(\tR\x05phone\x12\x1a\n" +
	"\bprovince\x18\a \x01(\tR\bprovince\x12\x12\n" +
	"\x04city\x18\b \x01(\tR\x04city\x12\x1a\n" +
	"\bdistrict\x18\t \x01(\tR\bdistrict\x12\x18\n" +
	"\aaddress\x18\n" +
	" \x01(\tR\aaddress\x12%\n" +
	"\x0ebusiness_hours\x18\v \x01(\tR\rbusinessHours\x12!\n" +
	"\tlongitude\x18\f \x01(\x01H\x00R\tlongitude\x88\x01\x01\x12\x1f\n" +
	"\blatitude\x18\r \x01(\x01H\x01R\blatitude\x88\x01\x01\x12\x16\n" +
	"\x06status\x18\x0e \x01(\tR\x06status\x12\x18\n" +
	"\avisible\x18\x0f \x01(\bR\avisible\x12!\n" +
	"\faudit_status\x18\x10 \x01(\tR\vauditStatus\x12B\n" +
	"\vstatus_code\x18\x11 \x01(\x0e2!.panda.merchant.v1.ResourceStatusR\n" +
	"statusCode\x12J\n" +
	"\x11audit_status_code\x18\x12 \x01(\x0e2\x1e.panda.merchant.v1.AuditStatusR\x0fauditStatusCodeB\f\n" +
	"\n" +
	"_longitudeB\v\n" +
	"\t_latitude\"\x85\x01\n" +
	"\x0fMerchantAccount\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x1f\n" +
	"\vmerchant_id\x18\x02 \x01(\tR\n" +
	"merchantId\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\"\x16\n" +
	"\x14ListMerchantsRequest\"R\n" +
	"\x15ListMerchantsResponse\x129\n" +
	"\tmerchants\x18\x01 \x03(\v2\x1b.panda.merchant.v1.MerchantR\tmerchants\"$\n" +
	"\x12GetMerchantRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"N\n" +
	"\x13GetMerchantResponse\x127\n" +
	"\bmerchant\x18\x01 \x01(\v2\x1b.panda.merchant.v1.MerchantR\bmerchant\"P\n" +
	"\x15CreateMerchantRequest\x127\n" +
	"\bmerchant\x18\x01 \x01(\v2\x1b.panda.merchant.v1.MerchantR\bmerchant\"Q\n" +
	"\x16CreateMerchantResponse\x127\n" +
	"\bmerchant\x18\x01 \x01(\v2\x1b.panda.merchant.v1.MerchantR\bmerchant\"`\n" +
	"\x15UpdateMerchantRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x127\n" +
	"\bmerchant\x18\x02 \x01(\v2\x1b.panda.merchant.v1.MerchantR\bmerchant\"Q\n" +
	"\x16UpdateMerchantResponse\x127\n" +
	"\bmerchant\x18\x01 \x01(\v2\x1b.panda.merchant.v1.MerchantR\bmerchant\"4\n" +
	"\x11ListStoresRequest\x12\x1f\n" +
	"\vmerchant_id\x18\x01 \x01(\tR\n" +
	"merchantId\"F\n" +
	"\x12ListStoresResponse\x120\n" +
	"\x06stores\x18\x01 \x03(\v2\x18.panda.merchant.v1.StoreR\x06stores\"\x18\n" +
	"\x16MerchantProfileRequest\"R\n" +
	"\x17MerchantProfileResponse\x127\n" +
	"\bmerchant\x18\x01 \x01(\v2\x1b.panda.merchant.v1.MerchantR\bmerchant\"\x17\n" +
	"\x15MerchantStoresRequest\"J\n" +
	"\x16MerchantStoresResponse\x120\n" +
	"\x06stores\x18\x01 \x03(\v2\x18.panda.merchant.v1.StoreR\x06stores\"4\n" +
	"\x17GetBrandMerchantRequest\x12\x19\n" +
	"\bbrand_id\x18\x01 \x01(\tR\abrandId\";\n" +
	"\x18GetBrandMerchantResponse\x12\x1f\n" +
	"\vmerchant_id\x18\x01 \x01(\tR\n" +
	"merchantId\"4\n" +
	"\x17GetStoreMerchantRequest\x12\x19\n" +
	"\bstore_id\x18\x01 \x01(\tR\astoreId\";\n" +
	"\x18GetStoreMerchantResponse\x12\x1f\n" +
	"\vmerchant_id\x18\x01 \x01(\tR\n" +
	"merchantId\",\n" +
	"\x0fGetStoreRequest\x12\x19\n" +
	"\bstore_id\x18\x01 \x01(\tR\astoreId\"B\n" +
	"\x10GetStoreResponse\x12.\n" +
	"\x05store\x18\x01 \x01(\v2\x18.panda.merchant.v1.StoreR\x05store\"T\n" +
	"\x18ResolveScopeNamesRequest\x12\x1b\n" +
	"\tbrand_ids\x18\x01 \x03(\tR\bbrandIds\x12\x1b\n" +
	"\tstore_ids\x18\x02 \x03(\tR\bstoreIds\"\xd7\x02\n" +
	"\x19ResolveScopeNamesResponse\x12]\n" +
	"\vbrand_names\x18\x01 \x03(\v2<.panda.merchant.v1.ResolveScopeNamesResponse.BrandNamesEntryR\n" +
	"brandNames\x12]\n" +
	"\vstore_names\x18\x02 \x03(\v2<.panda.merchant.v1.ResolveScopeNamesResponse.StoreNamesEntryR\n" +
	"storeNames\x1a=\n" +
	"\x0fBrandNamesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a=\n" +
	"\x0fStoreNamesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"p\n" +
	"\x13ListStoreIDsRequest\x12\x1f\n" +
	"\vmerchant_id\x18\x01 \x01(\tR\n" +
	"merchantId\x12\x1d\n" +
	"\n" +
	"scope_type\x18\x02 \x01(\tR\tscopeType\x12\x19\n" +
	"\bscope_id\x18\x03 \x01(\tR\ascopeId\"3\n" +
	"\x14ListStoreIDsResponse\x12\x1b\n" +
	"\tstore_ids\x18\x01 \x03(\tR\bstoreIds*\x89\x01\n" +
	"\x0eMerchantStatus\x12\x1f\n" +
	"\x1bMERCHANT_STATUS_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17MERCHANT_STATUS_PENDING\x10\x01\x12\x1a\n" +
	"\x16MERCHANT_STATUS_ACTIVE\x10\x02\x12\x1d\n" +
	"\x19MERCHANT_STATUS_SUSPENDED\x10\x03*k\n" +
	"\x0eResourceStatus\x12\x1f\n" +
	"\x1bRESOURCE_STATUS_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16RESOURCE_STATUS_ACTIVE\x10\x01\x12\x1c\n" +
	"\x18RESOURCE_STATUS_DISABLED\x10\x02*{\n" +
	"\vAuditStatus\x12\x1c\n" +
	"\x18AUDIT_STATUS_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14AUDIT_STATUS_PENDING\x10\x01\x12\x19\n" +
	"\x15AUDIT_STATUS_APPROVED\x10\x02\x12\x19\n" +
	"\x15AUDIT_STATUS_REJECTED\x10\x032\xbd\t\n" +
	"\x0fMerchantService\x12b\n" +
	"\rListMerchants\x12'.panda.merchant.v1.ListMerchantsRequest\x1a(.panda.merchant.v1.ListMerchantsResponse\x12\\\n" +
	"\vGetMerchant\x12%.panda.merchant.v1.GetMerchantRequest\x1a&.panda.merchant.v1.GetMerchantResponse\x12e\n" +
	"\x0eCreateMerchant\x12(.panda.merchant.v1.CreateMerchantRequest\x1a).panda.merchant.v1.CreateMerchantResponse\x12e\n" +
	"\x0eUpdateMerchant\x12(.panda.merchant.v1.UpdateMerchantRequest\x1a).panda.merchant.v1.UpdateMerchantResponse\x12Y\n" +
	"\n" +
	"ListStores\x12$.panda.merchant.v1.ListStoresRequest\x1a%.panda.merchant.v1.ListStoresResponse\x12`\n" +
	"\aProfile\x12).panda.merchant.v1.MerchantProfileRequest\x1a*.panda.merchant.v1.MerchantProfileResponse\x12]\n" +
	"\x06Stores\x12(.panda.merchant.v1.MerchantStoresRequest\x1a).panda.merchant.v1.MerchantStoresResponse\x12k\n" +
	"\x10GetBrandMerchant\x12*.panda.merchant.v1.GetBrandMerchantRequest\x1a+.panda.merchant.v1.GetBrandMerchantResponse\x12k\n" +
	"\x10GetStoreMerchant\x12*.panda.merchant.v1.GetStoreMerchantRequest\x1a+.panda.merchant.v1.GetStoreMerchantResponse\x12S\n" +
	"\bGetStore\x12\".panda.merchant.v1.GetStoreRequest\x1a#.panda.merchant.v1.GetStoreResponse\x12n\n" +
	"\x11ResolveScopeNames\x12+.panda.merchant.v1.ResolveScopeNamesRequest\x1a,.panda.merchant.v1.ResolveScopeNamesResponse\x12_\n" +
	"\fListStoreIDs\x12&.panda.merchant.v1.ListStoreIDsRequest\x1a'.panda.merchant.v1.ListStoreIDsResponseB;Z9github.com/panda-dev/panda-v2/contracts/proto/merchant/v1b\x06proto3"

var (
	file_merchant_v1_merchant_proto_rawDescOnce sync.Once
	file_merchant_v1_merchant_proto_rawDescData []byte
)

func file_merchant_v1_merchant_proto_rawDescGZIP() []byte {
	file_merchant_v1_merchant_proto_rawDescOnce.Do(func() {
		file_merchant_v1_merchant_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_merchant_v1_merchant_proto_rawDesc), len(file_merchant_v1_merchant_proto_rawDesc)))
	})
	return file_merchant_v1_merchant_proto_rawDescData
}

var file_merchant_v1_merchant_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_merchant_v1_merchant_proto_msgTypes = make([]protoimpl.MessageInfo, 30)
var file_merchant_v1_merchant_proto_goTypes = []any{
	(MerchantStatus)(0),               // 0: panda.merchant.v1.MerchantStatus
	(ResourceStatus)(0),               // 1: panda.merchant.v1.ResourceStatus
	(AuditStatus)(0),                  // 2: panda.merchant.v1.AuditStatus
	(*Merchant)(nil),                  // 3: panda.merchant.v1.Merchant
	(*Brand)(nil),                     // 4: panda.merchant.v1.Brand
	(*Store)(nil),                     // 5: panda.merchant.v1.Store
	(*MerchantAccount)(nil),           // 6: panda.merchant.v1.MerchantAccount
	(*ListMerchantsRequest)(nil),      // 7: panda.merchant.v1.ListMerchantsRequest
	(*ListMerchantsResponse)(nil),     // 8: panda.merchant.v1.ListMerchantsResponse
	(*GetMerchantRequest)(nil),        // 9: panda.merchant.v1.GetMerchantRequest
	(*GetMerchantResponse)(nil),       // 10: panda.merchant.v1.GetMerchantResponse
	(*CreateMerchantRequest)(nil),     // 11: panda.merchant.v1.CreateMerchantRequest
	(*CreateMerchantResponse)(nil),    // 12: panda.merchant.v1.CreateMerchantResponse
	(*UpdateMerchantRequest)(nil),     // 13: panda.merchant.v1.UpdateMerchantRequest
	(*UpdateMerchantResponse)(nil),    // 14: panda.merchant.v1.UpdateMerchantResponse
	(*ListStoresRequest)(nil),         // 15: panda.merchant.v1.ListStoresRequest
	(*ListStoresResponse)(nil),        // 16: panda.merchant.v1.ListStoresResponse
	(*MerchantProfileRequest)(nil),    // 17: panda.merchant.v1.MerchantProfileRequest
	(*MerchantProfileResponse)(nil),   // 18: panda.merchant.v1.MerchantProfileResponse
	(*MerchantStoresRequest)(nil),     // 19: panda.merchant.v1.MerchantStoresRequest
	(*MerchantStoresResponse)(nil),    // 20: panda.merchant.v1.MerchantStoresResponse
	(*GetBrandMerchantRequest)(nil),   // 21: panda.merchant.v1.GetBrandMerchantRequest
	(*GetBrandMerchantResponse)(nil),  // 22: panda.merchant.v1.GetBrandMerchantResponse
	(*GetStoreMerchantRequest)(nil),   // 23: panda.merchant.v1.GetStoreMerchantRequest
	(*GetStoreMerchantResponse)(nil),  // 24: panda.merchant.v1.GetStoreMerchantResponse
	(*GetStoreRequest)(nil),           // 25: panda.merchant.v1.GetStoreRequest
	(*GetStoreResponse)(nil),          // 26: panda.merchant.v1.GetStoreResponse
	(*ResolveScopeNamesRequest)(nil),  // 27: panda.merchant.v1.ResolveScopeNamesRequest
	(*ResolveScopeNamesResponse)(nil), // 28: panda.merchant.v1.ResolveScopeNamesResponse
	(*ListStoreIDsRequest)(nil),       // 29: panda.merchant.v1.ListStoreIDsRequest
	(*ListStoreIDsResponse)(nil),      // 30: panda.merchant.v1.ListStoreIDsResponse
	nil,                               // 31: panda.merchant.v1.ResolveScopeNamesResponse.BrandNamesEntry
	nil,                               // 32: panda.merchant.v1.ResolveScopeNamesResponse.StoreNamesEntry
}
var file_merchant_v1_merchant_proto_depIdxs = []int32{
	0,  // 0: panda.merchant.v1.Merchant.status_code:type_name -> panda.merchant.v1.MerchantStatus
	1,  // 1: panda.merchant.v1.Brand.status_code:type_name -> panda.merchant.v1.ResourceStatus
	2,  // 2: panda.merchant.v1.Brand.audit_status_code:type_name -> panda.merchant.v1.AuditStatus
	1,  // 3: panda.merchant.v1.Store.status_code:type_name -> panda.merchant.v1.ResourceStatus
	2,  // 4: panda.merchant.v1.Store.audit_status_code:type_name -> panda.merchant.v1.AuditStatus
	3,  // 5: panda.merchant.v1.ListMerchantsResponse.merchants:type_name -> panda.merchant.v1.Merchant
	3,  // 6: panda.merchant.v1.GetMerchantResponse.merchant:type_name -> panda.merchant.v1.Merchant
	3,  // 7: panda.merchant.v1.CreateMerchantRequest.merchant:type_name -> panda.merchant.v1.Merchant
	3,  // 8: panda.merchant.v1.CreateMerchantResponse.merchant:type_name -> panda.merchant.v1.Merchant
	3,  // 9: panda.merchant.v1.UpdateMerchantRequest.merchant:type_name -> panda.merchant.v1.Merchant
	3,  // 10: panda.merchant.v1.UpdateMerchantResponse.merchant:type_name -> panda.merchant.v1.Merchant
	5,  // 11: panda.merchant.v1.ListStoresResponse.stores:type_name -> panda.merchant.v1.Store
	3,  // 12: panda.merchant.v1.MerchantProfileResponse.merchant:type_name -> panda.merchant.v1.Merchant
	5,  // 13: panda.merchant.v1.MerchantStoresResponse.stores:type_name -> panda.merchant.v1.Store
	5,  // 14: panda.merchant.v1.GetStoreResponse.store:type_name -> panda.merchant.v1.Store
	31, // 15: panda.merchant.v1.ResolveScopeNamesResponse.brand_names:type_name -> panda.merchant.v1.ResolveScopeNamesResponse.BrandNamesEntry
	32, // 16: panda.merchant.v1.ResolveScopeNamesResponse.store_names:type_name -> panda.merchant.v1.ResolveScopeNamesResponse.StoreNamesEntry
	7,  // 17: panda.merchant.v1.MerchantService.ListMerchants:input_type -> panda.merchant.v1.ListMerchantsRequest
	9,  // 18: panda.merchant.v1.MerchantService.GetMerchant:input_type -> panda.merchant.v1.GetMerchantRequest
	11, // 19: panda.merchant.v1.MerchantService.CreateMerchant:input_type -> panda.merchant.v1.CreateMerchantRequest
	13, // 20: panda.merchant.v1.MerchantService.UpdateMerchant:input_type -> panda.merchant.v1.UpdateMerchantRequest
	15, // 21: panda.merchant.v1.MerchantService.ListStores:input_type -> panda.merchant.v1.ListStoresRequest
	17, // 22: panda.merchant.v1.MerchantService.Profile:input_type -> panda.merchant.v1.MerchantProfileRequest
	19, // 23: panda.merchant.v1.MerchantService.Stores:input_type -> panda.merchant.v1.MerchantStoresRequest
	21, // 24: panda.merchant.v1.MerchantService.GetBrandMerchant:input_type -> panda.merchant.v1.GetBrandMerchantRequest
	23, // 25: panda.merchant.v1.MerchantService.GetStoreMerchant:input_type -> panda.merchant.v1.GetStoreMerchantRequest
	25, // 26: panda.merchant.v1.MerchantService.GetStore:input_type -> panda.merchant.v1.GetStoreRequest
	27, // 27: panda.merchant.v1.MerchantService.ResolveScopeNames:input_type -> panda.merchant.v1.ResolveScopeNamesRequest
	29, // 28: panda.merchant.v1.MerchantService.ListStoreIDs:input_type -> panda.merchant.v1.ListStoreIDsRequest
	8,  // 29: panda.merchant.v1.MerchantService.ListMerchants:output_type -> panda.merchant.v1.ListMerchantsResponse
	10, // 30: panda.merchant.v1.MerchantService.GetMerchant:output_type -> panda.merchant.v1.GetMerchantResponse
	12, // 31: panda.merchant.v1.MerchantService.CreateMerchant:output_type -> panda.merchant.v1.CreateMerchantResponse
	14, // 32: panda.merchant.v1.MerchantService.UpdateMerchant:output_type -> panda.merchant.v1.UpdateMerchantResponse
	16, // 33: panda.merchant.v1.MerchantService.ListStores:output_type -> panda.merchant.v1.ListStoresResponse
	18, // 34: panda.merchant.v1.MerchantService.Profile:output_type -> panda.merchant.v1.MerchantProfileResponse
	20, // 35: panda.merchant.v1.MerchantService.Stores:output_type -> panda.merchant.v1.MerchantStoresResponse
	22, // 36: panda.merchant.v1.MerchantService.GetBrandMerchant:output_type -> panda.merchant.v1.GetBrandMerchantResponse
	24, // 37: panda.merchant.v1.MerchantService.GetStoreMerchant:output_type -> panda.merchant.v1.GetStoreMerchantResponse
	26, // 38: panda.merchant.v1.MerchantService.GetStore:output_type -> panda.merchant.v1.GetStoreResponse
	28, // 39: panda.merchant.v1.MerchantService.ResolveScopeNames:output_type -> panda.merchant.v1.ResolveScopeNamesResponse
	30, // 40: panda.merchant.v1.MerchantService.ListStoreIDs:output_type -> panda.merchant.v1.ListStoreIDsResponse
	29, // [29:41] is the sub-list for method output_type
	17, // [17:29] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_merchant_v1_merchant_proto_init() }
func file_merchant_v1_merchant_proto_init() {
	if File_merchant_v1_merchant_proto != nil {
		return
	}
	file_merchant_v1_merchant_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_merchant_v1_merchant_proto_rawDesc), len(file_merchant_v1_merchant_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   30,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_merchant_v1_merchant_proto_goTypes,
		DependencyIndexes: file_merchant_v1_merchant_proto_depIdxs,
		EnumInfos:         file_merchant_v1_merchant_proto_enumTypes,
		MessageInfos:      file_merchant_v1_merchant_proto_msgTypes,
	}.Build()
	File_merchant_v1_merchant_proto = out.File
	file_merchant_v1_merchant_proto_goTypes = nil
	file_merchant_v1_merchant_proto_depIdxs = nil
}
