import { defineConfig } from '@umijs/max';

export default defineConfig({
  antd: {},
  access: {},
  model: {},
  initialState: {},
  request: {},
  layout: {
    title: 'Panda 后台',
  },
  routes: [
    { path: '/login', component: 'login', layout: false },
    { path: '/', redirect: '/dashboard' },
    {
      path: '/dashboard',
      name: '概览',
      icon: 'DashboardOutlined',
      component: 'dashboard',
    },
    {
      path: '/permissions',
      name: '权限管理',
      icon: 'SafetyCertificateOutlined',
      component: 'permissions',
      access: 'canViewPermissions',
    },
    {
      path: '/roles',
      name: '角色管理',
      icon: 'TeamOutlined',
      component: 'roles',
      access: 'canViewRoles',
    },
    {
      path: '/admin-users',
      name: '管理员用户',
      icon: 'UserOutlined',
      component: 'admin-users',
      access: 'canViewAdminUsers',
    },
    {
      path: '/menus',
      name: '菜单管理',
      icon: 'MenuOutlined',
      component: 'menus',
      access: 'canViewMenus',
    },
    {
      path: '/merchants',
      name: '商户管理',
      icon: 'ShopOutlined',
      component: 'merchants',
      access: 'canViewMerchants',
    },
    {
      path: '/brands',
      name: '品牌管理',
      icon: 'TagOutlined',
      component: 'brands',
      access: 'canViewBrands',
    },
    {
      path: '/stores',
      name: '门店管理',
      icon: 'EnvironmentOutlined',
      component: 'stores',
      access: 'canViewStores',
    },
    {
      path: '/coupons',
      name: '优惠券管理',
      icon: 'GiftOutlined',
      access: 'canViewCoupons',
      routes: [
        { path: '/coupons/types', name: '优惠券类型', component: 'coupon-types', access: 'canViewCouponTypes' },
        { path: '/coupons/templates', name: '优惠券模板', component: 'coupon-templates', access: 'canViewCoupons' },
        { path: '/coupons/batches', name: '发券批次', component: 'coupon-batches', access: 'canManageCouponBatches' },
        { path: '/coupons/user-coupons', name: '用户券', component: 'user-coupons', access: 'canViewCouponUserCoupons' },
      ],
    },
    {
      path: '/coffee-machines',
      name: '设备管理',
      icon: 'CoffeeOutlined',
      access: 'canViewCoffeeMachines',
      routes: [
        { path: '/coffee-machines/devices', name: '咖啡机设备', component: 'coffee-machines/devices', access: 'canViewCoffeeMachines' },
        { path: '/coffee-machines/manufacturers', name: '厂商管理', component: 'coffee-machines/manufacturers', access: 'canViewCoffeeMachines' },
        { path: '/coffee-machines/drinks', name: '饮品管理', component: 'coffee-machines/drinks', access: 'canViewCoffeeMachines' },
      ],
    },
    {
      path: '/miniapp-users',
      name: '小程序用户',
      icon: 'ContactsOutlined',
      component: 'miniapp-users',
      access: 'canViewMiniappUsers',
    },
    {
      path: '/operation-logs',
      name: '操作日志',
      icon: 'HistoryOutlined',
      component: 'operation-logs',
      access: 'canViewOperationLogs',
    },
  ],
  npmClient: 'pnpm',
  mfsu: false,
  proxy: {
    '/api': {
      target: 'http://localhost:18080',
      changeOrigin: true,
      pathRewrite: { '^/api': '' },
    },
  },
});
