// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: coffee_machine/v1/coffee_machine.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Manufacturer struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// 稳定业务标识，创建后不可修改；旧系统靠它关联设备、饮品与出杯分支。
	Code         string `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Name         string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	ContactName  string `protobuf:"bytes,4,opt,name=contact_name,json=contactName,proto3" json:"contact_name,omitempty"`
	ContactPhone string `protobuf:"bytes,5,opt,name=contact_phone,json=contactPhone,proto3" json:"contact_phone,omitempty"`
	// active=启用，disabled=停用。
	Status        string `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Manufacturer) Reset() {
	*x = Manufacturer{}
	mi := &file_coffee_machine_v1_coffee_machine_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Manufacturer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Manufacturer) ProtoMessage() {}

func (x *Manufacturer) ProtoReflect() protoreflect.Message {
	mi := &file_coffee_machine_v1_coffee_machine_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Manufacturer.ProtoReflect.Descriptor instead.
func (*Manufacturer) Descriptor() ([]byte, []int) {
	return file_coffee_machine_v1_coffee_machine_proto_rawDescGZIP(), []int{0}
}

func (x *Manufacturer) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Manufacturer) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Manufacturer) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Manufacturer) GetContactName() string {
	if x != nil {
		return x.ContactName
	}
	return ""
}

func (x *Manufacturer) GetContactPhone() string {
	if x != nil {
		return x.ContactPhone
	}
	return ""
}

func (x *Manufacturer) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type Device struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ManufacturerId string                 `protobuf:"bytes,2,opt,name=manufacturer_id,json=manufacturerId,proto3" json:"manufacturer_id,omitempty"`
	SerialUnique   string                 `protobuf:"bytes,3,opt,name=serial_unique,json=serialUnique,proto3" json:"serial_unique,omitempty"`
	DeviceName     string                 `protobuf:"bytes,4,opt,name=device_name,json=deviceName,proto3" json:"device_name,omitempty"`
	// 部署点位，属于 merchant-service。本库不建外键，写入前由本服务调 merchant-service
	// 的 GetStore 确认点位存在且未被停用；确认不了就不写（回 503），而不是跳过校验。
	StoreId string `protobuf:"bytes,5,opt,name=store_id,json=storeId,proto3" json:"store_id,omitempty"`
	// 本系统是否启用：active=启用，disabled=停用。
	//
	// 这一列与下面的 vendor_online 是两件事，不能压成一个 status：status 是
	// 「我们让不让它用」，vendor_online 是「厂商说它此刻通不通」。下单校验（方案
	// 5.8）两条都要看。
	Status string `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	// 厂商上报的在线状态。用 optional 是为了保住第三种情况：从未同步过不等于
	// 离线，读到一个零值 false 的调用方分不清「我们知道它离线」和「我们不知道」。
	VendorOnline *bool `protobuf:"varint,7,opt,name=vendor_online,json=vendorOnline,proto3,oneof" json:"vendor_online,omitempty"`
	// 最近一次厂商同步时间，用于判断上面那个在线状态有多旧。
	LastSyncedAtUnix *int64 `protobuf:"varint,8,opt,name=last_synced_at_unix,json=lastSyncedAtUnix,proto3,oneof" json:"last_synced_at_unix,omitempty"`
	// 最近一次故障码与描述，空串表示没有故障记录。
	LastFaultCode    string `protobuf:"bytes,9,opt,name=last_fault_code,json=lastFaultCode,proto3" json:"last_fault_code,omitempty"`
	LastFaultMessage string `protobuf:"bytes,10,opt,name=last_fault_message,json=lastFaultMessage,proto3" json:"last_fault_message,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Device) Reset() {
	*x = Device{}
	mi := &file_coffee_machine_v1_coffee_machine_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Device) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Device) ProtoMessage() {}

func (x *Device) ProtoReflect() protoreflect.Message {
	mi := &file_coffee_machine_v1_coffee_machine_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Device.ProtoReflect.Descriptor instead.
func (*Device) Descriptor() ([]byte, []int) {
	return file_coffee_machine_v1_coffee_machine_proto_rawDescGZIP(), []int{1}
}

func (x *Device) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Device) GetManufacturerId() string {
	if x != nil {
		return x.ManufacturerId
	}
	return ""
}

func (x *Device) GetSerialUnique() string {
	if x != nil {
		return x.SerialUnique
	}
	return ""
}

func (x *Device) GetDeviceName() string {
	if x != nil {
		return x.DeviceName
	}
	return ""
}

func (x *Device) GetStoreId() string {
	if x != nil {
		return x.StoreId
	}
	return ""
}

func (x *Device) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Device) GetVendorOnline() bool {
	if x != nil && x.VendorOnline != nil {
		return *x.VendorOnline
	}
	return false
}

func (x *Device) GetLastSyncedAtUnix() int64 {
	if x != nil && x.LastSyncedAtUnix != nil {
		return *x.LastSyncedAtUnix
	}
	return 0
}

func (x *Device) GetLastFaultCode() string {
	if x != nil {
		return x.LastFaultCode
	}
	return ""
}

func (x *Device) GetLastFaultMessage() string {
	if x != nil {
		return x.LastFaultMessage
	}
	return ""
}

type Drink struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ManufacturerId string                 `protobuf:"bytes,2,opt,name=manufacturer_id,json=manufacturerId,proto3" json:"manufacturer_id,omitempty"`
	// 厂商侧饮品 ID。空串表示后台手工新建、不参与同步判重的饮品。
	OriginId    string `protobuf:"bytes,3,opt,name=origin_id,json=originId,proto3" json:"origin_id,omitempty"`
	ProductNum  string `protobuf:"bytes,4,opt,name=product_num,json=productNum,proto3" json:"product_num,omitempty"`
	ProductName string `protobuf:"bytes,5,opt,name=product_name,json=productName,proto3" json:"product_name,omitempty"`
	// milk_coffee | black_coffee | other，空串表示未分类。
	DrinkType   string `protobuf:"bytes,6,opt,name=drink_type,json=drinkType,proto3" json:"drink_type,omitempty"`
	ProductDesc string `protobuf:"bytes,7,opt,name=product_desc,json=productDesc,proto3" json:"product_desc,omitempty"`
	ProductImg  string `protobuf:"bytes,8,opt,name=product_img,json=productImg,proto3" json:"product_img,omitempty"`
	// 三级价格，单位分。
	Price           int64 `protobuf:"varint,9,opt,name=price,proto3" json:"price,omitempty"`
	VipPrice        int64 `protobuf:"varint,10,opt,name=vip_price,json=vipPrice,proto3" json:"vip_price,omitempty"`
	PickupCodePrice int64 `protobuf:"varint,11,opt,name=pickup_code_price,json=pickupCodePrice,proto3" json:"pickup_code_price,omitempty"`
	// on_shelf=上架，off_shelf=下架。
	Status        string `protobuf:"bytes,12,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Drink) Reset() {
	*x = Drink{}
	mi := &file_coffee_machine_v1_coffee_machine_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Drink) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Drink) ProtoMessage() {}

func (x *Drink) ProtoReflect() protoreflect.Message {
	mi := &file_coffee_machine_v1_coffee_machine_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Drink.ProtoReflect.Descriptor instead.
func (*Drink) Descriptor() ([]byte, []int) {
	return file_coffee_machine_v1_coffee_machine_proto_rawDescGZIP(), []int{2}
}

func (x *Drink) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Drink) GetManufacturerId() string {
	if x != nil {
		return x.ManufacturerId
	}
	return ""
}

func (x *Drink) GetOriginId() string {
	if x != nil {
		return x.OriginId
	}
	return ""
}

func (x *Drink) GetProductNum() string {
	if x != nil {
		return x.ProductNum
	}
	return ""
}

func (x *Drink) GetProductName() string {
	if x != nil {
		return x.ProductName
	}
	return ""
}

func (x *Drink) GetDrinkType() string {
	if x != nil {
		return x.DrinkType
	}
	return ""
}

func (x *Drink) GetProductDesc() string {
	if x != nil {
		return x.ProductDesc
	}
	return ""
}

func (x *Drink) GetProductImg() string {
	if x != nil {
		return x.ProductImg
	}
	return ""
}

func (x *Drink) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Drink) GetVipPrice() int64 {
	if x != nil {
		return x.VipPrice
	}
	return 0
}

func (x *Drink) GetPickupCodePrice() int64 {
	if x != nil {
		return x.PickupCodePrice
	}
	return 0
}

func (x *Drink) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type DeviceDrink struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	DeviceId  string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	DrinkId   string                 `protobuf:"bytes,2,opt,name=drink_id,json=drinkId,proto3" json:"drink_id,omitempty"`
	Enabled   bool                   `protobuf:"varint,3,opt,name=enabled,proto3" json:"enabled,omitempty"`
	SortOrder int32                  `protobuf:"varint,4,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`
	// 每机覆盖价，单位分。optional 保住 NULL 与 0 的区别：0 是「这台机器上按 0 元
	// 卖」，未设置才是「沿用饮品目录价」。
	Price           *int64 `protobuf:"varint,5,opt,name=price,proto3,oneof" json:"price,omitempty"`
	VipPrice        *int64 `protobuf:"varint,6,opt,name=vip_price,json=vipPrice,proto3,oneof" json:"vip_price,omitempty"`
	PickupCodePrice *int64 `protobuf:"varint,7,opt,name=pickup_code_price,json=pickupCodePrice,proto3,oneof" json:"pickup_code_price,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DeviceDrink) Reset() {
	*x = DeviceDrink{}
	mi := &file_coffee_machine_v1_coffee_machine_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceDrink) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceDrink) ProtoMessage() {}

func (x *DeviceDrink) ProtoReflect() protoreflect.Message {
	mi := &file_coffee_machine_v1_coffee_machine_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceDrink.ProtoReflect.Descriptor instead.
func (*DeviceDrink) Descriptor() ([]byte, []int) {
	return file_coffee_machine_v1_coffee_machine_proto_rawDescGZIP(), []int{3}
}

func (x *DeviceDrink) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *DeviceDrink) GetDrinkId() string {
	if x != nil {
		return x.DrinkId
	}
	return ""
}

func (x *DeviceDrink) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *DeviceDrink) GetSortOrder() int32 {
	if x != nil {
		return x.SortOrder
	}
	return 0
}

func (x *DeviceDrink) GetPrice() int64 {
	if x != nil && x.Price != nil {
		return *x.Price
	}
	return 0
}

func (x *DeviceDrink) GetVipPrice() int64 {
	if x != nil && x.VipPrice != nil {
		return *x.VipPrice
	}
	return 0
}

func (x *DeviceDrink) GetPickupCodePrice() int64 {
	if x != nil && x.PickupCodePrice != nil {
		return *x.PickupCodePrice
	}
	return 0
}

type ManufacturerID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ManufacturerID) Reset() {
	*x = ManufacturerID{}
	mi := &file_coffee_machine_v1_coffee_machine_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManufacturerID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManufacturerID) ProtoMessage() {}

func (x *ManufacturerID) ProtoReflect() protoreflect.Message {
	mi := &file_coffee_machine_v1_coffee_machine_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManufacturerID.ProtoReflect.Descriptor instead.
func (*ManufacturerID) Descriptor() ([]byte, []int) {
	return file_coffee_machine_v1_coffee_machine_proto_rawDescGZIP(), []int{4}
}

func (x *ManufacturerID) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeviceID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceID) Reset() {
	*x = DeviceID{}
	mi := &file_coffee_machine_v1_coffee_machine_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceID) ProtoMessage() {}

func (x *DeviceID) ProtoReflect() protoreflect.Message {
	mi := &file_coffee_machine_v1_coffee_machine_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceID.ProtoReflect.Descriptor instead.
func (*DeviceID) Descriptor() ([]byte, []int) {
	return file_coffee_machine_v1_coffee_machine_proto_rawDescGZIP(), []int{5}
}

func (x *DeviceID) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DrinkID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DrinkID) Reset() {
	*x = DrinkID{}
	mi := &file_coffee_machine_v1_coffee_machine_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DrinkID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DrinkID) ProtoMessage() {}

func (x *DrinkID) ProtoReflect() protoreflect.Message {
	mi := &file_coffee_machine_v1_coffee_machine_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DrinkID.ProtoReflect.Descriptor instead.
func (*DrinkID) Descriptor() ([]byte, []int) {
	return file_coffee_machine_v1_coffee_machine_proto_rawDescGZIP(), []int{6}
}

func (x *DrinkID) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListManufacturersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListManufacturersRequest) Reset() {
	*x = ListManufacturersRequest{}
	mi := &file_coffee_machine_v1_coffee_machine_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListManufacturersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListManufacturersRequest) ProtoMessage() {}

func (x *ListManufacturersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_coffee_machine_v1_coffee_machine_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListManufacturersRequest.ProtoReflect.Descriptor instead.
func (*ListManufacturersRequest) Descriptor() ([]byte, []int) {
	return file_coffee_machine_v1_coffee_machine_proto_rawDescGZIP(), []int{7}
}

type ListManufacturersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Manufacturers []*Manufacturer        `protobuf:"bytes,1,rep,name=manufacturers,proto3" json:"manufacturers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListManufacturersResponse) Reset() {
	*x = ListManufacturersResponse{}
	mi := &file_coffee_machine_v1_coffee_machine_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListManufacturersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListManufacturersResponse) ProtoMessage() {}

func (x *ListManufacturersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_coffee_machine_v1_coffee_machine_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListManufacturersResponse.ProtoReflect.Descriptor instead.
func (*ListManufacturersResponse) Descriptor() ([]byte, []int) {
	return file_coffee_machine_v1_coffee_machine_proto_rawDescGZIP(), []int{8}
}

func (x *ListManufacturersResponse) GetManufacturers() []*Manufacturer {
	if x != nil {
		return x.Manufacturers
	}
	return nil
}

type ListDevicesRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ManufacturerId string                 `protobuf:"bytes,1,opt,name=manufacturer_id,json=manufacturerId,proto3" json:"manufacturer_id,omitempty"`
	Status         string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	// 按部署点位过滤，属于 merchant-service 的 ID。
	StoreId       string `protobuf:"bytes,3,opt,name=store_id,json=storeId,proto3" json:"store_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDevicesRequest) Reset() {
	*x = ListDevicesRequest{}
	mi := &file_coffee_machine_v1_coffee_machine_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDevicesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDevicesRequest) ProtoMessage() {}

func (x *ListDevicesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_coffee_machine_v1_coffee_machine_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDevicesRequest.ProtoReflect.Descriptor instead.
func (*ListDevicesRequest) Descriptor() ([]byte, []int) {
	return file_coffee_machine_v1_coffee_machine_proto_rawDescGZIP(), []int{9}
}

func (x *ListDevicesRequest) GetManufacturerId() string {
	if x != nil {
		return x.ManufacturerId
	}
	return ""
}

func (x *ListDevicesRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ListDevicesRequest) GetStoreId() string {
	if x != nil {
		return x.StoreId
	}
	return ""
}

type ListDevicesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Devices       []*Device              `protobuf:"bytes,1,rep,name=devices,proto3" json:"devices,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDevicesResponse) Reset() {
	*x = ListDevicesResponse{}
	mi := &file_coffee_machine_v1_coffee_machine_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDevicesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDevicesResponse) ProtoMessage() {}

func (x *ListDevicesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_coffee_machine_v1_coffee_machine_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDevicesResponse.ProtoReflect.Descriptor instead.
func (*ListDevicesResponse) Descriptor() ([]byte, []int) {
	return file_coffee_machine_v1_coffee_machine_proto_rawDescGZIP(), []int{10}
}

func (x *ListDevicesResponse) GetDevices() []*Device {
	if x != nil {
		return x.Devices
	}
	return nil
}

type ListDrinksRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ManufacturerId string                 `protobuf:"bytes,1,opt,name=manufacturer_id,json=manufacturerId,proto3" json:"manufacturer_id,omitempty"`
	Status         string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListDrinksRequest) Reset() {
	*x = ListDrinksRequest{}
	mi := &file_coffee_machine_v1_coffee_machine_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDrinksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDrinksRequest) ProtoMessage() {}

func (x *ListDrinksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_coffee_machine_v1_coffee_machine_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDrinksRequest.ProtoReflect.Descriptor instead.
func (*ListDrinksRequest) Descriptor() ([]byte, []int) {
	return file_coffee_machine_v1_coffee_machine_proto_rawDescGZIP(), []int{11}
}

func (x *ListDrinksRequest) GetManufacturerId() string {
	if x != nil {
		return x.ManufacturerId
	}
	return ""
}

func (x *ListDrinksRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ListDrinksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Drinks        []*Drink               `protobuf:"bytes,1,rep,name=drinks,proto3" json:"drinks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDrinksResponse) Reset() {
	*x = ListDrinksResponse{}
	mi := &file_coffee_machine_v1_coffee_machine_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDrinksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDrinksResponse) ProtoMessage() {}

func (x *ListDrinksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_coffee_machine_v1_coffee_machine_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDrinksResponse.ProtoReflect.Descriptor instead.
func (*ListDrinksResponse) Descriptor() ([]byte, []int) {
	return file_coffee_machine_v1_coffee_machine_proto_rawDescGZIP(), []int{12}
}

func (x *ListDrinksResponse) GetDrinks() []*Drink {
	if x != nil {
		return x.Drinks
	}
	return nil
}

type UpsertDeviceDrinkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Relation      *DeviceDrink           `protobuf:"bytes,1,opt,name=relation,proto3" json:"relation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertDeviceDrinkRequest) Reset() {
	*x = UpsertDeviceDrinkRequest{}
	mi := &file_coffee_machine_v1_coffee_machine_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertDeviceDrinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertDeviceDrinkRequest) ProtoMessage() {}

func (x *UpsertDeviceDrinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_coffee_machine_v1_coffee_machine_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertDeviceDrinkRequest.ProtoReflect.Descriptor instead.
func (*UpsertDeviceDrinkRequest) Descriptor() ([]byte, []int) {
	return file_coffee_machine_v1_coffee_machine_proto_rawDescGZIP(), []int{13}
}

func (x *UpsertDeviceDrinkRequest) GetRelation() *DeviceDrink {
	if x != nil {
		return x.Relation
	}
	return nil
}

type ListDeviceDrinksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDeviceDrinksRequest) Reset() {
	*x = ListDeviceDrinksRequest{}
	mi := &file_coffee_machine_v1_coffee_machine_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDeviceDrinksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDeviceDrinksRequest) ProtoMessage() {}

func (x *ListDeviceDrinksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_coffee_machine_v1_coffee_machine_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDeviceDrinksRequest.ProtoReflect.Descriptor instead.
func (*ListDeviceDrinksRequest) Descriptor() ([]byte, []int) {
	return file_coffee_machine_v1_coffee_machine_proto_rawDescGZIP(), []int{14}
}

func (x *ListDeviceDrinksRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

type ListDeviceDrinksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Relations     []*DeviceDrink         `protobuf:"bytes,1,rep,name=relations,proto3" json:"relations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDeviceDrinksResponse) Reset() {
	*x = ListDeviceDrinksResponse{}
	mi := &file_coffee_machine_v1_coffee_machine_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDeviceDrinksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDeviceDrinksResponse) ProtoMessage() {}

func (x *ListDeviceDrinksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_coffee_machine_v1_coffee_machine_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDeviceDrinksResponse.ProtoReflect.Descriptor instead.
func (*ListDeviceDrinksResponse) Descriptor() ([]byte, []int) {
	return file_coffee_machine_v1_coffee_machine_proto_rawDescGZIP(), []int{15}
}

func (x *ListDeviceDrinksResponse) GetRelations() []*DeviceDrink {
	if x != nil {
		return x.Relations
	}
	return nil
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deleted       bool                   `protobuf:"varint,1,opt,name=deleted,proto3" json:"deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_coffee_machine_v1_coffee_machine_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_coffee_machine_v1_coffee_machine_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_coffee_machine_v1_coffee_machine_proto_rawDescGZIP(), []int{16}
}

func (x *DeleteResponse) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

var File_coffee_machine_v1_coffee_machine_proto protoreflect.FileDescriptor

const file_coffee_machine_v1_coffee_machine_proto_rawDesc = "" +
	"\n" +
	"&coffee_machine/v1/coffee_machine.proto\x12\x17panda.coffee_machine.v1\"\xa6\x01\n" +
	"\fManufacturer\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12!\n" +
	"\fcontact_name\x18\x04 \x01(\tR\vcontactName\x12#\n" +
	"\rcontact_phone\x18\x05 \x01(\tR\fcontactPhone\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\"\x98\x03\n" +
	"\x06Device\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12'\n" +
	"\x0fmanufacturer_id\x18\x02 \x01(\tR\x0emanufacturerId\x12#\n" +
	"\rserial_unique\x18\x03 \x01(\tR\fserialUnique\x12\x1f\n" +
	"\vdevice_name\x18\x04 \x01(\tR\n" +
	"deviceName\x12\x19\n" +
	"\bstore_id\x18\x05 \x01(\tR\astoreId\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12(\n" +
	"\rvendor_online\x18\a \x01(\bH\x00R\fvendorOnline\x88\x01\x01\x122\n" +
	"\x13last_synced_at_unix\x18\b \x01(\x03H\x01R\x10lastSyncedAtUnix\x88\x01\x01\x12&\n" +
	"\x0flast_fault_code\x18\t \x01(\tR\rlastFaultCode\x12,\n" +
	"\x12last_fault_message\x18\n" +
	" \x01(\tR\x10lastFaultMessageB\x10\n" +
	"\x0e_vendor_onlineB\x16\n" +
	"\x14_last_synced_at_unix\"\xfb\x02\n" +
	"\x05Drink\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12'\n" +
	"\x0fmanufacturer_id\x18\x02 \x01(\tR\x0emanufacturerId\x12\x1b\n" +
	"\torigin_id\x18\x03 \x01(\tR\boriginId\x12\x1f\n" +
	"\vproduct_num\x18\x04 \x01(\tR\n" +
	"productNum\x12!\n" +
	"\fproduct_name\x18\x05 \x01(\tR\vproductName\x12\x1d\n" +
	"\n" +
	"drink_type\x18\x06 \x01(\tR\tdrinkType\x12!\n" +
	"\fproduct_desc\x18\a \x01(\tR\vproductDesc\x12\x1f\n" +
	"\vproduct_img\x18\b \x01(\tR\n" +
	"productImg\x12\x14\n" +
	"\x05price\x18\t \x01(\x03R\x05price\x12\x1b\n" +
	"\tvip_price\x18\n" +
	" \x01(\x03R\bvipPrice\x12*\n" +
	"\x11pickup_code_price\x18\v \x01(\x03R\x0fpickupCodePrice\x12\x16\n" +
	"\x06status\x18\f \x01(\tR\x06status\"\x9a\x02\n" +
	"\vDeviceDrink\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x19\n" +
	"\bdrink_id\x18\x02 \x01(\tR\adrinkId\x12\x18\n" +
	"\aenabled\x18\x03 \x01(\bR\aenabled\x12\x1d\n" +
	"\n" +
	"sort_order\x18\x04 \x01(\x05R\tsortOrder\x12\x19\n" +
	"\x05price\x18\x05 \x01(\x03H\x00R\x05price\x88\x01\x01\x12 \n" +
	"\tvip_price\x18\x06 \x01(\x03H\x01R\bvipPrice\x88\x01\x01\x12/\n" +
	"\x11pickup_code_price\x18\a \x01(\x03H\x02R\x0fpickupCodePrice\x88\x01\x01B\b\n" +
	"\x06_priceB\f\n" +
	"\n" +
	"_vip_priceB\x14\n" +
	"\x12_pickup_code_price\" \n" +
	"\x0eManufacturerID\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x1a\n" +
	"\bDeviceID\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x19\n" +
	"\aDrinkID\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x1a\n" +
	"\x18ListManufacturersRequest\"h\n" +
	"\x19ListManufacturersResponse\x12K\n" +
	"\rmanufacturers\x18\x01 \x03(\v2%.panda.coffee_machine.v1.ManufacturerR\rmanufacturers\"p\n" +
	"\x12ListDevicesRequest\x12'\n" +
	"\x0fmanufacturer_id\x18\x01 \x01(\tR\x0emanufacturerId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x19\n" +
	"\bstore_id\x18\x03 \x01(\tR\astoreId\"P\n" +
	"\x13ListDevicesResponse\x129\n" +
	"\adevices\x18\x01 \x03(\v2\x1f.panda.coffee_machine.v1.DeviceR\adevices\"T\n" +
	"\x11ListDrinksRequest\x12'\n" +
	"\x0fmanufacturer_id\x18\x01 \x01(\tR\x0emanufacturerId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"L\n" +
	"\x12ListDrinksResponse\x126\n" +
	"\x06drinks\x18\x01 \x03(\v2\x1e.panda.coffee_machine.v1.DrinkR\x06drinks\"\\\n" +
	"\x18UpsertDeviceDrinkRequest\x12@\n" +
	"\brelation\x18\x01 \x01(\v2$.panda.coffee_machine.v1.DeviceDrinkR\brelation\"6\n" +
	"\x17ListDeviceDrinksRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\"^\n" +
	"\x18ListDeviceDrinksResponse\x12B\n" +
	"\trelations\x18\x01 \x03(\v2$.panda.coffee_machine.v1.DeviceDrinkR\trelations\"*\n" +
	"\x0eDeleteResponse\x12\x18\n" +
	"\adeleted\x18\x01 \x01(\bR\adeleted2\xb9\a\n" +
	"\x14CoffeeMachineService\x12O\n" +
	"\tGetDevice\x12!.panda.coffee_machine.v1.DeviceID\x1a\x1f.panda.coffee_machine.v1.Device\x12z\n" +
	"\x11ListManufacturers\x121.panda.coffee_machine.v1.ListManufacturersRequest\x1a2.panda.coffee_machine.v1.ListManufacturersResponse\x12h\n" +
	"\vListDevices\x12+.panda.coffee_machine.v1.ListDevicesRequest\x1a,.panda.coffee_machine.v1.ListDevicesResponse\x12e\n" +
	"\n" +
	"ListDrinks\x12*.panda.coffee_machine.v1.ListDrinksRequest\x1a+.panda.coffee_machine.v1.ListDrinksResponse\x12l\n" +
	"\x11UpsertDeviceDrink\x121.panda.coffee_machine.v1.UpsertDeviceDrinkRequest\x1a$.panda.coffee_machine.v1.DeviceDrink\x12w\n" +
	"\x10ListDeviceDrinks\x120.panda.coffee_machine.v1.ListDeviceDrinksRequest\x1a1.panda.coffee_machine.v1.ListDeviceDrinksResponse\x12f\n" +
	"\x12DeleteManufacturer\x12'.panda.coffee_machine.v1.ManufacturerID\x1a'.panda.coffee_machine.v1.DeleteResponse\x12Z\n" +
	"\fDeleteDevice\x12!.panda.coffee_machine.v1.DeviceID\x1a'.panda.coffee_machine.v1.DeleteResponse\x12X\n" +
	"\vDeleteDrink\x12 .panda.coffee_machine.v1.DrinkID\x1a'.panda.coffee_machine.v1.DeleteResponseBAZ?github.com/panda-dev/panda-v2/contracts/proto/coffee_machine/v1b\x06proto3"

var (
	file_coffee_machine_v1_coffee_machine_proto_rawDescOnce sync.Once
	file_coffee_machine_v1_coffee_machine_proto_rawDescData []byte
)

func file_coffee_machine_v1_coffee_machine_proto_rawDescGZIP() []byte {
	file_coffee_machine_v1_coffee_machine_proto_rawDescOnce.Do(func() {
		file_coffee_machine_v1_coffee_machine_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_coffee_machine_v1_coffee_machine_proto_rawDesc), len(file_coffee_machine_v1_coffee_machine_proto_rawDesc)))
	})
	return file_coffee_machine_v1_coffee_machine_proto_rawDescData
}

var file_coffee_machine_v1_coffee_machine_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_coffee_machine_v1_coffee_machine_proto_goTypes = []any{
	(*Manufacturer)(nil),              // 0: panda.coffee_machine.v1.Manufacturer
	(*Device)(nil),                    // 1: panda.coffee_machine.v1.Device
	(*Drink)(nil),                     // 2: panda.coffee_machine.v1.Drink
	(*DeviceDrink)(nil),               // 3: panda.coffee_machine.v1.DeviceDrink
	(*ManufacturerID)(nil),            // 4: panda.coffee_machine.v1.ManufacturerID
	(*DeviceID)(nil),                  // 5: panda.coffee_machine.v1.DeviceID
	(*DrinkID)(nil),                   // 6: panda.coffee_machine.v1.DrinkID
	(*ListManufacturersRequest)(nil),  // 7: panda.coffee_machine.v1.ListManufacturersRequest
	(*ListManufacturersResponse)(nil), // 8: panda.coffee_machine.v1.ListManufacturersResponse
	(*ListDevicesRequest)(nil),        // 9: panda.coffee_machine.v1.ListDevicesRequest
	(*ListDevicesResponse)(nil),       // 10: panda.coffee_machine.v1.ListDevicesResponse
	(*ListDrinksRequest)(nil),         // 11: panda.coffee_machine.v1.ListDrinksRequest
	(*ListDrinksResponse)(nil),        // 12: panda.coffee_machine.v1.ListDrinksResponse
	(*UpsertDeviceDrinkRequest)(nil),  // 13: panda.coffee_machine.v1.UpsertDeviceDrinkRequest
	(*ListDeviceDrinksRequest)(nil),   // 14: panda.coffee_machine.v1.ListDeviceDrinksRequest
	(*ListDeviceDrinksResponse)(nil),  // 15: panda.coffee_machine.v1.ListDeviceDrinksResponse
	(*DeleteResponse)(nil),            // 16: panda.coffee_machine.v1.DeleteResponse
}
var file_coffee_machine_v1_coffee_machine_proto_depIdxs = []int32{
	0,  // 0: panda.coffee_machine.v1.ListManufacturersResponse.manufacturers:type_name -> panda.coffee_machine.v1.Manufacturer
	1,  // 1: panda.coffee_machine.v1.ListDevicesResponse.devices:type_name -> panda.coffee_machine.v1.Device
	2,  // 2: panda.coffee_machine.v1.ListDrinksResponse.drinks:type_name -> panda.coffee_machine.v1.Drink
	3,  // 3: panda.coffee_machine.v1.UpsertDeviceDrinkRequest.relation:type_name -> panda.coffee_machine.v1.DeviceDrink
	3,  // 4: panda.coffee_machine.v1.ListDeviceDrinksResponse.relations:type_name -> panda.coffee_machine.v1.DeviceDrink
	5,  // 5: panda.coffee_machine.v1.CoffeeMachineService.GetDevice:input_type -> panda.coffee_machine.v1.DeviceID
	7,  // 6: panda.coffee_machine.v1.CoffeeMachineService.ListManufacturers:input_type -> panda.coffee_machine.v1.ListManufacturersRequest
	9,  // 7: panda.coffee_machine.v1.CoffeeMachineService.ListDevices:input_type -> panda.coffee_machine.v1.ListDevicesRequest
	11, // 8: panda.coffee_machine.v1.CoffeeMachineService.ListDrinks:input_type -> panda.coffee_machine.v1.ListDrinksRequest
	13, // 9: panda.coffee_machine.v1.CoffeeMachineService.UpsertDeviceDrink:input_type -> panda.coffee_machine.v1.UpsertDeviceDrinkRequest
	14, // 10: panda.coffee_machine.v1.CoffeeMachineService.ListDeviceDrinks:input_type -> panda.coffee_machine.v1.ListDeviceDrinksRequest
	4,  // 11: panda.coffee_machine.v1.CoffeeMachineService.DeleteManufacturer:input_type -> panda.coffee_machine.v1.ManufacturerID
	5,  // 12: panda.coffee_machine.v1.CoffeeMachineService.DeleteDevice:input_type -> panda.coffee_machine.v1.DeviceID
	6,  // 13: panda.coffee_machine.v1.CoffeeMachineService.DeleteDrink:input_type -> panda.coffee_machine.v1.DrinkID
	1,  // 14: panda.coffee_machine.v1.CoffeeMachineService.GetDevice:output_type -> panda.coffee_machine.v1.Device
	8,  // 15: panda.coffee_machine.v1.CoffeeMachineService.ListManufacturers:output_type -> panda.coffee_machine.v1.ListManufacturersResponse
	10, // 16: panda.coffee_machine.v1.CoffeeMachineService.ListDevices:output_type -> panda.coffee_machine.v1.ListDevicesResponse
	12, // 17: panda.coffee_machine.v1.CoffeeMachineService.ListDrinks:output_type -> panda.coffee_machine.v1.ListDrinksResponse
	3,  // 18: panda.coffee_machine.v1.CoffeeMachineService.UpsertDeviceDrink:output_type -> panda.coffee_machine.v1.DeviceDrink
	15, // 19: panda.coffee_machine.v1.CoffeeMachineService.ListDeviceDrinks:output_type -> panda.coffee_machine.v1.ListDeviceDrinksResponse
	16, // 20: panda.coffee_machine.v1.CoffeeMachineService.DeleteManufacturer:output_type -> panda.coffee_machine.v1.DeleteResponse
	16, // 21: panda.coffee_machine.v1.CoffeeMachineService.DeleteDevice:output_type -> panda.coffee_machine.v1.DeleteResponse
	16, // 22: panda.coffee_machine.v1.CoffeeMachineService.DeleteDrink:output_type -> panda.coffee_machine.v1.DeleteResponse
	14, // [14:23] is the sub-list for method output_type
	5,  // [5:14] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_coffee_machine_v1_coffee_machine_proto_init() }
func file_coffee_machine_v1_coffee_machine_proto_init() {
	if File_coffee_machine_v1_coffee_machine_proto != nil {
		return
	}
	file_coffee_machine_v1_coffee_machine_proto_msgTypes[1].OneofWrappers = []any{}
	file_coffee_machine_v1_coffee_machine_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_coffee_machine_v1_coffee_machine_proto_rawDesc), len(file_coffee_machine_v1_coffee_machine_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_coffee_machine_v1_coffee_machine_proto_goTypes,
		DependencyIndexes: file_coffee_machine_v1_coffee_machine_proto_depIdxs,
		MessageInfos:      file_coffee_machine_v1_coffee_machine_proto_msgTypes,
	}.Build()
	File_coffee_machine_v1_coffee_machine_proto = out.File
	file_coffee_machine_v1_coffee_machine_proto_goTypes = nil
	file_coffee_machine_v1_coffee_machine_proto_depIdxs = nil
}
