// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: coffee_machine/v1/coffee_machine.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CoffeeMachineService_ListManufacturers_FullMethodName  = "/coffee_machine.v1.CoffeeMachineService/ListManufacturers"
	CoffeeMachineService_ListDevices_FullMethodName        = "/coffee_machine.v1.CoffeeMachineService/ListDevices"
	CoffeeMachineService_ListDrinks_FullMethodName         = "/coffee_machine.v1.CoffeeMachineService/ListDrinks"
	CoffeeMachineService_UpsertDeviceDrink_FullMethodName  = "/coffee_machine.v1.CoffeeMachineService/UpsertDeviceDrink"
	CoffeeMachineService_ListDeviceDrinks_FullMethodName   = "/coffee_machine.v1.CoffeeMachineService/ListDeviceDrinks"
	CoffeeMachineService_DeleteManufacturer_FullMethodName = "/coffee_machine.v1.CoffeeMachineService/DeleteManufacturer"
	CoffeeMachineService_DeleteDevice_FullMethodName       = "/coffee_machine.v1.CoffeeMachineService/DeleteDevice"
	CoffeeMachineService_DeleteDrink_FullMethodName        = "/coffee_machine.v1.CoffeeMachineService/DeleteDrink"
)

// CoffeeMachineServiceClient is the client API for CoffeeMachineService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CoffeeMachineServiceClient interface {
	ListManufacturers(ctx context.Context, in *ListManufacturersRequest, opts ...grpc.CallOption) (*ListManufacturersResponse, error)
	ListDevices(ctx context.Context, in *ListDevicesRequest, opts ...grpc.CallOption) (*ListDevicesResponse, error)
	ListDrinks(ctx context.Context, in *ListDrinksRequest, opts ...grpc.CallOption) (*ListDrinksResponse, error)
	UpsertDeviceDrink(ctx context.Context, in *UpsertDeviceDrinkRequest, opts ...grpc.CallOption) (*DeviceDrink, error)
	ListDeviceDrinks(ctx context.Context, in *ListDeviceDrinksRequest, opts ...grpc.CallOption) (*ListDeviceDrinksResponse, error)
	DeleteManufacturer(ctx context.Context, in *ManufacturerID, opts ...grpc.CallOption) (*DeleteResponse, error)
	DeleteDevice(ctx context.Context, in *DeviceID, opts ...grpc.CallOption) (*DeleteResponse, error)
	DeleteDrink(ctx context.Context, in *DrinkID, opts ...grpc.CallOption) (*DeleteResponse, error)
}

type coffeeMachineServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCoffeeMachineServiceClient(cc grpc.ClientConnInterface) CoffeeMachineServiceClient {
	return &coffeeMachineServiceClient{cc}
}

func (c *coffeeMachineServiceClient) ListManufacturers(ctx context.Context, in *ListManufacturersRequest, opts ...grpc.CallOption) (*ListManufacturersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListManufacturersResponse)
	err := c.cc.Invoke(ctx, CoffeeMachineService_ListManufacturers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coffeeMachineServiceClient) ListDevices(ctx context.Context, in *ListDevicesRequest, opts ...grpc.CallOption) (*ListDevicesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDevicesResponse)
	err := c.cc.Invoke(ctx, CoffeeMachineService_ListDevices_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coffeeMachineServiceClient) ListDrinks(ctx context.Context, in *ListDrinksRequest, opts ...grpc.CallOption) (*ListDrinksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDrinksResponse)
	err := c.cc.Invoke(ctx, CoffeeMachineService_ListDrinks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coffeeMachineServiceClient) UpsertDeviceDrink(ctx context.Context, in *UpsertDeviceDrinkRequest, opts ...grpc.CallOption) (*DeviceDrink, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeviceDrink)
	err := c.cc.Invoke(ctx, CoffeeMachineService_UpsertDeviceDrink_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coffeeMachineServiceClient) ListDeviceDrinks(ctx context.Context, in *ListDeviceDrinksRequest, opts ...grpc.CallOption) (*ListDeviceDrinksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDeviceDrinksResponse)
	err := c.cc.Invoke(ctx, CoffeeMachineService_ListDeviceDrinks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coffeeMachineServiceClient) DeleteManufacturer(ctx context.Context, in *ManufacturerID, opts ...grpc.CallOption) (*DeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, CoffeeMachineService_DeleteManufacturer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coffeeMachineServiceClient) DeleteDevice(ctx context.Context, in *DeviceID, opts ...grpc.CallOption) (*DeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, CoffeeMachineService_DeleteDevice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coffeeMachineServiceClient) DeleteDrink(ctx context.Context, in *DrinkID, opts ...grpc.CallOption) (*DeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, CoffeeMachineService_DeleteDrink_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CoffeeMachineServiceServer is the server API for CoffeeMachineService service.
// All implementations must embed UnimplementedCoffeeMachineServiceServer
// for forward compatibility.
type CoffeeMachineServiceServer interface {
	ListManufacturers(context.Context, *ListManufacturersRequest) (*ListManufacturersResponse, error)
	ListDevices(context.Context, *ListDevicesRequest) (*ListDevicesResponse, error)
	ListDrinks(context.Context, *ListDrinksRequest) (*ListDrinksResponse, error)
	UpsertDeviceDrink(context.Context, *UpsertDeviceDrinkRequest) (*DeviceDrink, error)
	ListDeviceDrinks(context.Context, *ListDeviceDrinksRequest) (*ListDeviceDrinksResponse, error)
	DeleteManufacturer(context.Context, *ManufacturerID) (*DeleteResponse, error)
	DeleteDevice(context.Context, *DeviceID) (*DeleteResponse, error)
	DeleteDrink(context.Context, *DrinkID) (*DeleteResponse, error)
	mustEmbedUnimplementedCoffeeMachineServiceServer()
}

// UnimplementedCoffeeMachineServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCoffeeMachineServiceServer struct{}

func (UnimplementedCoffeeMachineServiceServer) ListManufacturers(context.Context, *ListManufacturersRequest) (*ListManufacturersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListManufacturers not implemented")
}
func (UnimplementedCoffeeMachineServiceServer) ListDevices(context.Context, *ListDevicesRequest) (*ListDevicesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListDevices not implemented")
}
func (UnimplementedCoffeeMachineServiceServer) ListDrinks(context.Context, *ListDrinksRequest) (*ListDrinksResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListDrinks not implemented")
}
func (UnimplementedCoffeeMachineServiceServer) UpsertDeviceDrink(context.Context, *UpsertDeviceDrinkRequest) (*DeviceDrink, error) {
	return nil, status.Error(codes.Unimplemented, "method UpsertDeviceDrink not implemented")
}
func (UnimplementedCoffeeMachineServiceServer) ListDeviceDrinks(context.Context, *ListDeviceDrinksRequest) (*ListDeviceDrinksResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListDeviceDrinks not implemented")
}
func (UnimplementedCoffeeMachineServiceServer) DeleteManufacturer(context.Context, *ManufacturerID) (*DeleteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteManufacturer not implemented")
}
func (UnimplementedCoffeeMachineServiceServer) DeleteDevice(context.Context, *DeviceID) (*DeleteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteDevice not implemented")
}
func (UnimplementedCoffeeMachineServiceServer) DeleteDrink(context.Context, *DrinkID) (*DeleteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteDrink not implemented")
}
func (UnimplementedCoffeeMachineServiceServer) mustEmbedUnimplementedCoffeeMachineServiceServer() {}
func (UnimplementedCoffeeMachineServiceServer) testEmbeddedByValue()                              {}

// UnsafeCoffeeMachineServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CoffeeMachineServiceServer will
// result in compilation errors.
type UnsafeCoffeeMachineServiceServer interface {
	mustEmbedUnimplementedCoffeeMachineServiceServer()
}

func RegisterCoffeeMachineServiceServer(s grpc.ServiceRegistrar, srv CoffeeMachineServiceServer) {
	// If the following call panics, it indicates UnimplementedCoffeeMachineServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CoffeeMachineService_ServiceDesc, srv)
}

func _CoffeeMachineService_ListManufacturers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListManufacturersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoffeeMachineServiceServer).ListManufacturers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoffeeMachineService_ListManufacturers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoffeeMachineServiceServer).ListManufacturers(ctx, req.(*ListManufacturersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoffeeMachineService_ListDevices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDevicesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoffeeMachineServiceServer).ListDevices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoffeeMachineService_ListDevices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoffeeMachineServiceServer).ListDevices(ctx, req.(*ListDevicesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoffeeMachineService_ListDrinks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDrinksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoffeeMachineServiceServer).ListDrinks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoffeeMachineService_ListDrinks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoffeeMachineServiceServer).ListDrinks(ctx, req.(*ListDrinksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoffeeMachineService_UpsertDeviceDrink_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertDeviceDrinkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoffeeMachineServiceServer).UpsertDeviceDrink(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoffeeMachineService_UpsertDeviceDrink_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoffeeMachineServiceServer).UpsertDeviceDrink(ctx, req.(*UpsertDeviceDrinkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoffeeMachineService_ListDeviceDrinks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDeviceDrinksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoffeeMachineServiceServer).ListDeviceDrinks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoffeeMachineService_ListDeviceDrinks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoffeeMachineServiceServer).ListDeviceDrinks(ctx, req.(*ListDeviceDrinksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoffeeMachineService_DeleteManufacturer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ManufacturerID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoffeeMachineServiceServer).DeleteManufacturer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoffeeMachineService_DeleteManufacturer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoffeeMachineServiceServer).DeleteManufacturer(ctx, req.(*ManufacturerID))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoffeeMachineService_DeleteDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeviceID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoffeeMachineServiceServer).DeleteDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoffeeMachineService_DeleteDevice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoffeeMachineServiceServer).DeleteDevice(ctx, req.(*DeviceID))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoffeeMachineService_DeleteDrink_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DrinkID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoffeeMachineServiceServer).DeleteDrink(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoffeeMachineService_DeleteDrink_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoffeeMachineServiceServer).DeleteDrink(ctx, req.(*DrinkID))
	}
	return interceptor(ctx, in, info, handler)
}

// CoffeeMachineService_ServiceDesc is the grpc.ServiceDesc for CoffeeMachineService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CoffeeMachineService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "coffee_machine.v1.CoffeeMachineService",
	HandlerType: (*CoffeeMachineServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListManufacturers",
			Handler:    _CoffeeMachineService_ListManufacturers_Handler,
		},
		{
			MethodName: "ListDevices",
			Handler:    _CoffeeMachineService_ListDevices_Handler,
		},
		{
			MethodName: "ListDrinks",
			Handler:    _CoffeeMachineService_ListDrinks_Handler,
		},
		{
			MethodName: "UpsertDeviceDrink",
			Handler:    _CoffeeMachineService_UpsertDeviceDrink_Handler,
		},
		{
			MethodName: "ListDeviceDrinks",
			Handler:    _CoffeeMachineService_ListDeviceDrinks_Handler,
		},
		{
			MethodName: "DeleteManufacturer",
			Handler:    _CoffeeMachineService_DeleteManufacturer_Handler,
		},
		{
			MethodName: "DeleteDevice",
			Handler:    _CoffeeMachineService_DeleteDevice_Handler,
		},
		{
			MethodName: "DeleteDrink",
			Handler:    _CoffeeMachineService_DeleteDrink_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "coffee_machine/v1/coffee_machine.proto",
}
