// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: coffee_machine/v1/coffee_machine.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Manufacturer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ContactName   string                 `protobuf:"bytes,3,opt,name=contact_name,json=contactName,proto3" json:"contact_name,omitempty"`
	ContactPhone  string                 `protobuf:"bytes,4,opt,name=contact_phone,json=contactPhone,proto3" json:"contact_phone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Manufacturer) Reset() {
	*x = Manufacturer{}
	mi := &file_coffee_machine_v1_coffee_machine_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Manufacturer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Manufacturer) ProtoMessage() {}

func (x *Manufacturer) ProtoReflect() protoreflect.Message {
	mi := &file_coffee_machine_v1_coffee_machine_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Manufacturer.ProtoReflect.Descriptor instead.
func (*Manufacturer) Descriptor() ([]byte, []int) {
	return file_coffee_machine_v1_coffee_machine_proto_rawDescGZIP(), []int{0}
}

func (x *Manufacturer) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Manufacturer) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Manufacturer) GetContactName() string {
	if x != nil {
		return x.ContactName
	}
	return ""
}

func (x *Manufacturer) GetContactPhone() string {
	if x != nil {
		return x.ContactPhone
	}
	return ""
}

type Device struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ManufacturerId string                 `protobuf:"bytes,2,opt,name=manufacturer_id,json=manufacturerId,proto3" json:"manufacturer_id,omitempty"`
	Name           string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	SerialNumber   string                 `protobuf:"bytes,4,opt,name=serial_number,json=serialNumber,proto3" json:"serial_number,omitempty"`
	Location       string                 `protobuf:"bytes,5,opt,name=location,proto3" json:"location,omitempty"`
	Status         string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Device) Reset() {
	*x = Device{}
	mi := &file_coffee_machine_v1_coffee_machine_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Device) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Device) ProtoMessage() {}

func (x *Device) ProtoReflect() protoreflect.Message {
	mi := &file_coffee_machine_v1_coffee_machine_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Device.ProtoReflect.Descriptor instead.
func (*Device) Descriptor() ([]byte, []int) {
	return file_coffee_machine_v1_coffee_machine_proto_rawDescGZIP(), []int{1}
}

func (x *Device) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Device) GetManufacturerId() string {
	if x != nil {
		return x.ManufacturerId
	}
	return ""
}

func (x *Device) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Device) GetSerialNumber() string {
	if x != nil {
		return x.SerialNumber
	}
	return ""
}

func (x *Device) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *Device) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type Drink struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Price         int64                  `protobuf:"varint,4,opt,name=price,proto3" json:"price,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Drink) Reset() {
	*x = Drink{}
	mi := &file_coffee_machine_v1_coffee_machine_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Drink) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Drink) ProtoMessage() {}

func (x *Drink) ProtoReflect() protoreflect.Message {
	mi := &file_coffee_machine_v1_coffee_machine_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Drink.ProtoReflect.Descriptor instead.
func (*Drink) Descriptor() ([]byte, []int) {
	return file_coffee_machine_v1_coffee_machine_proto_rawDescGZIP(), []int{2}
}

func (x *Drink) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Drink) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Drink) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Drink) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Drink) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type DeviceDrink struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	DrinkId       string                 `protobuf:"bytes,2,opt,name=drink_id,json=drinkId,proto3" json:"drink_id,omitempty"`
	Enabled       bool                   `protobuf:"varint,3,opt,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceDrink) Reset() {
	*x = DeviceDrink{}
	mi := &file_coffee_machine_v1_coffee_machine_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceDrink) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceDrink) ProtoMessage() {}

func (x *DeviceDrink) ProtoReflect() protoreflect.Message {
	mi := &file_coffee_machine_v1_coffee_machine_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceDrink.ProtoReflect.Descriptor instead.
func (*DeviceDrink) Descriptor() ([]byte, []int) {
	return file_coffee_machine_v1_coffee_machine_proto_rawDescGZIP(), []int{3}
}

func (x *DeviceDrink) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *DeviceDrink) GetDrinkId() string {
	if x != nil {
		return x.DrinkId
	}
	return ""
}

func (x *DeviceDrink) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

type ManufacturerID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ManufacturerID) Reset() {
	*x = ManufacturerID{}
	mi := &file_coffee_machine_v1_coffee_machine_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManufacturerID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManufacturerID) ProtoMessage() {}

func (x *ManufacturerID) ProtoReflect() protoreflect.Message {
	mi := &file_coffee_machine_v1_coffee_machine_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManufacturerID.ProtoReflect.Descriptor instead.
func (*ManufacturerID) Descriptor() ([]byte, []int) {
	return file_coffee_machine_v1_coffee_machine_proto_rawDescGZIP(), []int{4}
}

func (x *ManufacturerID) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeviceID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceID) Reset() {
	*x = DeviceID{}
	mi := &file_coffee_machine_v1_coffee_machine_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceID) ProtoMessage() {}

func (x *DeviceID) ProtoReflect() protoreflect.Message {
	mi := &file_coffee_machine_v1_coffee_machine_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceID.ProtoReflect.Descriptor instead.
func (*DeviceID) Descriptor() ([]byte, []int) {
	return file_coffee_machine_v1_coffee_machine_proto_rawDescGZIP(), []int{5}
}

func (x *DeviceID) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DrinkID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DrinkID) Reset() {
	*x = DrinkID{}
	mi := &file_coffee_machine_v1_coffee_machine_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DrinkID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DrinkID) ProtoMessage() {}

func (x *DrinkID) ProtoReflect() protoreflect.Message {
	mi := &file_coffee_machine_v1_coffee_machine_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DrinkID.ProtoReflect.Descriptor instead.
func (*DrinkID) Descriptor() ([]byte, []int) {
	return file_coffee_machine_v1_coffee_machine_proto_rawDescGZIP(), []int{6}
}

func (x *DrinkID) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListManufacturersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListManufacturersRequest) Reset() {
	*x = ListManufacturersRequest{}
	mi := &file_coffee_machine_v1_coffee_machine_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListManufacturersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListManufacturersRequest) ProtoMessage() {}

func (x *ListManufacturersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_coffee_machine_v1_coffee_machine_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListManufacturersRequest.ProtoReflect.Descriptor instead.
func (*ListManufacturersRequest) Descriptor() ([]byte, []int) {
	return file_coffee_machine_v1_coffee_machine_proto_rawDescGZIP(), []int{7}
}

type ListManufacturersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Manufacturers []*Manufacturer        `protobuf:"bytes,1,rep,name=manufacturers,proto3" json:"manufacturers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListManufacturersResponse) Reset() {
	*x = ListManufacturersResponse{}
	mi := &file_coffee_machine_v1_coffee_machine_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListManufacturersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListManufacturersResponse) ProtoMessage() {}

func (x *ListManufacturersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_coffee_machine_v1_coffee_machine_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListManufacturersResponse.ProtoReflect.Descriptor instead.
func (*ListManufacturersResponse) Descriptor() ([]byte, []int) {
	return file_coffee_machine_v1_coffee_machine_proto_rawDescGZIP(), []int{8}
}

func (x *ListManufacturersResponse) GetManufacturers() []*Manufacturer {
	if x != nil {
		return x.Manufacturers
	}
	return nil
}

type ListDevicesRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ManufacturerId string                 `protobuf:"bytes,1,opt,name=manufacturer_id,json=manufacturerId,proto3" json:"manufacturer_id,omitempty"`
	Status         string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListDevicesRequest) Reset() {
	*x = ListDevicesRequest{}
	mi := &file_coffee_machine_v1_coffee_machine_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDevicesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDevicesRequest) ProtoMessage() {}

func (x *ListDevicesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_coffee_machine_v1_coffee_machine_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDevicesRequest.ProtoReflect.Descriptor instead.
func (*ListDevicesRequest) Descriptor() ([]byte, []int) {
	return file_coffee_machine_v1_coffee_machine_proto_rawDescGZIP(), []int{9}
}

func (x *ListDevicesRequest) GetManufacturerId() string {
	if x != nil {
		return x.ManufacturerId
	}
	return ""
}

func (x *ListDevicesRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ListDevicesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Devices       []*Device              `protobuf:"bytes,1,rep,name=devices,proto3" json:"devices,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDevicesResponse) Reset() {
	*x = ListDevicesResponse{}
	mi := &file_coffee_machine_v1_coffee_machine_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDevicesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDevicesResponse) ProtoMessage() {}

func (x *ListDevicesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_coffee_machine_v1_coffee_machine_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDevicesResponse.ProtoReflect.Descriptor instead.
func (*ListDevicesResponse) Descriptor() ([]byte, []int) {
	return file_coffee_machine_v1_coffee_machine_proto_rawDescGZIP(), []int{10}
}

func (x *ListDevicesResponse) GetDevices() []*Device {
	if x != nil {
		return x.Devices
	}
	return nil
}

type ListDrinksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDrinksRequest) Reset() {
	*x = ListDrinksRequest{}
	mi := &file_coffee_machine_v1_coffee_machine_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDrinksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDrinksRequest) ProtoMessage() {}

func (x *ListDrinksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_coffee_machine_v1_coffee_machine_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDrinksRequest.ProtoReflect.Descriptor instead.
func (*ListDrinksRequest) Descriptor() ([]byte, []int) {
	return file_coffee_machine_v1_coffee_machine_proto_rawDescGZIP(), []int{11}
}

func (x *ListDrinksRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ListDrinksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Drinks        []*Drink               `protobuf:"bytes,1,rep,name=drinks,proto3" json:"drinks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDrinksResponse) Reset() {
	*x = ListDrinksResponse{}
	mi := &file_coffee_machine_v1_coffee_machine_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDrinksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDrinksResponse) ProtoMessage() {}

func (x *ListDrinksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_coffee_machine_v1_coffee_machine_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDrinksResponse.ProtoReflect.Descriptor instead.
func (*ListDrinksResponse) Descriptor() ([]byte, []int) {
	return file_coffee_machine_v1_coffee_machine_proto_rawDescGZIP(), []int{12}
}

func (x *ListDrinksResponse) GetDrinks() []*Drink {
	if x != nil {
		return x.Drinks
	}
	return nil
}

type UpsertDeviceDrinkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Relation      *DeviceDrink           `protobuf:"bytes,1,opt,name=relation,proto3" json:"relation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertDeviceDrinkRequest) Reset() {
	*x = UpsertDeviceDrinkRequest{}
	mi := &file_coffee_machine_v1_coffee_machine_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertDeviceDrinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertDeviceDrinkRequest) ProtoMessage() {}

func (x *UpsertDeviceDrinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_coffee_machine_v1_coffee_machine_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertDeviceDrinkRequest.ProtoReflect.Descriptor instead.
func (*UpsertDeviceDrinkRequest) Descriptor() ([]byte, []int) {
	return file_coffee_machine_v1_coffee_machine_proto_rawDescGZIP(), []int{13}
}

func (x *UpsertDeviceDrinkRequest) GetRelation() *DeviceDrink {
	if x != nil {
		return x.Relation
	}
	return nil
}

type ListDeviceDrinksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDeviceDrinksRequest) Reset() {
	*x = ListDeviceDrinksRequest{}
	mi := &file_coffee_machine_v1_coffee_machine_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDeviceDrinksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDeviceDrinksRequest) ProtoMessage() {}

func (x *ListDeviceDrinksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_coffee_machine_v1_coffee_machine_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDeviceDrinksRequest.ProtoReflect.Descriptor instead.
func (*ListDeviceDrinksRequest) Descriptor() ([]byte, []int) {
	return file_coffee_machine_v1_coffee_machine_proto_rawDescGZIP(), []int{14}
}

func (x *ListDeviceDrinksRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

type ListDeviceDrinksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Relations     []*DeviceDrink         `protobuf:"bytes,1,rep,name=relations,proto3" json:"relations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDeviceDrinksResponse) Reset() {
	*x = ListDeviceDrinksResponse{}
	mi := &file_coffee_machine_v1_coffee_machine_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDeviceDrinksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDeviceDrinksResponse) ProtoMessage() {}

func (x *ListDeviceDrinksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_coffee_machine_v1_coffee_machine_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDeviceDrinksResponse.ProtoReflect.Descriptor instead.
func (*ListDeviceDrinksResponse) Descriptor() ([]byte, []int) {
	return file_coffee_machine_v1_coffee_machine_proto_rawDescGZIP(), []int{15}
}

func (x *ListDeviceDrinksResponse) GetRelations() []*DeviceDrink {
	if x != nil {
		return x.Relations
	}
	return nil
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deleted       bool                   `protobuf:"varint,1,opt,name=deleted,proto3" json:"deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_coffee_machine_v1_coffee_machine_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_coffee_machine_v1_coffee_machine_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_coffee_machine_v1_coffee_machine_proto_rawDescGZIP(), []int{16}
}

func (x *DeleteResponse) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

var File_coffee_machine_v1_coffee_machine_proto protoreflect.FileDescriptor

const file_coffee_machine_v1_coffee_machine_proto_rawDesc = "" +
	"\n" +
	"&coffee_machine/v1/coffee_machine.proto\x12\x11coffee_machine.v1\"z\n" +
	"\fManufacturer\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12!\n" +
	"\fcontact_name\x18\x03 \x01(\tR\vcontactName\x12#\n" +
	"\rcontact_phone\x18\x04 \x01(\tR\fcontactPhone\"\xae\x01\n" +
	"\x06Device\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12'\n" +
	"\x0fmanufacturer_id\x18\x02 \x01(\tR\x0emanufacturerId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12#\n" +
	"\rserial_number\x18\x04 \x01(\tR\fserialNumber\x12\x1a\n" +
	"\blocation\x18\x05 \x01(\tR\blocation\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\"{\n" +
	"\x05Drink\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x03R\x05price\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\"_\n" +
	"\vDeviceDrink\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x19\n" +
	"\bdrink_id\x18\x02 \x01(\tR\adrinkId\x12\x18\n" +
	"\aenabled\x18\x03 \x01(\bR\aenabled\" \n" +
	"\x0eManufacturerID\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x1a\n" +
	"\bDeviceID\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x19\n" +
	"\aDrinkID\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x1a\n" +
	"\x18ListManufacturersRequest\"b\n" +
	"\x19ListManufacturersResponse\x12E\n" +
	"\rmanufacturers\x18\x01 \x03(\v2\x1f.coffee_machine.v1.ManufacturerR\rmanufacturers\"U\n" +
	"\x12ListDevicesRequest\x12'\n" +
	"\x0fmanufacturer_id\x18\x01 \x01(\tR\x0emanufacturerId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"J\n" +
	"\x13ListDevicesResponse\x123\n" +
	"\adevices\x18\x01 \x03(\v2\x19.coffee_machine.v1.DeviceR\adevices\"+\n" +
	"\x11ListDrinksRequest\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"F\n" +
	"\x12ListDrinksResponse\x120\n" +
	"\x06drinks\x18\x01 \x03(\v2\x18.coffee_machine.v1.DrinkR\x06drinks\"V\n" +
	"\x18UpsertDeviceDrinkRequest\x12:\n" +
	"\brelation\x18\x01 \x01(\v2\x1e.coffee_machine.v1.DeviceDrinkR\brelation\"6\n" +
	"\x17ListDeviceDrinksRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\"X\n" +
	"\x18ListDeviceDrinksResponse\x12<\n" +
	"\trelations\x18\x01 \x03(\v2\x1e.coffee_machine.v1.DeviceDrinkR\trelations\"*\n" +
	"\x0eDeleteResponse\x12\x18\n" +
	"\adeleted\x18\x01 \x01(\bR\adeleted2\x88\x06\n" +
	"\x14CoffeeMachineService\x12n\n" +
	"\x11ListManufacturers\x12+.coffee_machine.v1.ListManufacturersRequest\x1a,.coffee_machine.v1.ListManufacturersResponse\x12\\\n" +
	"\vListDevices\x12%.coffee_machine.v1.ListDevicesRequest\x1a&.coffee_machine.v1.ListDevicesResponse\x12Y\n" +
	"\n" +
	"ListDrinks\x12$.coffee_machine.v1.ListDrinksRequest\x1a%.coffee_machine.v1.ListDrinksResponse\x12`\n" +
	"\x11UpsertDeviceDrink\x12+.coffee_machine.v1.UpsertDeviceDrinkRequest\x1a\x1e.coffee_machine.v1.DeviceDrink\x12k\n" +
	"\x10ListDeviceDrinks\x12*.coffee_machine.v1.ListDeviceDrinksRequest\x1a+.coffee_machine.v1.ListDeviceDrinksResponse\x12Z\n" +
	"\x12DeleteManufacturer\x12!.coffee_machine.v1.ManufacturerID\x1a!.coffee_machine.v1.DeleteResponse\x12N\n" +
	"\fDeleteDevice\x12\x1b.coffee_machine.v1.DeviceID\x1a!.coffee_machine.v1.DeleteResponse\x12L\n" +
	"\vDeleteDrink\x12\x1a.coffee_machine.v1.DrinkID\x1a!.coffee_machine.v1.DeleteResponseBAZ?github.com/panda-dev/panda-v2/contracts/proto/coffee_machine/v1b\x06proto3"

var (
	file_coffee_machine_v1_coffee_machine_proto_rawDescOnce sync.Once
	file_coffee_machine_v1_coffee_machine_proto_rawDescData []byte
)

func file_coffee_machine_v1_coffee_machine_proto_rawDescGZIP() []byte {
	file_coffee_machine_v1_coffee_machine_proto_rawDescOnce.Do(func() {
		file_coffee_machine_v1_coffee_machine_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_coffee_machine_v1_coffee_machine_proto_rawDesc), len(file_coffee_machine_v1_coffee_machine_proto_rawDesc)))
	})
	return file_coffee_machine_v1_coffee_machine_proto_rawDescData
}

var file_coffee_machine_v1_coffee_machine_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_coffee_machine_v1_coffee_machine_proto_goTypes = []any{
	(*Manufacturer)(nil),              // 0: coffee_machine.v1.Manufacturer
	(*Device)(nil),                    // 1: coffee_machine.v1.Device
	(*Drink)(nil),                     // 2: coffee_machine.v1.Drink
	(*DeviceDrink)(nil),               // 3: coffee_machine.v1.DeviceDrink
	(*ManufacturerID)(nil),            // 4: coffee_machine.v1.ManufacturerID
	(*DeviceID)(nil),                  // 5: coffee_machine.v1.DeviceID
	(*DrinkID)(nil),                   // 6: coffee_machine.v1.DrinkID
	(*ListManufacturersRequest)(nil),  // 7: coffee_machine.v1.ListManufacturersRequest
	(*ListManufacturersResponse)(nil), // 8: coffee_machine.v1.ListManufacturersResponse
	(*ListDevicesRequest)(nil),        // 9: coffee_machine.v1.ListDevicesRequest
	(*ListDevicesResponse)(nil),       // 10: coffee_machine.v1.ListDevicesResponse
	(*ListDrinksRequest)(nil),         // 11: coffee_machine.v1.ListDrinksRequest
	(*ListDrinksResponse)(nil),        // 12: coffee_machine.v1.ListDrinksResponse
	(*UpsertDeviceDrinkRequest)(nil),  // 13: coffee_machine.v1.UpsertDeviceDrinkRequest
	(*ListDeviceDrinksRequest)(nil),   // 14: coffee_machine.v1.ListDeviceDrinksRequest
	(*ListDeviceDrinksResponse)(nil),  // 15: coffee_machine.v1.ListDeviceDrinksResponse
	(*DeleteResponse)(nil),            // 16: coffee_machine.v1.DeleteResponse
}
var file_coffee_machine_v1_coffee_machine_proto_depIdxs = []int32{
	0,  // 0: coffee_machine.v1.ListManufacturersResponse.manufacturers:type_name -> coffee_machine.v1.Manufacturer
	1,  // 1: coffee_machine.v1.ListDevicesResponse.devices:type_name -> coffee_machine.v1.Device
	2,  // 2: coffee_machine.v1.ListDrinksResponse.drinks:type_name -> coffee_machine.v1.Drink
	3,  // 3: coffee_machine.v1.UpsertDeviceDrinkRequest.relation:type_name -> coffee_machine.v1.DeviceDrink
	3,  // 4: coffee_machine.v1.ListDeviceDrinksResponse.relations:type_name -> coffee_machine.v1.DeviceDrink
	7,  // 5: coffee_machine.v1.CoffeeMachineService.ListManufacturers:input_type -> coffee_machine.v1.ListManufacturersRequest
	9,  // 6: coffee_machine.v1.CoffeeMachineService.ListDevices:input_type -> coffee_machine.v1.ListDevicesRequest
	11, // 7: coffee_machine.v1.CoffeeMachineService.ListDrinks:input_type -> coffee_machine.v1.ListDrinksRequest
	13, // 8: coffee_machine.v1.CoffeeMachineService.UpsertDeviceDrink:input_type -> coffee_machine.v1.UpsertDeviceDrinkRequest
	14, // 9: coffee_machine.v1.CoffeeMachineService.ListDeviceDrinks:input_type -> coffee_machine.v1.ListDeviceDrinksRequest
	4,  // 10: coffee_machine.v1.CoffeeMachineService.DeleteManufacturer:input_type -> coffee_machine.v1.ManufacturerID
	5,  // 11: coffee_machine.v1.CoffeeMachineService.DeleteDevice:input_type -> coffee_machine.v1.DeviceID
	6,  // 12: coffee_machine.v1.CoffeeMachineService.DeleteDrink:input_type -> coffee_machine.v1.DrinkID
	8,  // 13: coffee_machine.v1.CoffeeMachineService.ListManufacturers:output_type -> coffee_machine.v1.ListManufacturersResponse
	10, // 14: coffee_machine.v1.CoffeeMachineService.ListDevices:output_type -> coffee_machine.v1.ListDevicesResponse
	12, // 15: coffee_machine.v1.CoffeeMachineService.ListDrinks:output_type -> coffee_machine.v1.ListDrinksResponse
	3,  // 16: coffee_machine.v1.CoffeeMachineService.UpsertDeviceDrink:output_type -> coffee_machine.v1.DeviceDrink
	15, // 17: coffee_machine.v1.CoffeeMachineService.ListDeviceDrinks:output_type -> coffee_machine.v1.ListDeviceDrinksResponse
	16, // 18: coffee_machine.v1.CoffeeMachineService.DeleteManufacturer:output_type -> coffee_machine.v1.DeleteResponse
	16, // 19: coffee_machine.v1.CoffeeMachineService.DeleteDevice:output_type -> coffee_machine.v1.DeleteResponse
	16, // 20: coffee_machine.v1.CoffeeMachineService.DeleteDrink:output_type -> coffee_machine.v1.DeleteResponse
	13, // [13:21] is the sub-list for method output_type
	5,  // [5:13] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_coffee_machine_v1_coffee_machine_proto_init() }
func file_coffee_machine_v1_coffee_machine_proto_init() {
	if File_coffee_machine_v1_coffee_machine_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_coffee_machine_v1_coffee_machine_proto_rawDesc), len(file_coffee_machine_v1_coffee_machine_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_coffee_machine_v1_coffee_machine_proto_goTypes,
		DependencyIndexes: file_coffee_machine_v1_coffee_machine_proto_depIdxs,
		MessageInfos:      file_coffee_machine_v1_coffee_machine_proto_msgTypes,
	}.Build()
	File_coffee_machine_v1_coffee_machine_proto = out.File
	file_coffee_machine_v1_coffee_machine_proto_goTypes = nil
	file_coffee_machine_v1_coffee_machine_proto_depIdxs = nil
}
