-- coffee_machine/002：咖啡机表和关键字段中文注释

COMMENT ON TABLE manufacturers IS '设备厂商';
COMMENT ON COLUMN manufacturers.id IS '主键';
COMMENT ON COLUMN manufacturers.legacy_id IS '旧系统 MongoDB ObjectID，仅用于迁移对账';
COMMENT ON COLUMN manufacturers.code IS '厂商编码，稳定业务标识，创建后不可修改';
COMMENT ON COLUMN manufacturers.name IS '厂商名称';
COMMENT ON COLUMN manufacturers.contact_name IS '联系人';
COMMENT ON COLUMN manufacturers.contact_phone IS '联系电话';
COMMENT ON COLUMN manufacturers.status IS '状态：active=启用，disabled=停用';
COMMENT ON COLUMN manufacturers.created_at IS '创建时间';
COMMENT ON COLUMN manufacturers.updated_at IS '更新时间';

COMMENT ON TABLE manufacturer_credentials IS '厂商接入凭据与访问令牌';
COMMENT ON COLUMN manufacturer_credentials.manufacturer_id IS '厂商 ID，引用本库 manufacturers';
COMMENT ON COLUMN manufacturer_credentials.api_base_url IS '生产环境接口地址';
COMMENT ON COLUMN manufacturer_credentials.test_api_base_url IS '测试环境接口地址';
COMMENT ON COLUMN manufacturer_credentials.username IS '厂商接口账号';
COMMENT ON COLUMN manufacturer_credentials.user_secret IS '厂商接口密钥，不回传前端';
COMMENT ON COLUMN manufacturer_credentials.signing_secret IS '回调签名校验密钥';
COMMENT ON COLUMN manufacturer_credentials.access_token IS '当前访问令牌';
COMMENT ON COLUMN manufacturer_credentials.token_expires_at IS '令牌过期时间';
COMMENT ON COLUMN manufacturer_credentials.created_at IS '创建时间';
COMMENT ON COLUMN manufacturer_credentials.updated_at IS '更新时间';

COMMENT ON TABLE devices IS '咖啡机设备主数据';
COMMENT ON COLUMN devices.id IS '主键';
COMMENT ON COLUMN devices.legacy_id IS '旧系统 MongoDB ObjectID，仅用于迁移对账';
COMMENT ON COLUMN devices.serial_unique IS '设备序列号，全局唯一';
COMMENT ON COLUMN devices.device_name IS '设备名称';
COMMENT ON COLUMN devices.manufacturer_id IS '厂商 ID，引用本库 manufacturers';
COMMENT ON COLUMN devices.store_id IS '部署点位 ID，属于商户服务，仅作跨库值引用';
COMMENT ON COLUMN devices.status IS '是否启用：active=启用，disabled=停用';
COMMENT ON COLUMN devices.vendor_online IS '设备是否在线，由厂商上报；NULL 表示从未同步过，不等于离线';
COMMENT ON COLUMN devices.last_synced_at IS '最近一次厂商同步时间';
COMMENT ON COLUMN devices.version_number IS '设备版本号';
COMMENT ON COLUMN devices.android_version IS 'Android 系统版本';
COMMENT ON COLUMN devices.main_board_version IS '主板版本';
COMMENT ON COLUMN devices.last_fault_code IS '最近一次故障码';
COMMENT ON COLUMN devices.last_fault_message IS '最近一次故障描述';
COMMENT ON COLUMN devices.last_fault_at IS '最近一次故障时间';
COMMENT ON COLUMN devices.last_active_at IS '最近一次活跃时间';
COMMENT ON COLUMN devices.pickup_password IS '店员打咖啡用的静态验证码';
COMMENT ON COLUMN devices.coffee_balance IS '咖啡余额，单位为分';
COMMENT ON COLUMN devices.show_vip IS '是否展示会员价';
COMMENT ON COLUMN devices.enable_coupon_verification IS '是否允许核销会员价体验券';
COMMENT ON COLUMN devices.warranty_end_at IS '保修到期时间';
COMMENT ON COLUMN devices.qrcode_type IS '二维码类型：miniprogram=小程序码，regular=常规码';
COMMENT ON COLUMN devices.regular_qrcode_payment_method IS '常规码使用的支付渠道：fengxuan_wanlian=丰选万联，youlian=友联';
COMMENT ON COLUMN devices.created_at IS '创建时间';
COMMENT ON COLUMN devices.updated_at IS '更新时间';

COMMENT ON TABLE device_payment_methods IS '设备支持的支付方式';
COMMENT ON COLUMN device_payment_methods.id IS '主键';
COMMENT ON COLUMN device_payment_methods.device_id IS '设备 ID，引用本库 devices';
COMMENT ON COLUMN device_payment_methods.payment_method_id IS '支付方式 ID，属于支付服务，仅作跨库值引用';
COMMENT ON COLUMN device_payment_methods.sort_order IS '展示排序，值越小越靠前';
COMMENT ON COLUMN device_payment_methods.created_at IS '创建时间';

COMMENT ON TABLE drinks IS '饮品目录，按厂商维护';
COMMENT ON COLUMN drinks.id IS '主键';
COMMENT ON COLUMN drinks.legacy_id IS '旧系统 MongoDB ObjectID，仅用于迁移对账';
COMMENT ON COLUMN drinks.manufacturer_id IS '厂商 ID，引用本库 manufacturers';
COMMENT ON COLUMN drinks.origin_id IS '厂商侧饮品 ID；为空表示后台手工新建、不参与同步判重的饮品';
COMMENT ON COLUMN drinks.product_num IS '制作饮品用的商品编号';
COMMENT ON COLUMN drinks.product_name IS '饮品名称';
COMMENT ON COLUMN drinks.en_name IS '饮品英文名称';
COMMENT ON COLUMN drinks.drink_type IS '饮品类型：milk_coffee=奶咖，black_coffee=黑咖，other=其他';
COMMENT ON COLUMN drinks.product_img IS '饮品图片地址';
COMMENT ON COLUMN drinks.product_desc IS '饮品描述';
COMMENT ON COLUMN drinks.price IS '原价，单位为分';
COMMENT ON COLUMN drinks.vip_price IS '会员价，单位为分';
COMMENT ON COLUMN drinks.pickup_code_price IS '提货码价，单位为分';
COMMENT ON COLUMN drinks.status IS '上下架状态：on_shelf=上架，off_shelf=下架';
COMMENT ON COLUMN drinks.sort IS '展示排序，值越小越靠前';
COMMENT ON COLUMN drinks.created_at IS '创建时间';
COMMENT ON COLUMN drinks.updated_at IS '更新时间';

COMMENT ON TABLE device_drinks IS '设备与饮品的供应关系，可覆盖每台设备的售价';
COMMENT ON COLUMN device_drinks.id IS '主键';
COMMENT ON COLUMN device_drinks.legacy_id IS '旧系统 MongoDB ObjectID，仅用于迁移对账';
COMMENT ON COLUMN device_drinks.device_id IS '设备 ID，引用本库 devices';
COMMENT ON COLUMN device_drinks.drink_id IS '饮品 ID，引用本库 drinks';
COMMENT ON COLUMN device_drinks.enabled IS '该设备是否供应此饮品';
COMMENT ON COLUMN device_drinks.sort_order IS '展示排序，值越小越靠前';
COMMENT ON COLUMN device_drinks.price IS '该设备的原价覆盖，单位为分；NULL 表示沿用饮品目录价';
COMMENT ON COLUMN device_drinks.vip_price IS '该设备的会员价覆盖，单位为分；NULL 表示沿用饮品目录价';
COMMENT ON COLUMN device_drinks.pickup_code_price IS '该设备的提货码价覆盖，单位为分；NULL 表示沿用饮品目录价';
COMMENT ON COLUMN device_drinks.created_at IS '创建时间';
COMMENT ON COLUMN device_drinks.updated_at IS '更新时间';

COMMENT ON TABLE device_events IS '设备事件日志';
COMMENT ON COLUMN device_events.id IS '主键';
COMMENT ON COLUMN device_events.legacy_id IS '旧系统 MongoDB ObjectID，仅用于迁移对账';
COMMENT ON COLUMN device_events.device_id IS '设备 ID，引用本库 devices';
COMMENT ON COLUMN device_events.source IS '事件来源：vendor=厂商，machine=机器，admin=后台，system=系统';
COMMENT ON COLUMN device_events.event_type IS '事件类型，自由字符串，例如 device_store_changed';
COMMENT ON COLUMN device_events.occurred_at IS '事件发生时间';
COMMENT ON COLUMN device_events.received_at IS '事件接收时间';
COMMENT ON COLUMN device_events.external_event_id IS '厂商侧事件 ID，用于回调去重';
COMMENT ON COLUMN device_events.error_code IS '错误码';
COMMENT ON COLUMN device_events.error_message IS '错误描述';
COMMENT ON COLUMN device_events.detail IS '事件可读摘要，例如设备更换点位的前后 store_id';
COMMENT ON COLUMN device_events.payload IS '厂商原始报文';

COMMENT ON TABLE device_balance_ledger IS '设备余额账变流水，只允许追加';
COMMENT ON COLUMN device_balance_ledger.id IS '主键';
COMMENT ON COLUMN device_balance_ledger.legacy_id IS '旧系统 MongoDB ObjectID，仅用于迁移对账';
COMMENT ON COLUMN device_balance_ledger.device_id IS '设备 ID，引用本库 devices';
COMMENT ON COLUMN device_balance_ledger.type IS '账变类型：recharge=充值，deduct=扣减，adjust=调整，reverse=冲正';
COMMENT ON COLUMN device_balance_ledger.amount IS '变动金额，单位为分；有符号，充值为正、扣减为负';
COMMENT ON COLUMN device_balance_ledger.balance_after IS '变动后余额，单位为分';
COMMENT ON COLUMN device_balance_ledger.reverses_entry_id IS '冲正对应的原始流水 ID，引用本表';
COMMENT ON COLUMN device_balance_ledger.reference_type IS '账变起因的对象类型，例如提货单、后台充值单；本列记的是「为什么余额变了」，与事件日志不同';
COMMENT ON COLUMN device_balance_ledger.reference_id IS '账变起因的对象 ID，仅作跨库值引用';
COMMENT ON COLUMN device_balance_ledger.request_id IS '幂等请求号或业务单号，同一请求号只落一条流水';
COMMENT ON COLUMN device_balance_ledger.remark IS '备注';
COMMENT ON COLUMN device_balance_ledger.operator_id IS '操作人 ID，属于身份服务，仅作跨库值引用';
COMMENT ON COLUMN device_balance_ledger.operator_name IS '操作人名称';
COMMENT ON COLUMN device_balance_ledger.created_at IS '创建时间';

COMMENT ON TABLE message_outbox IS '待发布消息事件，审计与通知在业务事务内追加到这里';
COMMENT ON COLUMN message_outbox.event_id IS '事件唯一 ID';
COMMENT ON COLUMN message_outbox.event_type IS '事件类型，也是 RabbitMQ 的 routing key';
COMMENT ON COLUMN message_outbox.event_version IS '事件版本，载荷形状不兼容变更时递增';
COMMENT ON COLUMN message_outbox.trace_id IS '关联调用链 ID';
COMMENT ON COLUMN message_outbox.payload IS '事件内容，JSON 序列化后的字节';
COMMENT ON COLUMN message_outbox.attempts IS '发布尝试次数';
COMMENT ON COLUMN message_outbox.next_attempt_at IS '下次投递时间，失败重试据此退避';
COMMENT ON COLUMN message_outbox.published_at IS '成功发布时间；为空表示尚未投出';
COMMENT ON COLUMN message_outbox.lease_owner IS '当前投递方实例标识';
COMMENT ON COLUMN message_outbox.lease_token IS '投递租约令牌，防止两个副本重复投递';
COMMENT ON COLUMN message_outbox.lease_until IS '投递租约截止时间';
COMMENT ON COLUMN message_outbox.last_error IS '最近一次投递失败原因';
COMMENT ON COLUMN message_outbox.created_at IS '创建时间';

COMMENT ON TABLE message_inbox IS '已接收消息事件及消费租约';
COMMENT ON COLUMN message_inbox.event_id IS '已接收事件唯一 ID，用于消费去重';
COMMENT ON COLUMN message_inbox.claimed_at IS '首次领取消费时间';
COMMENT ON COLUMN message_inbox.lease_owner IS '当前消费方实例标识';
COMMENT ON COLUMN message_inbox.lease_token IS '消费租约令牌，防止两个副本重复消费';
COMMENT ON COLUMN message_inbox.lease_until IS '消费租约截止时间';
COMMENT ON COLUMN message_inbox.completed_at IS '成功完成消费时间';
