-- order/002：订单表和关键字段中文注释

COMMENT ON TABLE orders IS '订单主表：一次下单的事实，金额单位为分；买了哪几件东西见 order_lines。订单类型不存列，由行的 line_type 派生：有 membership 行的是会员订单，有 drink 行的是咖啡订单';
COMMENT ON COLUMN orders.order_no IS '订单号，业务唯一';
COMMENT ON COLUMN orders.legacy_id IS '老库订单 ID（ObjectID 十六进制），仅迁移过来的历史订单有值';
COMMENT ON COLUMN orders.user_id IS '下单用户 ID，属于身份服务时仅作跨库值引用';
COMMENT ON COLUMN orders.source IS '下单来源：miniapp=小程序直接下单，screen_qr=咖啡机屏幕选品后扫码下单';
COMMENT ON COLUMN orders.status IS '订单状态：pending_payment=待支付，paid=已支付，completed=已完成，cancelled=已取消，expired=支付超时，refunding=退款中，refunded=已退款';
COMMENT ON COLUMN orders.fulfillment_status IS '履约状态汇总（只由饮品行驱动）：pending=待制作，making=制作中，ready=待取杯，completed=已取杯，failed=出杯失败，cancelled=已取消，none=本单无需履约（纯会员订单）；事实由履约服务产生';
COMMENT ON COLUMN orders.store_id IS '点位或门店 ID，属于商户服务时仅作跨库值引用';
COMMENT ON COLUMN orders.store_name IS '下单时的点位名称快照';
COMMENT ON COLUMN orders.device_id IS '咖啡机 ID，属于咖啡机服务时仅作跨库值引用';
COMMENT ON COLUMN orders.device_no IS '下单时的咖啡机编号快照';
COMMENT ON COLUMN orders.scene_token IS '屏幕选品会话标识，属于咖啡机侧时仅作跨库值引用';
COMMENT ON COLUMN orders.original_amount IS '订单原价，单位为分；等于各行原价之和';
COMMENT ON COLUMN orders.discount_amount IS '订单优惠合计（会员价、活动、券等），单位为分；等于各行优惠之和';
COMMENT ON COLUMN orders.payable_amount IS '应付金额，单位为分；等于原价减优惠合计，也等于各行应付之和';
COMMENT ON COLUMN orders.paid_amount IS '已支付金额，单位为分';
COMMENT ON COLUMN orders.refunded_amount IS '已退款金额，单位为分';
COMMENT ON COLUMN orders.membership_id IS '下单时的会员资格 ID（会员价的计算依据），属于会员服务时仅作跨库值引用；买会员套餐这件事本身是 order_lines 里的会员行';
COMMENT ON COLUMN orders.membership_snapshot IS '下单时的会员资格快照（等级、有效期等），结构归会员服务，本库只存副本；与 order_lines 的会员套餐快照是两回事：这里是「买的时候已经是会员」，那里是「这一单买了会员」';
COMMENT ON COLUMN orders.fortune_cards_expected IS '本单承诺发放的福卡张数，包含基础赠送与加购活动加赠';
COMMENT ON COLUMN orders.fortune_card_snapshot IS '承诺发放福卡的构成快照（基础赠送、各活动加赠）；发放结果与余额归账户服务';
COMMENT ON COLUMN orders.payment_method IS '主支付渠道，逐笔出资见 order_payment_lines';
COMMENT ON COLUMN orders.payment_no IS '支付单号，属于支付服务时仅作跨库值引用，非空时唯一';
COMMENT ON COLUMN orders.paid_at IS '支付完成时间';
COMMENT ON COLUMN orders.finished_at IS '订单完成时间';
COMMENT ON COLUMN orders.cancelled_at IS '订单取消时间';
COMMENT ON COLUMN orders.cancellation_reason IS '取消原因';
COMMENT ON COLUMN orders.expires_at IS '待支付订单的超时时间，超时关单扫描依据';
COMMENT ON COLUMN orders.remark IS '订单备注';
COMMENT ON COLUMN orders.request_id IS '下单请求幂等号，非空时唯一';

COMMENT ON TABLE order_lines IS '订单行：这一单买了哪几件东西，一件一行，带商品快照、数量、价格与优惠';
COMMENT ON COLUMN order_lines.order_id IS '订单 ID';
COMMENT ON COLUMN order_lines.line_no IS '订单内行号';
COMMENT ON COLUMN order_lines.line_type IS '行类型：drink=饮品（一次一杯），addon=加购品（幸运杯套一类的活动商品），membership=会员（开通或续费的套餐）';
COMMENT ON COLUMN order_lines.legacy_id IS '老库对应记录 ID（ObjectID 十六进制），仅迁移过来的历史数据有值';
COMMENT ON COLUMN order_lines.item_id IS '商品 ID，属于咖啡机服务时仅作跨库值引用（会员行是会员服务的套餐 ID）；加购品可能只有活动、没有独立商品，此时为空';
COMMENT ON COLUMN order_lines.item_code IS '下单时的商品编码快照';
COMMENT ON COLUMN order_lines.item_name IS '下单时的商品名称快照';
COMMENT ON COLUMN order_lines.item_image IS '下单时的商品图片快照';
COMMENT ON COLUMN order_lines.quantity IS '数量；饮品与会员恒为 1，加购品可以多件';
COMMENT ON COLUMN order_lines.original_unit_price IS '下单时的商品目录单价，单位为分';
COMMENT ON COLUMN order_lines.unit_price IS '成交单价，单位为分，仅用于展示与对账；不参与任何金额恒等式，不是「本行应付除以数量」';
COMMENT ON COLUMN order_lines.price_discount_amount IS '标价优惠金额，单位为分：目录价与成交单价之间的差额，例如会员价、活动价（原型里的 memberDiscountCents）；只有饮品行与加购行可能有，会员费恒为 0';
COMMENT ON COLUMN order_lines.discount_amount IS '本行优惠合计，单位为分；等于标价优惠加券抵扣；加购品的活动价也走标价优惠这一格';
COMMENT ON COLUMN order_lines.payable_amount IS '本行应付金额，单位为分；等于商品目录单价乘数量减本行优惠合计';
COMMENT ON COLUMN order_lines.coupon_id IS '本行使用的用户券 ID，属于优惠券服务时仅作跨库值引用；券挂在行上（咖啡券只优惠饮品，不抵扣幸运杯套），一张券只能落一行';
COMMENT ON COLUMN order_lines.coupon_discount_amount IS '本行由用户券抵扣的金额，单位为分；是本行优惠合计里的券那部分，只有饮品行可以为非零';
COMMENT ON COLUMN order_lines.specs IS '饮品规格快照（冷热、杯型、糖量等），结构归咖啡机服务；加购品与会员行为空对象';
COMMENT ON COLUMN order_lines.selection_snapshot IS '固定选品原始快照，用于还原与排查，不参与查询；加购品与会员行为空对象';
COMMENT ON COLUMN order_lines.campaign_id IS '加购活动 ID，属于活动归属服务时仅作跨库值引用；只有加购行有';
COMMENT ON COLUMN order_lines.campaign_snapshot IS '成交时的加购活动快照（活动名称、活动价、每件赠卡数）；活动改规则或下架不影响历史订单';
COMMENT ON COLUMN order_lines.membership_plan_snapshot IS '成交时的会员套餐快照（套餐名称、时长、续费目标会员、权益摘要）；结构归会员服务，本库只存副本；只有会员行有值';
COMMENT ON COLUMN order_lines.device_id IS '出杯咖啡机 ID，与所属订单的 device_id 一致，冗余用于厂商单号的唯一性作用域；只有饮品行有';
COMMENT ON COLUMN order_lines.device_order_no IS '咖啡机侧订单号，外部单号，同一台机器内唯一；只有饮品行有';
COMMENT ON COLUMN order_lines.fulfillment_task_no IS '履约任务号，属于履约服务时仅作跨库值引用；只有饮品行有';
COMMENT ON COLUMN order_lines.pickup_no IS '取杯号，取杯口显示的短号；只有饮品行有';
COMMENT ON COLUMN order_lines.pickup_code IS '取杯码，取杯凭据；不得写入日志、审计、事件与后台列表；只有饮品行有';
COMMENT ON COLUMN order_lines.remark IS '单行备注（例如加购品的口味或备注）';

COMMENT ON TABLE order_payment_lines IS '订单出资分摊：一个订单下逐笔出资来源与金额';
COMMENT ON COLUMN order_payment_lines.order_id IS '订单 ID';
COMMENT ON COLUMN order_payment_lines.line_no IS '订单内出资序号';
COMMENT ON COLUMN order_payment_lines.line_type IS '出资来源：wechat=微信，unionpay=银联，coffee_bean=咖啡豆，fortune_card=福卡，wallet=其他钱包，other=其他';
COMMENT ON COLUMN order_payment_lines.amount IS '该笔出资金额，单位为分';
COMMENT ON COLUMN order_payment_lines.status IS '出资状态：reserved=已预占，succeeded=已成功，failed=已失败，released=已释放，reversed=已冲正';
COMMENT ON COLUMN order_payment_lines.payment_no IS '支付单号，属于支付服务时仅作跨库值引用';
COMMENT ON COLUMN order_payment_lines.provider_transaction_id IS '渠道方流水号';
COMMENT ON COLUMN order_payment_lines.failure_code IS '失败码';
COMMENT ON COLUMN order_payment_lines.account_entry_id IS '账户账变 ID，属于账户服务时仅作跨库值引用';
COMMENT ON COLUMN order_payment_lines.succeeded_at IS '出资成功时间';
COMMENT ON COLUMN order_payment_lines.reversed_at IS '出资冲正时间';

COMMENT ON TABLE order_state_transitions IS '订单领域状态变更审计记录，只追加';
COMMENT ON COLUMN order_state_transitions.aggregate_type IS '聚合类型：order=订单，order_line=订单行，after_sale=售后单，payment_line=出资';
COMMENT ON COLUMN order_state_transitions.aggregate_id IS '发生状态变化的聚合 ID';
COMMENT ON COLUMN order_state_transitions.from_status IS '变更前状态';
COMMENT ON COLUMN order_state_transitions.to_status IS '变更后状态';
COMMENT ON COLUMN order_state_transitions.reason IS '状态变更原因';
COMMENT ON COLUMN order_state_transitions.request_id IS '触发状态变化的请求幂等号';
COMMENT ON COLUMN order_state_transitions.actor_type IS '操作者类型：user=用户，merchant=商户，admin=后台，system=系统';
COMMENT ON COLUMN order_state_transitions.actor_id IS '操作人 ID，属于身份服务时仅作跨库值引用';
COMMENT ON COLUMN order_state_transitions.metadata IS '状态变化附加信息';

COMMENT ON TABLE order_after_sales IS '订单售后申请与处理结果，不保存退款单本身';
COMMENT ON COLUMN order_after_sales.legacy_id IS '老库退款单 ID（ObjectID 十六进制），仅迁移过来的历史记录有值';
COMMENT ON COLUMN order_after_sales.after_sale_no IS '售后单号，业务唯一';
COMMENT ON COLUMN order_after_sales.order_id IS '订单 ID';
COMMENT ON COLUMN order_after_sales.order_no IS '订单号快照，供客服与对账直接检索';
COMMENT ON COLUMN order_after_sales.user_id IS '申请用户 ID，属于身份服务时仅作跨库值引用';
COMMENT ON COLUMN order_after_sales.type IS '售后类型，当前只有 refund=退款';
COMMENT ON COLUMN order_after_sales.scope IS '退款范围：all=整单，drink=只退饮品行，addon=只退加购行，membership=只退会员套餐；除整单外都必须指明具体是哪一行';
COMMENT ON COLUMN order_after_sales.order_line_id IS '退的那一行，指向 order_lines；scope=all 时为空，其余范围必填（同一单有两件加购品时，只有它能说清退的是哪件）；「这一行属于本售后单的订单」由服务校验，外键看不到别的行';
COMMENT ON COLUMN order_after_sales.status IS '售后状态：pending=待处理，approved=已通过，rejected=已驳回，refunding=退款中，refunded=已退款，failed=退款失败，cancelled=已撤销';
COMMENT ON COLUMN order_after_sales.reason IS '申请原因';
COMMENT ON COLUMN order_after_sales.images IS '申请凭证图片 URL 列表';
COMMENT ON COLUMN order_after_sales.refund_amount IS '退款金额，单位为分';
COMMENT ON COLUMN order_after_sales.refund_no IS '退款单号，属于支付服务时仅作跨库值引用';
COMMENT ON COLUMN order_after_sales.failure_code IS '退款失败码';
COMMENT ON COLUMN order_after_sales.reviewed_by IS '审核人 ID，属于身份服务时仅作跨库值引用';
COMMENT ON COLUMN order_after_sales.reviewed_at IS '审核时间';
COMMENT ON COLUMN order_after_sales.review_remark IS '审核备注';
COMMENT ON COLUMN order_after_sales.refunded_at IS '退款完成时间';

COMMENT ON TABLE order_idempotency_keys IS '订单操作幂等请求记录';
COMMENT ON COLUMN order_idempotency_keys.scope IS '幂等作用域，例如 create、cancel、pay';
COMMENT ON COLUMN order_idempotency_keys.idempotency_key IS '调用方提供的幂等键';
COMMENT ON COLUMN order_idempotency_keys.request_hash IS '请求内容摘要，用于检测同一幂等键复用不同请求';
COMMENT ON COLUMN order_idempotency_keys.resource_type IS '幂等请求创建或操作的资源类型';
COMMENT ON COLUMN order_idempotency_keys.resource_id IS '幂等请求关联的资源 ID';
COMMENT ON COLUMN order_idempotency_keys.response IS '首次处理结果快照';
COMMENT ON COLUMN order_idempotency_keys.status IS '处理状态：processing=处理中，succeeded=成功，failed=失败';

COMMENT ON TABLE message_outbox IS '订单服务待发布消息事件';
COMMENT ON COLUMN message_outbox.event_id IS '事件唯一 ID';
COMMENT ON COLUMN message_outbox.event_type IS '事件类型';
COMMENT ON COLUMN message_outbox.event_version IS '事件版本';
COMMENT ON COLUMN message_outbox.payload IS '事件内容二进制数据';
COMMENT ON COLUMN message_outbox.attempts IS '发布尝试次数';
COMMENT ON COLUMN message_outbox.published_at IS '成功发布时间';
COMMENT ON COLUMN message_outbox.lease_until IS '消息处理租约截止时间';

COMMENT ON TABLE message_inbox IS '订单服务已接收消息事件及消费租约';
COMMENT ON COLUMN message_inbox.event_id IS '已接收事件唯一 ID，用于消费去重';
COMMENT ON COLUMN message_inbox.claimed_at IS '首次领取消费时间';
COMMENT ON COLUMN message_inbox.lease_until IS '消息消费租约截止时间';
COMMENT ON COLUMN message_inbox.completed_at IS '成功完成消费时间';
