-- order/007：orders.payment_method 的注释跟上它今天真正装的值
--
-- 这一条**只改注释，不动结构、不回填**。002 写的是「主支付渠道，逐笔出资见
-- order_payment_lines」，而这一列从本次改动起装的是**用户选定的支付方式**：
-- payment-service 目录里的 code（ums_h5_alipay / ums_h5_wechat / ums_h5_miniapp_wechat /
-- coffee_bean …），由支付结果事件的 paymentMethodCode 带过来（见 payment-service 的
-- dto.PaymentEventPayload）。
--
-- 改注释不是洁癖：照着旧注释去 `WHERE payment_method = 'wechat'` 的人会以为能捞出所有微信
-- 支付，而新的单子上那一列是 ums_h5_wechat——查出来的是空集。出资渠道仍然逐笔记在
-- order_payment_lines.line_type 上，那一列才是 wechat / unionpay / coffee_bean 那套词表
-- （003 的 CHECK）。
--
-- 为什么要分成两个值：支付宝那条路的 funding_type 是 other（funding_type 的词表里没有
-- 支付宝这一档，见 payment-service 的 catalog），只发 funding_type 的话后台订单列表上的
-- 「支付方式」永远是「其他」，看不出用户是扫码付的支付宝还是微信。而那个值不能直接换掉
-- 了写进 order_payment_lines.line_type——那会撞 003 的 CHECK，整条落单事务回滚，而钱在
-- 支付侧已经收了。
--
-- **不回填历史行**：本次改动之前的单子，这一列存的是 funding_type（other / wechat /
-- coffee_bean），因为那时事件里只有那一个值。「用户当时选的是哪一种方式」这个事实从来没
-- 落进订单库，它在 panda_payment 的 payments.payment_method 上——为了一个展示列去跨库读
-- 不符合两个库各管各的原则，而它本来就是另一个粒度（一条 payments 行未必等于一张订单）。
-- 所以这一列在库里**两种值并存**：老单是出资渠道，新单是支付方式 code，后台列表认不出来
-- 的一律原样回显（见 admin-web 的 paymentMethodLabel）。

COMMENT ON COLUMN orders.payment_method IS '用户选定的支付方式（payment-service 目录里的 code，如 ums_h5_alipay）；出资渠道逐笔见 order_payment_lines.line_type。这一列在本次改动之前的行上记的是出资渠道（other/wechat），两种值并存';
