// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: user/v1/user.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	UserService_GetProfile_FullMethodName        = "/panda.user.v1.UserService/GetProfile"
	UserService_UpdateProfile_FullMethodName     = "/panda.user.v1.UserService/UpdateProfile"
	UserService_HasUsers_FullMethodName          = "/panda.user.v1.UserService/HasUsers"
	UserService_ResetAccountScope_FullMethodName = "/panda.user.v1.UserService/ResetAccountScope"
	UserService_GetWechatIdentity_FullMethodName = "/panda.user.v1.UserService/GetWechatIdentity"
)

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserServiceClient interface {
	GetProfile(ctx context.Context, in *GetProfileRequest, opts ...grpc.CallOption) (*GetProfileResponse, error)
	UpdateProfile(ctx context.Context, in *UpdateProfileRequest, opts ...grpc.CallOption) (*UpdateProfileResponse, error)
	// Internal RPCs. Callers authenticate with the shared service token rather
	// than an end-user access token.
	HasUsers(ctx context.Context, in *HasUsersRequest, opts ...grpc.CallOption) (*HasUsersResponse, error)
	ResetAccountScope(ctx context.Context, in *ResetAccountScopeRequest, opts ...grpc.CallOption) (*ResetAccountScopeResponse, error)
	// GetWechatIdentity 把用户的微信 openid 交给内部调用方。order-service 发起微信小程序
	// 支付时需要它填 payer.openid（渠道必填），而 openid 是用户身份，只能服务间取，
	// 不能由客户端自称（见 order-service 的 dto.PayOrderRequest）。
	GetWechatIdentity(ctx context.Context, in *GetWechatIdentityRequest, opts ...grpc.CallOption) (*GetWechatIdentityResponse, error)
}

type userServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUserServiceClient(cc grpc.ClientConnInterface) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) GetProfile(ctx context.Context, in *GetProfileRequest, opts ...grpc.CallOption) (*GetProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProfileResponse)
	err := c.cc.Invoke(ctx, UserService_GetProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) UpdateProfile(ctx context.Context, in *UpdateProfileRequest, opts ...grpc.CallOption) (*UpdateProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateProfileResponse)
	err := c.cc.Invoke(ctx, UserService_UpdateProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) HasUsers(ctx context.Context, in *HasUsersRequest, opts ...grpc.CallOption) (*HasUsersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HasUsersResponse)
	err := c.cc.Invoke(ctx, UserService_HasUsers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) ResetAccountScope(ctx context.Context, in *ResetAccountScopeRequest, opts ...grpc.CallOption) (*ResetAccountScopeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResetAccountScopeResponse)
	err := c.cc.Invoke(ctx, UserService_ResetAccountScope_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetWechatIdentity(ctx context.Context, in *GetWechatIdentityRequest, opts ...grpc.CallOption) (*GetWechatIdentityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetWechatIdentityResponse)
	err := c.cc.Invoke(ctx, UserService_GetWechatIdentity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service.
// All implementations must embed UnimplementedUserServiceServer
// for forward compatibility.
type UserServiceServer interface {
	GetProfile(context.Context, *GetProfileRequest) (*GetProfileResponse, error)
	UpdateProfile(context.Context, *UpdateProfileRequest) (*UpdateProfileResponse, error)
	// Internal RPCs. Callers authenticate with the shared service token rather
	// than an end-user access token.
	HasUsers(context.Context, *HasUsersRequest) (*HasUsersResponse, error)
	ResetAccountScope(context.Context, *ResetAccountScopeRequest) (*ResetAccountScopeResponse, error)
	// GetWechatIdentity 把用户的微信 openid 交给内部调用方。order-service 发起微信小程序
	// 支付时需要它填 payer.openid（渠道必填），而 openid 是用户身份，只能服务间取，
	// 不能由客户端自称（见 order-service 的 dto.PayOrderRequest）。
	GetWechatIdentity(context.Context, *GetWechatIdentityRequest) (*GetWechatIdentityResponse, error)
	mustEmbedUnimplementedUserServiceServer()
}

// UnimplementedUserServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUserServiceServer struct{}

func (UnimplementedUserServiceServer) GetProfile(context.Context, *GetProfileRequest) (*GetProfileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProfile not implemented")
}
func (UnimplementedUserServiceServer) UpdateProfile(context.Context, *UpdateProfileRequest) (*UpdateProfileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateProfile not implemented")
}
func (UnimplementedUserServiceServer) HasUsers(context.Context, *HasUsersRequest) (*HasUsersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HasUsers not implemented")
}
func (UnimplementedUserServiceServer) ResetAccountScope(context.Context, *ResetAccountScopeRequest) (*ResetAccountScopeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResetAccountScope not implemented")
}
func (UnimplementedUserServiceServer) GetWechatIdentity(context.Context, *GetWechatIdentityRequest) (*GetWechatIdentityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetWechatIdentity not implemented")
}
func (UnimplementedUserServiceServer) mustEmbedUnimplementedUserServiceServer() {}
func (UnimplementedUserServiceServer) testEmbeddedByValue()                     {}

// UnsafeUserServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserServiceServer will
// result in compilation errors.
type UnsafeUserServiceServer interface {
	mustEmbedUnimplementedUserServiceServer()
}

func RegisterUserServiceServer(s grpc.ServiceRegistrar, srv UserServiceServer) {
	// If the following call panics, it indicates UnimplementedUserServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UserService_ServiceDesc, srv)
}

func _UserService_GetProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_GetProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetProfile(ctx, req.(*GetProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_UpdateProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).UpdateProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_UpdateProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).UpdateProfile(ctx, req.(*UpdateProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_HasUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HasUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).HasUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_HasUsers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).HasUsers(ctx, req.(*HasUsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_ResetAccountScope_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResetAccountScopeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).ResetAccountScope(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_ResetAccountScope_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).ResetAccountScope(ctx, req.(*ResetAccountScopeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetWechatIdentity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWechatIdentityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetWechatIdentity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_GetWechatIdentity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetWechatIdentity(ctx, req.(*GetWechatIdentityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UserService_ServiceDesc is the grpc.ServiceDesc for UserService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "panda.user.v1.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetProfile",
			Handler:    _UserService_GetProfile_Handler,
		},
		{
			MethodName: "UpdateProfile",
			Handler:    _UserService_UpdateProfile_Handler,
		},
		{
			MethodName: "HasUsers",
			Handler:    _UserService_HasUsers_Handler,
		},
		{
			MethodName: "ResetAccountScope",
			Handler:    _UserService_ResetAccountScope_Handler,
		},
		{
			MethodName: "GetWechatIdentity",
			Handler:    _UserService_GetWechatIdentity_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user/v1/user.proto",
}

const (
	AdminAccessService_GetAdminAccess_FullMethodName = "/panda.user.v1.AdminAccessService/GetAdminAccess"
)

// AdminAccessServiceClient is the client API for AdminAccessService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AdminAccessService answers only for the identity presented in metadata, so it
// is authenticated by an end-user access token instead of the service token.
type AdminAccessServiceClient interface {
	GetAdminAccess(ctx context.Context, in *GetAdminAccessRequest, opts ...grpc.CallOption) (*GetAdminAccessResponse, error)
}

type adminAccessServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAdminAccessServiceClient(cc grpc.ClientConnInterface) AdminAccessServiceClient {
	return &adminAccessServiceClient{cc}
}

func (c *adminAccessServiceClient) GetAdminAccess(ctx context.Context, in *GetAdminAccessRequest, opts ...grpc.CallOption) (*GetAdminAccessResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAdminAccessResponse)
	err := c.cc.Invoke(ctx, AdminAccessService_GetAdminAccess_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdminAccessServiceServer is the server API for AdminAccessService service.
// All implementations must embed UnimplementedAdminAccessServiceServer
// for forward compatibility.
//
// AdminAccessService answers only for the identity presented in metadata, so it
// is authenticated by an end-user access token instead of the service token.
type AdminAccessServiceServer interface {
	GetAdminAccess(context.Context, *GetAdminAccessRequest) (*GetAdminAccessResponse, error)
	mustEmbedUnimplementedAdminAccessServiceServer()
}

// UnimplementedAdminAccessServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAdminAccessServiceServer struct{}

func (UnimplementedAdminAccessServiceServer) GetAdminAccess(context.Context, *GetAdminAccessRequest) (*GetAdminAccessResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAdminAccess not implemented")
}
func (UnimplementedAdminAccessServiceServer) mustEmbedUnimplementedAdminAccessServiceServer() {}
func (UnimplementedAdminAccessServiceServer) testEmbeddedByValue()                            {}

// UnsafeAdminAccessServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AdminAccessServiceServer will
// result in compilation errors.
type UnsafeAdminAccessServiceServer interface {
	mustEmbedUnimplementedAdminAccessServiceServer()
}

func RegisterAdminAccessServiceServer(s grpc.ServiceRegistrar, srv AdminAccessServiceServer) {
	// If the following call panics, it indicates UnimplementedAdminAccessServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AdminAccessService_ServiceDesc, srv)
}

func _AdminAccessService_GetAdminAccess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAdminAccessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminAccessServiceServer).GetAdminAccess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminAccessService_GetAdminAccess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminAccessServiceServer).GetAdminAccess(ctx, req.(*GetAdminAccessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AdminAccessService_ServiceDesc is the grpc.ServiceDesc for AdminAccessService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AdminAccessService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "panda.user.v1.AdminAccessService",
	HandlerType: (*AdminAccessServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAdminAccess",
			Handler:    _AdminAccessService_GetAdminAccess_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user/v1/user.proto",
}

const (
	MerchantAccessService_GetMerchantAccess_FullMethodName = "/panda.user.v1.MerchantAccessService/GetMerchantAccess"
)

// MerchantAccessServiceClient is the client API for MerchantAccessService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// MerchantAccessService answers only for the identity presented in metadata, so
// it is authenticated by an end-user access token instead of the service token.
type MerchantAccessServiceClient interface {
	GetMerchantAccess(ctx context.Context, in *GetMerchantAccessRequest, opts ...grpc.CallOption) (*GetMerchantAccessResponse, error)
}

type merchantAccessServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMerchantAccessServiceClient(cc grpc.ClientConnInterface) MerchantAccessServiceClient {
	return &merchantAccessServiceClient{cc}
}

func (c *merchantAccessServiceClient) GetMerchantAccess(ctx context.Context, in *GetMerchantAccessRequest, opts ...grpc.CallOption) (*GetMerchantAccessResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMerchantAccessResponse)
	err := c.cc.Invoke(ctx, MerchantAccessService_GetMerchantAccess_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MerchantAccessServiceServer is the server API for MerchantAccessService service.
// All implementations must embed UnimplementedMerchantAccessServiceServer
// for forward compatibility.
//
// MerchantAccessService answers only for the identity presented in metadata, so
// it is authenticated by an end-user access token instead of the service token.
type MerchantAccessServiceServer interface {
	GetMerchantAccess(context.Context, *GetMerchantAccessRequest) (*GetMerchantAccessResponse, error)
	mustEmbedUnimplementedMerchantAccessServiceServer()
}

// UnimplementedMerchantAccessServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMerchantAccessServiceServer struct{}

func (UnimplementedMerchantAccessServiceServer) GetMerchantAccess(context.Context, *GetMerchantAccessRequest) (*GetMerchantAccessResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMerchantAccess not implemented")
}
func (UnimplementedMerchantAccessServiceServer) mustEmbedUnimplementedMerchantAccessServiceServer() {}
func (UnimplementedMerchantAccessServiceServer) testEmbeddedByValue()                               {}

// UnsafeMerchantAccessServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MerchantAccessServiceServer will
// result in compilation errors.
type UnsafeMerchantAccessServiceServer interface {
	mustEmbedUnimplementedMerchantAccessServiceServer()
}

func RegisterMerchantAccessServiceServer(s grpc.ServiceRegistrar, srv MerchantAccessServiceServer) {
	// If the following call panics, it indicates UnimplementedMerchantAccessServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MerchantAccessService_ServiceDesc, srv)
}

func _MerchantAccessService_GetMerchantAccess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMerchantAccessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MerchantAccessServiceServer).GetMerchantAccess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MerchantAccessService_GetMerchantAccess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MerchantAccessServiceServer).GetMerchantAccess(ctx, req.(*GetMerchantAccessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MerchantAccessService_ServiceDesc is the grpc.ServiceDesc for MerchantAccessService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MerchantAccessService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "panda.user.v1.MerchantAccessService",
	HandlerType: (*MerchantAccessServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMerchantAccess",
			Handler:    _MerchantAccessService_GetMerchantAccess_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user/v1/user.proto",
}
