// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: settlement/v1/settlement.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_settlement_v1_settlement_proto protoreflect.FileDescriptor

const file_settlement_v1_settlement_proto_rawDesc = "" +
	"\n" +
	"\x1esettlement/v1/settlement.proto\x12\x13panda.settlement.v12\x13\n" +
	"\x11SettlementServiceB=Z;github.com/panda-dev/panda-v2/contracts/proto/settlement/v1b\x06proto3"

var file_settlement_v1_settlement_proto_goTypes = []any{}
var file_settlement_v1_settlement_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_settlement_v1_settlement_proto_init() }
func file_settlement_v1_settlement_proto_init() {
	if File_settlement_v1_settlement_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_settlement_v1_settlement_proto_rawDesc), len(file_settlement_v1_settlement_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_settlement_v1_settlement_proto_goTypes,
		DependencyIndexes: file_settlement_v1_settlement_proto_depIdxs,
	}.Build()
	File_settlement_v1_settlement_proto = out.File
	file_settlement_v1_settlement_proto_goTypes = nil
	file_settlement_v1_settlement_proto_depIdxs = nil
}
