package runtime

import (
	"context"
	"net/http"

	"github.com/go-kratos/kratos/v2/errors"
	"github.com/go-kratos/kratos/v2/middleware"
	khttp "github.com/go-kratos/kratos/v2/transport/http"
	khttpstatus "github.com/go-kratos/kratos/v2/transport/http/status"
	"github.com/panda-dev/panda-v2/backend/platform/api"
)

// ErrHandlerPanic 是 recovery 中间件把 panic 翻成的错误值。它的用处只有一个：
// 让下面这层包装认得出「刚才那次是 panic」，见 HandleFunc 里的收尾。
//
// 用 kratos 的错误值而不是一个普通 error：同一个中间件也挂在 gRPC server 上（见
// platform/server 的 serverMiddleware），那边拿到的就是它。非 kratos 错误在那条路上
// 一律变成 Unknown(2)，而这是一次服务端崩溃，该报 Internal(13)。
//
// 消息里不带 panic 的值：它会原样成为回给调用方的状态消息，而 panic 的值常常是
// 被处理的数据本身（比如一句 SQL 错误）。现场在日志里，不在响应里。
var ErrHandlerPanic = errors.InternalServer(api.CodeInternal, "handler panicked")

// HTTPRouter is the registrar the HTTPRoutes hook receives. It registers routes
// on the underlying kratos server with the runtime's instrumentation wrapped
// around every handler.
//
// It exists because khttp.Middleware is not enough here. Kratos only consults its
// HTTP server middleware matcher from handlers generated by protoc-gen-go-http,
// which call ctx.Middleware(...) themselves; every route in this repository is a
// plain Server.HandleFunc, so nothing ever asks the matcher for them and the
// middleware is a silent no-op. Wrapping at registration time is the one place
// that covers all of them.
//
// Wrapping there is safe: kratos' mux filter has already installed the transport
// on the request context by the time a handler runs, and that is where the
// tracing and metrics middlewares read the operation, method and path template
// from.
type HTTPRouter struct {
	*khttp.Server
	middlewares []middleware.Middleware
}

// NewHTTPRouter wraps a kratos HTTP server for instrumented route registration.
func NewHTTPRouter(s *khttp.Server, middlewares ...middleware.Middleware) *HTTPRouter {
	return &HTTPRouter{Server: s, middlewares: middlewares}
}

// HandleFunc registers h with the instrumentation around it. The server's other
// registration methods are promoted unchanged.
func (r *HTTPRouter) HandleFunc(path string, h http.HandlerFunc) {
	r.Server.HandleFunc(path, func(w http.ResponseWriter, req *http.Request) {
		recorder := &statusRecorder{ResponseWriter: w, status: http.StatusOK}
		chain := middleware.Chain(r.middlewares...)
		handler := func(ctx context.Context, _ any) (any, error) {
			h(recorder, req.WithContext(ctx))
			// A plain http.HandlerFunc has no error to report, so on its own the
			// request metrics would label every response OK — 4xx and 5xx included.
			// Reconstruct the status as an error purely so the chain can read it;
			// the response is already written and the returned error is dropped.
			if recorder.status >= http.StatusBadRequest {
				return nil, errors.New(int(khttpstatus.ToGRPCCode(recorder.status)), http.StatusText(recorder.status), "")
			}
			return nil, nil
		}
		_, err := chain(handler)(req.Context(), req)
		// panic 只能在这里收尾。中间件把 panic 吃掉、把错误交回来，而这层包装是唯一
		// 还握着响应写入器的地方：不管它，net/http 会按「处理器正常返回」发一个**空
		// 200**——调用方看到的是成功。那比崩溃难查得多。
		//
		// 上面那条重建出来的错误不会误伤：状态码小于 400 时它是 nil；大于等于 400 时
		// 处理器一定已经写过响应头，下面的 wrote 判据把它挡在外面。
		if errors.Is(err, ErrHandlerPanic) && !recorder.wrote {
			api.Error(recorder, http.StatusInternalServerError, api.CodeInternal, "internal server error")
		}
	})
}

// statusRecorder remembers the status the handler wrote. WriteHeader counts once
// — a second call is a no-op for the recorder exactly as it is for net/http —
// and a bare Write implies 200, which is the value it is initialized with.
type statusRecorder struct {
	http.ResponseWriter
	status int
	wrote  bool
}

func (s *statusRecorder) WriteHeader(status int) {
	if !s.wrote {
		s.status = status
		s.wrote = true
	}
	s.ResponseWriter.WriteHeader(status)
}

func (s *statusRecorder) Write(b []byte) (int, error) {
	s.wrote = true
	return s.ResponseWriter.Write(b)
}
