package runtime

import (
	"context"
	"net/http"

	"github.com/go-kratos/kratos/v2/errors"
	"github.com/go-kratos/kratos/v2/middleware"
	khttp "github.com/go-kratos/kratos/v2/transport/http"
	khttpstatus "github.com/go-kratos/kratos/v2/transport/http/status"
)

// HTTPRouter is the registrar the HTTPRoutes hook receives. It registers routes
// on the underlying kratos server with the runtime's instrumentation wrapped
// around every handler.
//
// It exists because khttp.Middleware is not enough here. Kratos only consults its
// HTTP server middleware matcher from handlers generated by protoc-gen-go-http,
// which call ctx.Middleware(...) themselves; every route in this repository is a
// plain Server.HandleFunc, so nothing ever asks the matcher for them and the
// middleware is a silent no-op. Wrapping at registration time is the one place
// that covers all of them.
//
// Wrapping there is safe: kratos' mux filter has already installed the transport
// on the request context by the time a handler runs, and that is where the
// tracing and metrics middlewares read the operation, method and path template
// from.
type HTTPRouter struct {
	*khttp.Server
	middlewares []middleware.Middleware
}

// NewHTTPRouter wraps a kratos HTTP server for instrumented route registration.
func NewHTTPRouter(s *khttp.Server, middlewares ...middleware.Middleware) *HTTPRouter {
	return &HTTPRouter{Server: s, middlewares: middlewares}
}

// HandleFunc registers h with the instrumentation around it. The server's other
// registration methods are promoted unchanged.
func (r *HTTPRouter) HandleFunc(path string, h http.HandlerFunc) {
	r.Server.HandleFunc(path, func(w http.ResponseWriter, req *http.Request) {
		recorder := &statusRecorder{ResponseWriter: w, status: http.StatusOK}
		chain := middleware.Chain(r.middlewares...)
		handler := func(ctx context.Context, _ any) (any, error) {
			h(recorder, req.WithContext(ctx))
			// A plain http.HandlerFunc has no error to report, so on its own the
			// request metrics would label every response OK — 4xx and 5xx included.
			// Reconstruct the status as an error purely so the chain can read it;
			// the response is already written and the returned error is dropped.
			if recorder.status >= http.StatusBadRequest {
				return nil, errors.New(int(khttpstatus.ToGRPCCode(recorder.status)), http.StatusText(recorder.status), "")
			}
			return nil, nil
		}
		_, _ = chain(handler)(req.Context(), req)
	})
}

// statusRecorder remembers the status the handler wrote. WriteHeader counts once
// — a second call is a no-op for the recorder exactly as it is for net/http —
// and a bare Write implies 200, which is the value it is initialized with.
type statusRecorder struct {
	http.ResponseWriter
	status int
	wrote  bool
}

func (s *statusRecorder) WriteHeader(status int) {
	if !s.wrote {
		s.status = status
		s.wrote = true
	}
	s.ResponseWriter.WriteHeader(status)
}

func (s *statusRecorder) Write(b []byte) (int, error) {
	s.wrote = true
	return s.ResponseWriter.Write(b)
}
