// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: lottery/v1/lottery.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_lottery_v1_lottery_proto protoreflect.FileDescriptor

const file_lottery_v1_lottery_proto_rawDesc = "" +
	"\n" +
	"\x18lottery/v1/lottery.proto\x12\x10panda.lottery.v12\x10\n" +
	"\x0eLotteryServiceB:Z8github.com/panda-dev/panda-v2/contracts/proto/lottery/v1b\x06proto3"

var file_lottery_v1_lottery_proto_goTypes = []any{}
var file_lottery_v1_lottery_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_lottery_v1_lottery_proto_init() }
func file_lottery_v1_lottery_proto_init() {
	if File_lottery_v1_lottery_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_lottery_v1_lottery_proto_rawDesc), len(file_lottery_v1_lottery_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_lottery_v1_lottery_proto_goTypes,
		DependencyIndexes: file_lottery_v1_lottery_proto_depIdxs,
	}.Build()
	File_lottery_v1_lottery_proto = out.File
	file_lottery_v1_lottery_proto_goTypes = nil
	file_lottery_v1_lottery_proto_depIdxs = nil
}
