// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: account/v1/coffee_bean.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CoffeeBeanService_GetCoffeeBeanBalance_FullMethodName   = "/panda.account.v1.CoffeeBeanService/GetCoffeeBeanBalance"
	CoffeeBeanService_DeductCoffeeBeans_FullMethodName      = "/panda.account.v1.CoffeeBeanService/DeductCoffeeBeans"
	CoffeeBeanService_ReverseCoffeeBeanEntry_FullMethodName = "/panda.account.v1.CoffeeBeanService/ReverseCoffeeBeanEntry"
)

// CoffeeBeanServiceClient is the client API for CoffeeBeanService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 咖啡豆账户的内部契约——方案 5.6 的 account-service 里，咖啡豆那一半（同目录的
// fortune_card.proto 是另一半：福卡。两半同形，差别在币种与词表）。
//
// ⚠️ 同目录的 account.proto 是**登录账号**的草稿，与本文件无关，理由见 fortune_card.proto 的文件头。
//
// 调用方都是**服务**，不是客户端：纯豆出资（payment-service）扣减、退款冲正（本服务的
// order.after_sale.reviewed 消费者）。小程序与后台读余额、流水走 HTTP
// （`/v1/miniapp/coffee-beans`、`/v1/admin/coffee-beans/*`），不走这里。
//
// 金额一律是**分**（整数，无小数）——与 orders.payable_amount 同一个单位。这与福卡那边
// 「金额是张数」不是笔误：福卡的币种是张，豆的币种是分。
//
// 这一半**没有**后台调整、也**没有**冻结：
//   - 人工调整是真人在后台点的，走 HTTP（POST /v1/admin/coffee-beans/{userId}/adjustments），
//     那条路上有权限码与审计；服务令牌面不该有一条能凭空造币的 RPC。
//   - 豆在支付时就已经扣走，退款窗口里没有「冻着但还在」的东西，所以没有 Freeze/Release。
//     只有两个方向：扣走、还回来。
type CoffeeBeanServiceClient interface {
	// 读一个用户的豆余额（单位分）。
	//
	// 支付在扣减之前先看一眼，好在余额不够时直接给出一句「咖啡豆余额不足」，而不是拿一次
	// 失败去说同一件事。没有账户行就是 0——账户行是第一次调整或第一次扣减时懒创建的。
	GetCoffeeBeanBalance(ctx context.Context, in *GetCoffeeBeanBalanceRequest, opts ...grpc.CallOption) (*GetCoffeeBeanBalanceResponse, error)
	// 扣减咖啡豆：一张订单用豆全额付掉了（payment-service 的 action=account 出资）。
	//
	// 入参给的是**订单**（order_id / order_no）而不是随调用方挑的 reference_*：幂等键由
	// order_id 派生（`order:{orderId}`），退款冲正也要按它反查那笔扣减。让调用方自由填
	// reference 的话，同一个订单重试两次就可能落在两个键上，扣两次。
	//
	// 余额不足是本服务**认识**的业务结果，回 FailedPrecondition：那是「用户没钱」，不是
	// 「服务坏了」——调用方应当把它翻成一次发起即失败的支付结果（客户端可以换方式重试），
	// 而不是当成故障去重试或告警。
	DeductCoffeeBeans(ctx context.Context, in *DeductCoffeeBeansRequest, opts ...grpc.CallOption) (*DeductCoffeeBeansResponse, error)
	// 把一单扣掉的豆还回去（退款冲正，售后审核通过时由本服务自己发起）。
	//
	// 入参给订单与金额，不给流水 ID：调用方（事件消费者）手里只有订单，让账户域自己去反查
	// 那笔扣减，比让订单域把账变 ID 塞进事件载荷少一层耦合。
	//
	// ⚠️ 与福卡那面的冲正不同，这个方法是**幂等且可能什么都不做**的：那笔订单不是用豆付的
	// （绝大多数订单是渠道支付），就返回 reversed=false 且不报错；同一条售后重投由
	// `after_sale:{afterSaleNo}` 的唯一索引挡住，也不会冲第二次。把它做成错误会让一条完全
	// 正常的事件一路重试到死信。
	ReverseCoffeeBeanEntry(ctx context.Context, in *ReverseCoffeeBeanEntryRequest, opts ...grpc.CallOption) (*ReverseCoffeeBeanEntryResponse, error)
}

type coffeeBeanServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCoffeeBeanServiceClient(cc grpc.ClientConnInterface) CoffeeBeanServiceClient {
	return &coffeeBeanServiceClient{cc}
}

func (c *coffeeBeanServiceClient) GetCoffeeBeanBalance(ctx context.Context, in *GetCoffeeBeanBalanceRequest, opts ...grpc.CallOption) (*GetCoffeeBeanBalanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCoffeeBeanBalanceResponse)
	err := c.cc.Invoke(ctx, CoffeeBeanService_GetCoffeeBeanBalance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coffeeBeanServiceClient) DeductCoffeeBeans(ctx context.Context, in *DeductCoffeeBeansRequest, opts ...grpc.CallOption) (*DeductCoffeeBeansResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeductCoffeeBeansResponse)
	err := c.cc.Invoke(ctx, CoffeeBeanService_DeductCoffeeBeans_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coffeeBeanServiceClient) ReverseCoffeeBeanEntry(ctx context.Context, in *ReverseCoffeeBeanEntryRequest, opts ...grpc.CallOption) (*ReverseCoffeeBeanEntryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReverseCoffeeBeanEntryResponse)
	err := c.cc.Invoke(ctx, CoffeeBeanService_ReverseCoffeeBeanEntry_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CoffeeBeanServiceServer is the server API for CoffeeBeanService service.
// All implementations must embed UnimplementedCoffeeBeanServiceServer
// for forward compatibility.
//
// 咖啡豆账户的内部契约——方案 5.6 的 account-service 里，咖啡豆那一半（同目录的
// fortune_card.proto 是另一半：福卡。两半同形，差别在币种与词表）。
//
// ⚠️ 同目录的 account.proto 是**登录账号**的草稿，与本文件无关，理由见 fortune_card.proto 的文件头。
//
// 调用方都是**服务**，不是客户端：纯豆出资（payment-service）扣减、退款冲正（本服务的
// order.after_sale.reviewed 消费者）。小程序与后台读余额、流水走 HTTP
// （`/v1/miniapp/coffee-beans`、`/v1/admin/coffee-beans/*`），不走这里。
//
// 金额一律是**分**（整数，无小数）——与 orders.payable_amount 同一个单位。这与福卡那边
// 「金额是张数」不是笔误：福卡的币种是张，豆的币种是分。
//
// 这一半**没有**后台调整、也**没有**冻结：
//   - 人工调整是真人在后台点的，走 HTTP（POST /v1/admin/coffee-beans/{userId}/adjustments），
//     那条路上有权限码与审计；服务令牌面不该有一条能凭空造币的 RPC。
//   - 豆在支付时就已经扣走，退款窗口里没有「冻着但还在」的东西，所以没有 Freeze/Release。
//     只有两个方向：扣走、还回来。
type CoffeeBeanServiceServer interface {
	// 读一个用户的豆余额（单位分）。
	//
	// 支付在扣减之前先看一眼，好在余额不够时直接给出一句「咖啡豆余额不足」，而不是拿一次
	// 失败去说同一件事。没有账户行就是 0——账户行是第一次调整或第一次扣减时懒创建的。
	GetCoffeeBeanBalance(context.Context, *GetCoffeeBeanBalanceRequest) (*GetCoffeeBeanBalanceResponse, error)
	// 扣减咖啡豆：一张订单用豆全额付掉了（payment-service 的 action=account 出资）。
	//
	// 入参给的是**订单**（order_id / order_no）而不是随调用方挑的 reference_*：幂等键由
	// order_id 派生（`order:{orderId}`），退款冲正也要按它反查那笔扣减。让调用方自由填
	// reference 的话，同一个订单重试两次就可能落在两个键上，扣两次。
	//
	// 余额不足是本服务**认识**的业务结果，回 FailedPrecondition：那是「用户没钱」，不是
	// 「服务坏了」——调用方应当把它翻成一次发起即失败的支付结果（客户端可以换方式重试），
	// 而不是当成故障去重试或告警。
	DeductCoffeeBeans(context.Context, *DeductCoffeeBeansRequest) (*DeductCoffeeBeansResponse, error)
	// 把一单扣掉的豆还回去（退款冲正，售后审核通过时由本服务自己发起）。
	//
	// 入参给订单与金额，不给流水 ID：调用方（事件消费者）手里只有订单，让账户域自己去反查
	// 那笔扣减，比让订单域把账变 ID 塞进事件载荷少一层耦合。
	//
	// ⚠️ 与福卡那面的冲正不同，这个方法是**幂等且可能什么都不做**的：那笔订单不是用豆付的
	// （绝大多数订单是渠道支付），就返回 reversed=false 且不报错；同一条售后重投由
	// `after_sale:{afterSaleNo}` 的唯一索引挡住，也不会冲第二次。把它做成错误会让一条完全
	// 正常的事件一路重试到死信。
	ReverseCoffeeBeanEntry(context.Context, *ReverseCoffeeBeanEntryRequest) (*ReverseCoffeeBeanEntryResponse, error)
	mustEmbedUnimplementedCoffeeBeanServiceServer()
}

// UnimplementedCoffeeBeanServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCoffeeBeanServiceServer struct{}

func (UnimplementedCoffeeBeanServiceServer) GetCoffeeBeanBalance(context.Context, *GetCoffeeBeanBalanceRequest) (*GetCoffeeBeanBalanceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCoffeeBeanBalance not implemented")
}
func (UnimplementedCoffeeBeanServiceServer) DeductCoffeeBeans(context.Context, *DeductCoffeeBeansRequest) (*DeductCoffeeBeansResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeductCoffeeBeans not implemented")
}
func (UnimplementedCoffeeBeanServiceServer) ReverseCoffeeBeanEntry(context.Context, *ReverseCoffeeBeanEntryRequest) (*ReverseCoffeeBeanEntryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReverseCoffeeBeanEntry not implemented")
}
func (UnimplementedCoffeeBeanServiceServer) mustEmbedUnimplementedCoffeeBeanServiceServer() {}
func (UnimplementedCoffeeBeanServiceServer) testEmbeddedByValue()                           {}

// UnsafeCoffeeBeanServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CoffeeBeanServiceServer will
// result in compilation errors.
type UnsafeCoffeeBeanServiceServer interface {
	mustEmbedUnimplementedCoffeeBeanServiceServer()
}

func RegisterCoffeeBeanServiceServer(s grpc.ServiceRegistrar, srv CoffeeBeanServiceServer) {
	// If the following call panics, it indicates UnimplementedCoffeeBeanServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CoffeeBeanService_ServiceDesc, srv)
}

func _CoffeeBeanService_GetCoffeeBeanBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCoffeeBeanBalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoffeeBeanServiceServer).GetCoffeeBeanBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoffeeBeanService_GetCoffeeBeanBalance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoffeeBeanServiceServer).GetCoffeeBeanBalance(ctx, req.(*GetCoffeeBeanBalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoffeeBeanService_DeductCoffeeBeans_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeductCoffeeBeansRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoffeeBeanServiceServer).DeductCoffeeBeans(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoffeeBeanService_DeductCoffeeBeans_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoffeeBeanServiceServer).DeductCoffeeBeans(ctx, req.(*DeductCoffeeBeansRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoffeeBeanService_ReverseCoffeeBeanEntry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReverseCoffeeBeanEntryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoffeeBeanServiceServer).ReverseCoffeeBeanEntry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoffeeBeanService_ReverseCoffeeBeanEntry_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoffeeBeanServiceServer).ReverseCoffeeBeanEntry(ctx, req.(*ReverseCoffeeBeanEntryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CoffeeBeanService_ServiceDesc is the grpc.ServiceDesc for CoffeeBeanService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CoffeeBeanService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "panda.account.v1.CoffeeBeanService",
	HandlerType: (*CoffeeBeanServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCoffeeBeanBalance",
			Handler:    _CoffeeBeanService_GetCoffeeBeanBalance_Handler,
		},
		{
			MethodName: "DeductCoffeeBeans",
			Handler:    _CoffeeBeanService_DeductCoffeeBeans_Handler,
		},
		{
			MethodName: "ReverseCoffeeBeanEntry",
			Handler:    _CoffeeBeanService_ReverseCoffeeBeanEntry_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "account/v1/coffee_bean.proto",
}
