// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: account/v1/coffee_bean.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetCoffeeBeanBalanceRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 小程序用户 ID，值引用（身份服务的用户）。本服务不持有用户资料。
	UserId        string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCoffeeBeanBalanceRequest) Reset() {
	*x = GetCoffeeBeanBalanceRequest{}
	mi := &file_account_v1_coffee_bean_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCoffeeBeanBalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCoffeeBeanBalanceRequest) ProtoMessage() {}

func (x *GetCoffeeBeanBalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_account_v1_coffee_bean_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCoffeeBeanBalanceRequest.ProtoReflect.Descriptor instead.
func (*GetCoffeeBeanBalanceRequest) Descriptor() ([]byte, []int) {
	return file_account_v1_coffee_bean_proto_rawDescGZIP(), []int{0}
}

func (x *GetCoffeeBeanBalanceRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetCoffeeBeanBalanceResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 余额，单位为分。
	Balance       int64 `protobuf:"varint,1,opt,name=balance,proto3" json:"balance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCoffeeBeanBalanceResponse) Reset() {
	*x = GetCoffeeBeanBalanceResponse{}
	mi := &file_account_v1_coffee_bean_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCoffeeBeanBalanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCoffeeBeanBalanceResponse) ProtoMessage() {}

func (x *GetCoffeeBeanBalanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_account_v1_coffee_bean_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCoffeeBeanBalanceResponse.ProtoReflect.Descriptor instead.
func (*GetCoffeeBeanBalanceResponse) Descriptor() ([]byte, []int) {
	return file_account_v1_coffee_bean_proto_rawDescGZIP(), []int{1}
}

func (x *GetCoffeeBeanBalanceResponse) GetBalance() int64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

type DeductCoffeeBeansRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	UserId string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// 订单 ID，必填、UUID。幂等键由它派生，所以它是业务字段不是备注。
	OrderId string `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	// 订单号，给人看的号，落进流水的 reference_no。
	OrderNo string `protobuf:"bytes,3,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	// 扣减金额，恒 > 0，单位为分。
	Amount int64 `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`
	// 流水上给用户看的文案，留空则用「咖啡豆支付」。
	Title         string `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`
	Remark        string `protobuf:"bytes,6,opt,name=remark,proto3" json:"remark,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeductCoffeeBeansRequest) Reset() {
	*x = DeductCoffeeBeansRequest{}
	mi := &file_account_v1_coffee_bean_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeductCoffeeBeansRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeductCoffeeBeansRequest) ProtoMessage() {}

func (x *DeductCoffeeBeansRequest) ProtoReflect() protoreflect.Message {
	mi := &file_account_v1_coffee_bean_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeductCoffeeBeansRequest.ProtoReflect.Descriptor instead.
func (*DeductCoffeeBeansRequest) Descriptor() ([]byte, []int) {
	return file_account_v1_coffee_bean_proto_rawDescGZIP(), []int{2}
}

func (x *DeductCoffeeBeansRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *DeductCoffeeBeansRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *DeductCoffeeBeansRequest) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *DeductCoffeeBeansRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *DeductCoffeeBeansRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *DeductCoffeeBeansRequest) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

type DeductCoffeeBeansResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 本次扣减后的余额，单位为分。重放时给的是**当时那笔**的 balance_after，不是此刻的余额。
	BalanceAfter int64 `protobuf:"varint,1,opt,name=balance_after,json=balanceAfter,proto3" json:"balance_after,omitempty"`
	// 这一笔流水的 ID。它会经 payment_fundings.account_entry_id 一路落到
	// order_payment_lines.account_entry_id，也是将来对账/反查那笔扣减的入口。
	EntryId string `protobuf:"bytes,2,opt,name=entry_id,json=entryId,proto3" json:"entry_id,omitempty"`
	// true = 这一笔之前就存在，本次没有新增行（重放）。
	Replayed      bool `protobuf:"varint,3,opt,name=replayed,proto3" json:"replayed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeductCoffeeBeansResponse) Reset() {
	*x = DeductCoffeeBeansResponse{}
	mi := &file_account_v1_coffee_bean_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeductCoffeeBeansResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeductCoffeeBeansResponse) ProtoMessage() {}

func (x *DeductCoffeeBeansResponse) ProtoReflect() protoreflect.Message {
	mi := &file_account_v1_coffee_bean_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeductCoffeeBeansResponse.ProtoReflect.Descriptor instead.
func (*DeductCoffeeBeansResponse) Descriptor() ([]byte, []int) {
	return file_account_v1_coffee_bean_proto_rawDescGZIP(), []int{3}
}

func (x *DeductCoffeeBeansResponse) GetBalanceAfter() int64 {
	if x != nil {
		return x.BalanceAfter
	}
	return 0
}

func (x *DeductCoffeeBeansResponse) GetEntryId() string {
	if x != nil {
		return x.EntryId
	}
	return ""
}

func (x *DeductCoffeeBeansResponse) GetReplayed() bool {
	if x != nil {
		return x.Replayed
	}
	return false
}

type ReverseCoffeeBeanEntryRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 要冲正的那张订单。本服务按 `order:{orderId}` 反查那笔扣减。
	OrderId string `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	// 售后单 ID，值引用，落进流水的 reference_id。
	AfterSaleId string `protobuf:"bytes,2,opt,name=after_sale_id,json=afterSaleId,proto3" json:"after_sale_id,omitempty"`
	// 售后单号。它是幂等键（`after_sale:{afterSaleNo}`），必填——没有它就没有「只冲一次」。
	AfterSaleNo string `protobuf:"bytes,3,opt,name=after_sale_no,json=afterSaleNo,proto3" json:"after_sale_no,omitempty"`
	// 本次要还回去的金额，恒 > 0，单位为分。允许小于那笔扣减：部分退款（先退加购行、再退
	// 整单）由调用方按退款范围给，本服务不整单照抄。
	Amount        int64  `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`
	Remark        string `protobuf:"bytes,5,opt,name=remark,proto3" json:"remark,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReverseCoffeeBeanEntryRequest) Reset() {
	*x = ReverseCoffeeBeanEntryRequest{}
	mi := &file_account_v1_coffee_bean_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReverseCoffeeBeanEntryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReverseCoffeeBeanEntryRequest) ProtoMessage() {}

func (x *ReverseCoffeeBeanEntryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_account_v1_coffee_bean_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReverseCoffeeBeanEntryRequest.ProtoReflect.Descriptor instead.
func (*ReverseCoffeeBeanEntryRequest) Descriptor() ([]byte, []int) {
	return file_account_v1_coffee_bean_proto_rawDescGZIP(), []int{4}
}

func (x *ReverseCoffeeBeanEntryRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *ReverseCoffeeBeanEntryRequest) GetAfterSaleId() string {
	if x != nil {
		return x.AfterSaleId
	}
	return ""
}

func (x *ReverseCoffeeBeanEntryRequest) GetAfterSaleNo() string {
	if x != nil {
		return x.AfterSaleNo
	}
	return ""
}

func (x *ReverseCoffeeBeanEntryRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *ReverseCoffeeBeanEntryRequest) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

type ReverseCoffeeBeanEntryResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// true = 本次真的新增了一笔冲正。
	//
	// false 有两种成因，且**调用方不需要分辨**：这张订单不是用豆付的（没有可冲的扣减），
	// 或者这条售后已经冲过了（重投）。两种情况下要做的都是同一件事：什么都不做。
	//
	// 不回冲正流水的 ID 与冲正后余额：今天唯一的调用方（本服务的售后事件消费者）两样都用
	// 不到，而「当时那笔的 balance_after」在这里只会被误当成当前余额。将来退款单那一轮要反查
	// 这笔冲正时，入口是 `after_sale:{afterSaleNo}` 的唯一索引，不是这个响应。
	Reversed      bool `protobuf:"varint,1,opt,name=reversed,proto3" json:"reversed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReverseCoffeeBeanEntryResponse) Reset() {
	*x = ReverseCoffeeBeanEntryResponse{}
	mi := &file_account_v1_coffee_bean_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReverseCoffeeBeanEntryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReverseCoffeeBeanEntryResponse) ProtoMessage() {}

func (x *ReverseCoffeeBeanEntryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_account_v1_coffee_bean_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReverseCoffeeBeanEntryResponse.ProtoReflect.Descriptor instead.
func (*ReverseCoffeeBeanEntryResponse) Descriptor() ([]byte, []int) {
	return file_account_v1_coffee_bean_proto_rawDescGZIP(), []int{5}
}

func (x *ReverseCoffeeBeanEntryResponse) GetReversed() bool {
	if x != nil {
		return x.Reversed
	}
	return false
}

var File_account_v1_coffee_bean_proto protoreflect.FileDescriptor

const file_account_v1_coffee_bean_proto_rawDesc = "" +
	"\n" +
	"\x1caccount/v1/coffee_bean.proto\x12\x10panda.account.v1\"6\n" +
	"\x1bGetCoffeeBeanBalanceRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"8\n" +
	"\x1cGetCoffeeBeanBalanceResponse\x12\x18\n" +
	"\abalance\x18\x01 \x01(\x03R\abalance\"\xaf\x01\n" +
	"\x18DeductCoffeeBeansRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\x12\x19\n" +
	"\border_no\x18\x03 \x01(\tR\aorderNo\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x03R\x06amount\x12\x14\n" +
	"\x05title\x18\x05 \x01(\tR\x05title\x12\x16\n" +
	"\x06remark\x18\x06 \x01(\tR\x06remark\"w\n" +
	"\x19DeductCoffeeBeansResponse\x12#\n" +
	"\rbalance_after\x18\x01 \x01(\x03R\fbalanceAfter\x12\x19\n" +
	"\bentry_id\x18\x02 \x01(\tR\aentryId\x12\x1a\n" +
	"\breplayed\x18\x03 \x01(\bR\breplayed\"\xb2\x01\n" +
	"\x1dReverseCoffeeBeanEntryRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\"\n" +
	"\rafter_sale_id\x18\x02 \x01(\tR\vafterSaleId\x12\"\n" +
	"\rafter_sale_no\x18\x03 \x01(\tR\vafterSaleNo\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x03R\x06amount\x12\x16\n" +
	"\x06remark\x18\x05 \x01(\tR\x06remark\"<\n" +
	"\x1eReverseCoffeeBeanEntryResponse\x12\x1a\n" +
	"\breversed\x18\x01 \x01(\bR\breversed2\xf5\x02\n" +
	"\x11CoffeeBeanService\x12u\n" +
	"\x14GetCoffeeBeanBalance\x12-.panda.account.v1.GetCoffeeBeanBalanceRequest\x1a..panda.account.v1.GetCoffeeBeanBalanceResponse\x12l\n" +
	"\x11DeductCoffeeBeans\x12*.panda.account.v1.DeductCoffeeBeansRequest\x1a+.panda.account.v1.DeductCoffeeBeansResponse\x12{\n" +
	"\x16ReverseCoffeeBeanEntry\x12/.panda.account.v1.ReverseCoffeeBeanEntryRequest\x1a0.panda.account.v1.ReverseCoffeeBeanEntryResponseB:Z8github.com/panda-dev/panda-v2/contracts/proto/account/v1b\x06proto3"

var (
	file_account_v1_coffee_bean_proto_rawDescOnce sync.Once
	file_account_v1_coffee_bean_proto_rawDescData []byte
)

func file_account_v1_coffee_bean_proto_rawDescGZIP() []byte {
	file_account_v1_coffee_bean_proto_rawDescOnce.Do(func() {
		file_account_v1_coffee_bean_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_account_v1_coffee_bean_proto_rawDesc), len(file_account_v1_coffee_bean_proto_rawDesc)))
	})
	return file_account_v1_coffee_bean_proto_rawDescData
}

var file_account_v1_coffee_bean_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_account_v1_coffee_bean_proto_goTypes = []any{
	(*GetCoffeeBeanBalanceRequest)(nil),    // 0: panda.account.v1.GetCoffeeBeanBalanceRequest
	(*GetCoffeeBeanBalanceResponse)(nil),   // 1: panda.account.v1.GetCoffeeBeanBalanceResponse
	(*DeductCoffeeBeansRequest)(nil),       // 2: panda.account.v1.DeductCoffeeBeansRequest
	(*DeductCoffeeBeansResponse)(nil),      // 3: panda.account.v1.DeductCoffeeBeansResponse
	(*ReverseCoffeeBeanEntryRequest)(nil),  // 4: panda.account.v1.ReverseCoffeeBeanEntryRequest
	(*ReverseCoffeeBeanEntryResponse)(nil), // 5: panda.account.v1.ReverseCoffeeBeanEntryResponse
}
var file_account_v1_coffee_bean_proto_depIdxs = []int32{
	0, // 0: panda.account.v1.CoffeeBeanService.GetCoffeeBeanBalance:input_type -> panda.account.v1.GetCoffeeBeanBalanceRequest
	2, // 1: panda.account.v1.CoffeeBeanService.DeductCoffeeBeans:input_type -> panda.account.v1.DeductCoffeeBeansRequest
	4, // 2: panda.account.v1.CoffeeBeanService.ReverseCoffeeBeanEntry:input_type -> panda.account.v1.ReverseCoffeeBeanEntryRequest
	1, // 3: panda.account.v1.CoffeeBeanService.GetCoffeeBeanBalance:output_type -> panda.account.v1.GetCoffeeBeanBalanceResponse
	3, // 4: panda.account.v1.CoffeeBeanService.DeductCoffeeBeans:output_type -> panda.account.v1.DeductCoffeeBeansResponse
	5, // 5: panda.account.v1.CoffeeBeanService.ReverseCoffeeBeanEntry:output_type -> panda.account.v1.ReverseCoffeeBeanEntryResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_account_v1_coffee_bean_proto_init() }
func file_account_v1_coffee_bean_proto_init() {
	if File_account_v1_coffee_bean_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_account_v1_coffee_bean_proto_rawDesc), len(file_account_v1_coffee_bean_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_account_v1_coffee_bean_proto_goTypes,
		DependencyIndexes: file_account_v1_coffee_bean_proto_depIdxs,
		MessageInfos:      file_account_v1_coffee_bean_proto_msgTypes,
	}.Build()
	File_account_v1_coffee_bean_proto = out.File
	file_account_v1_coffee_bean_proto_goTypes = nil
	file_account_v1_coffee_bean_proto_depIdxs = nil
}
