// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: account/v1/fortune_card.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetFortuneCardBalanceRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 小程序用户 ID，值引用（身份服务的用户）。本服务不持有用户资料。
	UserId        string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFortuneCardBalanceRequest) Reset() {
	*x = GetFortuneCardBalanceRequest{}
	mi := &file_account_v1_fortune_card_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFortuneCardBalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFortuneCardBalanceRequest) ProtoMessage() {}

func (x *GetFortuneCardBalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_account_v1_fortune_card_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFortuneCardBalanceRequest.ProtoReflect.Descriptor instead.
func (*GetFortuneCardBalanceRequest) Descriptor() ([]byte, []int) {
	return file_account_v1_fortune_card_proto_rawDescGZIP(), []int{0}
}

func (x *GetFortuneCardBalanceRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetFortuneCardBalanceResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 可用福卡张数。
	Balance       int64 `protobuf:"varint,1,opt,name=balance,proto3" json:"balance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFortuneCardBalanceResponse) Reset() {
	*x = GetFortuneCardBalanceResponse{}
	mi := &file_account_v1_fortune_card_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFortuneCardBalanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFortuneCardBalanceResponse) ProtoMessage() {}

func (x *GetFortuneCardBalanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_account_v1_fortune_card_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFortuneCardBalanceResponse.ProtoReflect.Descriptor instead.
func (*GetFortuneCardBalanceResponse) Descriptor() ([]byte, []int) {
	return file_account_v1_fortune_card_proto_rawDescGZIP(), []int{1}
}

func (x *GetFortuneCardBalanceResponse) GetBalance() int64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

type DeductFortuneCardsRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	UserId string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// 扣减张数，恒 > 0。
	Amount int64 `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	// 幂等号，由调用方给（抽奖侧就是参与记录的 ID）。
	RequestId string `protobuf:"bytes,3,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// 流水上给用户看的那一行文案，例如「参与抽奖」。
	Title string `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	// 起因对象，都是值引用：reference_type 是 draw / order / entry 之类，reference_id 是它的
	// ID，reference_no 是给人看的号（订单号）。本服务的流水上记「为什么余额变了」，
	// 与事件日志不是一回事。
	ReferenceType string `protobuf:"bytes,5,opt,name=reference_type,json=referenceType,proto3" json:"reference_type,omitempty"`
	ReferenceId   string `protobuf:"bytes,6,opt,name=reference_id,json=referenceId,proto3" json:"reference_id,omitempty"`
	ReferenceNo   string `protobuf:"bytes,7,opt,name=reference_no,json=referenceNo,proto3" json:"reference_no,omitempty"`
	Remark        string `protobuf:"bytes,8,opt,name=remark,proto3" json:"remark,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeductFortuneCardsRequest) Reset() {
	*x = DeductFortuneCardsRequest{}
	mi := &file_account_v1_fortune_card_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeductFortuneCardsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeductFortuneCardsRequest) ProtoMessage() {}

func (x *DeductFortuneCardsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_account_v1_fortune_card_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeductFortuneCardsRequest.ProtoReflect.Descriptor instead.
func (*DeductFortuneCardsRequest) Descriptor() ([]byte, []int) {
	return file_account_v1_fortune_card_proto_rawDescGZIP(), []int{2}
}

func (x *DeductFortuneCardsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *DeductFortuneCardsRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *DeductFortuneCardsRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *DeductFortuneCardsRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *DeductFortuneCardsRequest) GetReferenceType() string {
	if x != nil {
		return x.ReferenceType
	}
	return ""
}

func (x *DeductFortuneCardsRequest) GetReferenceId() string {
	if x != nil {
		return x.ReferenceId
	}
	return ""
}

func (x *DeductFortuneCardsRequest) GetReferenceNo() string {
	if x != nil {
		return x.ReferenceNo
	}
	return ""
}

func (x *DeductFortuneCardsRequest) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

type DeductFortuneCardsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 本次扣减后的余额。重放时给的是**当时那笔**的 balance_after，不是此刻的余额。
	BalanceAfter int64 `protobuf:"varint,1,opt,name=balance_after,json=balanceAfter,proto3" json:"balance_after,omitempty"`
	// 这一笔流水的 ID。退款追回时拿它去冲正。
	EntryId string `protobuf:"bytes,2,opt,name=entry_id,json=entryId,proto3" json:"entry_id,omitempty"`
	// true = 这一笔之前就存在，本次没有新增行（重放）。
	Replayed      bool `protobuf:"varint,3,opt,name=replayed,proto3" json:"replayed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeductFortuneCardsResponse) Reset() {
	*x = DeductFortuneCardsResponse{}
	mi := &file_account_v1_fortune_card_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeductFortuneCardsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeductFortuneCardsResponse) ProtoMessage() {}

func (x *DeductFortuneCardsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_account_v1_fortune_card_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeductFortuneCardsResponse.ProtoReflect.Descriptor instead.
func (*DeductFortuneCardsResponse) Descriptor() ([]byte, []int) {
	return file_account_v1_fortune_card_proto_rawDescGZIP(), []int{3}
}

func (x *DeductFortuneCardsResponse) GetBalanceAfter() int64 {
	if x != nil {
		return x.BalanceAfter
	}
	return 0
}

func (x *DeductFortuneCardsResponse) GetEntryId() string {
	if x != nil {
		return x.EntryId
	}
	return ""
}

func (x *DeductFortuneCardsResponse) GetReplayed() bool {
	if x != nil {
		return x.Replayed
	}
	return false
}

type ReverseFortuneCardEntryRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 要冲正的那笔流水 ID（fortune_card_entries.id）。
	EntryId string `protobuf:"bytes,1,opt,name=entry_id,json=entryId,proto3" json:"entry_id,omitempty"`
	// 冲正流水上的文案与备注，留空则用「冲正」。
	Title         string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Remark        string `protobuf:"bytes,3,opt,name=remark,proto3" json:"remark,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReverseFortuneCardEntryRequest) Reset() {
	*x = ReverseFortuneCardEntryRequest{}
	mi := &file_account_v1_fortune_card_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReverseFortuneCardEntryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReverseFortuneCardEntryRequest) ProtoMessage() {}

func (x *ReverseFortuneCardEntryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_account_v1_fortune_card_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReverseFortuneCardEntryRequest.ProtoReflect.Descriptor instead.
func (*ReverseFortuneCardEntryRequest) Descriptor() ([]byte, []int) {
	return file_account_v1_fortune_card_proto_rawDescGZIP(), []int{4}
}

func (x *ReverseFortuneCardEntryRequest) GetEntryId() string {
	if x != nil {
		return x.EntryId
	}
	return ""
}

func (x *ReverseFortuneCardEntryRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ReverseFortuneCardEntryRequest) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

type ReverseFortuneCardEntryResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 冲正流水的 ID（重放时是已有的那一笔）。
	EntryId string `protobuf:"bytes,1,opt,name=entry_id,json=entryId,proto3" json:"entry_id,omitempty"`
	// 冲正之后的余额。重放时给的是**当时那笔**的 balance_after。
	BalanceAfter int64 `protobuf:"varint,2,opt,name=balance_after,json=balanceAfter,proto3" json:"balance_after,omitempty"`
	// true = 这笔冲正之前就存在，本次没有新增行（重放）。
	Replayed      bool `protobuf:"varint,3,opt,name=replayed,proto3" json:"replayed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReverseFortuneCardEntryResponse) Reset() {
	*x = ReverseFortuneCardEntryResponse{}
	mi := &file_account_v1_fortune_card_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReverseFortuneCardEntryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReverseFortuneCardEntryResponse) ProtoMessage() {}

func (x *ReverseFortuneCardEntryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_account_v1_fortune_card_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReverseFortuneCardEntryResponse.ProtoReflect.Descriptor instead.
func (*ReverseFortuneCardEntryResponse) Descriptor() ([]byte, []int) {
	return file_account_v1_fortune_card_proto_rawDescGZIP(), []int{5}
}

func (x *ReverseFortuneCardEntryResponse) GetEntryId() string {
	if x != nil {
		return x.EntryId
	}
	return ""
}

func (x *ReverseFortuneCardEntryResponse) GetBalanceAfter() int64 {
	if x != nil {
		return x.BalanceAfter
	}
	return 0
}

func (x *ReverseFortuneCardEntryResponse) GetReplayed() bool {
	if x != nil {
		return x.Replayed
	}
	return false
}

var File_account_v1_fortune_card_proto protoreflect.FileDescriptor

const file_account_v1_fortune_card_proto_rawDesc = "" +
	"\n" +
	"\x1daccount/v1/fortune_card.proto\x12\x10panda.account.v1\"7\n" +
	"\x1cGetFortuneCardBalanceRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"9\n" +
	"\x1dGetFortuneCardBalanceResponse\x12\x18\n" +
	"\abalance\x18\x01 \x01(\x03R\abalance\"\x86\x02\n" +
	"\x19DeductFortuneCardsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x03R\x06amount\x12\x1d\n" +
	"\n" +
	"request_id\x18\x03 \x01(\tR\trequestId\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12%\n" +
	"\x0ereference_type\x18\x05 \x01(\tR\rreferenceType\x12!\n" +
	"\freference_id\x18\x06 \x01(\tR\vreferenceId\x12!\n" +
	"\freference_no\x18\a \x01(\tR\vreferenceNo\x12\x16\n" +
	"\x06remark\x18\b \x01(\tR\x06remark\"x\n" +
	"\x1aDeductFortuneCardsResponse\x12#\n" +
	"\rbalance_after\x18\x01 \x01(\x03R\fbalanceAfter\x12\x19\n" +
	"\bentry_id\x18\x02 \x01(\tR\aentryId\x12\x1a\n" +
	"\breplayed\x18\x03 \x01(\bR\breplayed\"i\n" +
	"\x1eReverseFortuneCardEntryRequest\x12\x19\n" +
	"\bentry_id\x18\x01 \x01(\tR\aentryId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x16\n" +
	"\x06remark\x18\x03 \x01(\tR\x06remark\"}\n" +
	"\x1fReverseFortuneCardEntryResponse\x12\x19\n" +
	"\bentry_id\x18\x01 \x01(\tR\aentryId\x12#\n" +
	"\rbalance_after\x18\x02 \x01(\x03R\fbalanceAfter\x12\x1a\n" +
	"\breplayed\x18\x03 \x01(\bR\breplayed2\xff\x02\n" +
	"\x12FortuneCardService\x12x\n" +
	"\x15GetFortuneCardBalance\x12..panda.account.v1.GetFortuneCardBalanceRequest\x1a/.panda.account.v1.GetFortuneCardBalanceResponse\x12o\n" +
	"\x12DeductFortuneCards\x12+.panda.account.v1.DeductFortuneCardsRequest\x1a,.panda.account.v1.DeductFortuneCardsResponse\x12~\n" +
	"\x17ReverseFortuneCardEntry\x120.panda.account.v1.ReverseFortuneCardEntryRequest\x1a1.panda.account.v1.ReverseFortuneCardEntryResponseB:Z8github.com/panda-dev/panda-v2/contracts/proto/account/v1b\x06proto3"

var (
	file_account_v1_fortune_card_proto_rawDescOnce sync.Once
	file_account_v1_fortune_card_proto_rawDescData []byte
)

func file_account_v1_fortune_card_proto_rawDescGZIP() []byte {
	file_account_v1_fortune_card_proto_rawDescOnce.Do(func() {
		file_account_v1_fortune_card_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_account_v1_fortune_card_proto_rawDesc), len(file_account_v1_fortune_card_proto_rawDesc)))
	})
	return file_account_v1_fortune_card_proto_rawDescData
}

var file_account_v1_fortune_card_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_account_v1_fortune_card_proto_goTypes = []any{
	(*GetFortuneCardBalanceRequest)(nil),    // 0: panda.account.v1.GetFortuneCardBalanceRequest
	(*GetFortuneCardBalanceResponse)(nil),   // 1: panda.account.v1.GetFortuneCardBalanceResponse
	(*DeductFortuneCardsRequest)(nil),       // 2: panda.account.v1.DeductFortuneCardsRequest
	(*DeductFortuneCardsResponse)(nil),      // 3: panda.account.v1.DeductFortuneCardsResponse
	(*ReverseFortuneCardEntryRequest)(nil),  // 4: panda.account.v1.ReverseFortuneCardEntryRequest
	(*ReverseFortuneCardEntryResponse)(nil), // 5: panda.account.v1.ReverseFortuneCardEntryResponse
}
var file_account_v1_fortune_card_proto_depIdxs = []int32{
	0, // 0: panda.account.v1.FortuneCardService.GetFortuneCardBalance:input_type -> panda.account.v1.GetFortuneCardBalanceRequest
	2, // 1: panda.account.v1.FortuneCardService.DeductFortuneCards:input_type -> panda.account.v1.DeductFortuneCardsRequest
	4, // 2: panda.account.v1.FortuneCardService.ReverseFortuneCardEntry:input_type -> panda.account.v1.ReverseFortuneCardEntryRequest
	1, // 3: panda.account.v1.FortuneCardService.GetFortuneCardBalance:output_type -> panda.account.v1.GetFortuneCardBalanceResponse
	3, // 4: panda.account.v1.FortuneCardService.DeductFortuneCards:output_type -> panda.account.v1.DeductFortuneCardsResponse
	5, // 5: panda.account.v1.FortuneCardService.ReverseFortuneCardEntry:output_type -> panda.account.v1.ReverseFortuneCardEntryResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_account_v1_fortune_card_proto_init() }
func file_account_v1_fortune_card_proto_init() {
	if File_account_v1_fortune_card_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_account_v1_fortune_card_proto_rawDesc), len(file_account_v1_fortune_card_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_account_v1_fortune_card_proto_goTypes,
		DependencyIndexes: file_account_v1_fortune_card_proto_depIdxs,
		MessageInfos:      file_account_v1_fortune_card_proto_msgTypes,
	}.Build()
	File_account_v1_fortune_card_proto = out.File
	file_account_v1_fortune_card_proto_goTypes = nil
	file_account_v1_fortune_card_proto_depIdxs = nil
}
