// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: account/v1/fortune_card.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FortuneCardService_GetFortuneCardBalance_FullMethodName    = "/panda.account.v1.FortuneCardService/GetFortuneCardBalance"
	FortuneCardService_DeductFortuneCards_FullMethodName       = "/panda.account.v1.FortuneCardService/DeductFortuneCards"
	FortuneCardService_ReverseFortuneCardEntry_FullMethodName  = "/panda.account.v1.FortuneCardService/ReverseFortuneCardEntry"
	FortuneCardService_PreviewFortuneCardFreeze_FullMethodName = "/panda.account.v1.FortuneCardService/PreviewFortuneCardFreeze"
)

// FortuneCardServiceClient is the client API for FortuneCardService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 福卡账户的内部契约——方案 5.6 的 account-service 里，福卡账户那一半。
//
// ⚠️ 同目录的 account.proto 是**登录账号**的草稿（ADMIN / MERCHANT 的 Login），全仓没有
// 任何地方 import 它，与本文件不是一回事：这里的「账户」是用户的资产账户，不是能登录后台的
// 账号。这个目录名两义是历史遗留，改它要动一堆 go_package，不在本轮。
//
// 调用方都是**服务**，不是客户端：抽奖（lottery-service）扣减、退款追回冲正，以及订单域在
// 受理退款申请前问一句「这单的卡还冻得上吗」。小程序与后台读余额、流水走 HTTP
// （`/v1/miniapp/fortune-cards`、`/v1/admin/fortune-cards/*`），不走这里。
//
// 金额一律是「张数」，整数，没有小数。
type FortuneCardServiceClient interface {
	// 读一个用户的福卡余额。
	//
	// 抽奖在扣减之前先看一眼，好在余额不够时给出一句「福卡余额不足」，而不是拿一次失败去
	// 说同一件事。没有账户行就是 0——账户行是第一次发放时懒创建的。
	GetFortuneCardBalance(ctx context.Context, in *GetFortuneCardBalanceRequest, opts ...grpc.CallOption) (*GetFortuneCardBalanceResponse, error)
	// 扣减福卡：用户每参与一次抽奖扣 1 张（张数由调用方给，本服务不持有抽奖规则）。
	//
	// request_id 是幂等号，调用方重试必须拿回同一笔而不是扣第二次，所以它进 entry_key
	// 唯一索引。余额不足是本服务**认识**的业务结果，回 FailedPrecondition；那是「用户没钱」，
	// 不是「服务坏了」，调用方应当把它翻译成给用户看的一句话。
	DeductFortuneCards(ctx context.Context, in *DeductFortuneCardsRequest, opts ...grpc.CallOption) (*DeductFortuneCardsResponse, error)
	// 冲正一笔已有的流水，把张数还回去（退款追回福卡）。
	//
	// 幂等键就从 entry_id 派生（`reverse:{entryId}`）：一笔流水只能被冲正一次，重放回放
	// 已经生成的那笔。冲正会把余额扣成负数时拒绝——「已经抽过奖的福卡追不回来」是业务规则，
	// 不是故障，所以是明确的错误消息，不是 500。
	ReverseFortuneCardEntry(ctx context.Context, in *ReverseFortuneCardEntryRequest, opts ...grpc.CallOption) (*ReverseFortuneCardEntryResponse, error)
	// 预览一次冻结：现在把这批发放冻起来，**冻得上几张**。只算不写。
	//
	// 存在的理由是一条业务规则：一单赠送的福卡一张都没被用过，才允许申请退款。判据只能是
	// 这个数——福卡的流水是一口**池子**（抽奖扣的那一笔只记 `draw:{requestId}`，从不指向
	// 它消耗的是哪一次发放），所以「这一单送的那几张还在不在」在库里没有直接答案，能算出来
	// 的只有「这批发放键上还挂着几张（没被冲正过的）」与「账户此刻还有多少可用」，取小的
	// 那个——正是 FreezeAfterSale 此刻会冻上的张数。预览与冻结必须用同一句 SQL，否则两个
	// 数会漂移，而这里的漂移直接变成「申请被拒了但其实冻得上」或者反过来。
	//
	// 订单域在**受理申请之前**问一次：冻不满就是不受理（回给用户一句人话），而不是像过去
	// 那样先受理、冻结时再悄悄钳住。这一问挡的是「用户早就把卡抽掉了」这个常态；申请与冻结
	// 之间那个毫秒级的窗口挡不住，也不该由它挡——冻结那一侧的钳制仍然是权威。
	PreviewFortuneCardFreeze(ctx context.Context, in *PreviewFortuneCardFreezeRequest, opts ...grpc.CallOption) (*PreviewFortuneCardFreezeResponse, error)
}

type fortuneCardServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFortuneCardServiceClient(cc grpc.ClientConnInterface) FortuneCardServiceClient {
	return &fortuneCardServiceClient{cc}
}

func (c *fortuneCardServiceClient) GetFortuneCardBalance(ctx context.Context, in *GetFortuneCardBalanceRequest, opts ...grpc.CallOption) (*GetFortuneCardBalanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFortuneCardBalanceResponse)
	err := c.cc.Invoke(ctx, FortuneCardService_GetFortuneCardBalance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fortuneCardServiceClient) DeductFortuneCards(ctx context.Context, in *DeductFortuneCardsRequest, opts ...grpc.CallOption) (*DeductFortuneCardsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeductFortuneCardsResponse)
	err := c.cc.Invoke(ctx, FortuneCardService_DeductFortuneCards_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fortuneCardServiceClient) ReverseFortuneCardEntry(ctx context.Context, in *ReverseFortuneCardEntryRequest, opts ...grpc.CallOption) (*ReverseFortuneCardEntryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReverseFortuneCardEntryResponse)
	err := c.cc.Invoke(ctx, FortuneCardService_ReverseFortuneCardEntry_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fortuneCardServiceClient) PreviewFortuneCardFreeze(ctx context.Context, in *PreviewFortuneCardFreezeRequest, opts ...grpc.CallOption) (*PreviewFortuneCardFreezeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PreviewFortuneCardFreezeResponse)
	err := c.cc.Invoke(ctx, FortuneCardService_PreviewFortuneCardFreeze_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FortuneCardServiceServer is the server API for FortuneCardService service.
// All implementations must embed UnimplementedFortuneCardServiceServer
// for forward compatibility.
//
// 福卡账户的内部契约——方案 5.6 的 account-service 里，福卡账户那一半。
//
// ⚠️ 同目录的 account.proto 是**登录账号**的草稿（ADMIN / MERCHANT 的 Login），全仓没有
// 任何地方 import 它，与本文件不是一回事：这里的「账户」是用户的资产账户，不是能登录后台的
// 账号。这个目录名两义是历史遗留，改它要动一堆 go_package，不在本轮。
//
// 调用方都是**服务**，不是客户端：抽奖（lottery-service）扣减、退款追回冲正，以及订单域在
// 受理退款申请前问一句「这单的卡还冻得上吗」。小程序与后台读余额、流水走 HTTP
// （`/v1/miniapp/fortune-cards`、`/v1/admin/fortune-cards/*`），不走这里。
//
// 金额一律是「张数」，整数，没有小数。
type FortuneCardServiceServer interface {
	// 读一个用户的福卡余额。
	//
	// 抽奖在扣减之前先看一眼，好在余额不够时给出一句「福卡余额不足」，而不是拿一次失败去
	// 说同一件事。没有账户行就是 0——账户行是第一次发放时懒创建的。
	GetFortuneCardBalance(context.Context, *GetFortuneCardBalanceRequest) (*GetFortuneCardBalanceResponse, error)
	// 扣减福卡：用户每参与一次抽奖扣 1 张（张数由调用方给，本服务不持有抽奖规则）。
	//
	// request_id 是幂等号，调用方重试必须拿回同一笔而不是扣第二次，所以它进 entry_key
	// 唯一索引。余额不足是本服务**认识**的业务结果，回 FailedPrecondition；那是「用户没钱」，
	// 不是「服务坏了」，调用方应当把它翻译成给用户看的一句话。
	DeductFortuneCards(context.Context, *DeductFortuneCardsRequest) (*DeductFortuneCardsResponse, error)
	// 冲正一笔已有的流水，把张数还回去（退款追回福卡）。
	//
	// 幂等键就从 entry_id 派生（`reverse:{entryId}`）：一笔流水只能被冲正一次，重放回放
	// 已经生成的那笔。冲正会把余额扣成负数时拒绝——「已经抽过奖的福卡追不回来」是业务规则，
	// 不是故障，所以是明确的错误消息，不是 500。
	ReverseFortuneCardEntry(context.Context, *ReverseFortuneCardEntryRequest) (*ReverseFortuneCardEntryResponse, error)
	// 预览一次冻结：现在把这批发放冻起来，**冻得上几张**。只算不写。
	//
	// 存在的理由是一条业务规则：一单赠送的福卡一张都没被用过，才允许申请退款。判据只能是
	// 这个数——福卡的流水是一口**池子**（抽奖扣的那一笔只记 `draw:{requestId}`，从不指向
	// 它消耗的是哪一次发放），所以「这一单送的那几张还在不在」在库里没有直接答案，能算出来
	// 的只有「这批发放键上还挂着几张（没被冲正过的）」与「账户此刻还有多少可用」，取小的
	// 那个——正是 FreezeAfterSale 此刻会冻上的张数。预览与冻结必须用同一句 SQL，否则两个
	// 数会漂移，而这里的漂移直接变成「申请被拒了但其实冻得上」或者反过来。
	//
	// 订单域在**受理申请之前**问一次：冻不满就是不受理（回给用户一句人话），而不是像过去
	// 那样先受理、冻结时再悄悄钳住。这一问挡的是「用户早就把卡抽掉了」这个常态；申请与冻结
	// 之间那个毫秒级的窗口挡不住，也不该由它挡——冻结那一侧的钳制仍然是权威。
	PreviewFortuneCardFreeze(context.Context, *PreviewFortuneCardFreezeRequest) (*PreviewFortuneCardFreezeResponse, error)
	mustEmbedUnimplementedFortuneCardServiceServer()
}

// UnimplementedFortuneCardServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFortuneCardServiceServer struct{}

func (UnimplementedFortuneCardServiceServer) GetFortuneCardBalance(context.Context, *GetFortuneCardBalanceRequest) (*GetFortuneCardBalanceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFortuneCardBalance not implemented")
}
func (UnimplementedFortuneCardServiceServer) DeductFortuneCards(context.Context, *DeductFortuneCardsRequest) (*DeductFortuneCardsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeductFortuneCards not implemented")
}
func (UnimplementedFortuneCardServiceServer) ReverseFortuneCardEntry(context.Context, *ReverseFortuneCardEntryRequest) (*ReverseFortuneCardEntryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReverseFortuneCardEntry not implemented")
}
func (UnimplementedFortuneCardServiceServer) PreviewFortuneCardFreeze(context.Context, *PreviewFortuneCardFreezeRequest) (*PreviewFortuneCardFreezeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PreviewFortuneCardFreeze not implemented")
}
func (UnimplementedFortuneCardServiceServer) mustEmbedUnimplementedFortuneCardServiceServer() {}
func (UnimplementedFortuneCardServiceServer) testEmbeddedByValue()                            {}

// UnsafeFortuneCardServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FortuneCardServiceServer will
// result in compilation errors.
type UnsafeFortuneCardServiceServer interface {
	mustEmbedUnimplementedFortuneCardServiceServer()
}

func RegisterFortuneCardServiceServer(s grpc.ServiceRegistrar, srv FortuneCardServiceServer) {
	// If the following call panics, it indicates UnimplementedFortuneCardServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FortuneCardService_ServiceDesc, srv)
}

func _FortuneCardService_GetFortuneCardBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFortuneCardBalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FortuneCardServiceServer).GetFortuneCardBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FortuneCardService_GetFortuneCardBalance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FortuneCardServiceServer).GetFortuneCardBalance(ctx, req.(*GetFortuneCardBalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FortuneCardService_DeductFortuneCards_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeductFortuneCardsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FortuneCardServiceServer).DeductFortuneCards(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FortuneCardService_DeductFortuneCards_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FortuneCardServiceServer).DeductFortuneCards(ctx, req.(*DeductFortuneCardsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FortuneCardService_ReverseFortuneCardEntry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReverseFortuneCardEntryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FortuneCardServiceServer).ReverseFortuneCardEntry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FortuneCardService_ReverseFortuneCardEntry_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FortuneCardServiceServer).ReverseFortuneCardEntry(ctx, req.(*ReverseFortuneCardEntryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FortuneCardService_PreviewFortuneCardFreeze_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PreviewFortuneCardFreezeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FortuneCardServiceServer).PreviewFortuneCardFreeze(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FortuneCardService_PreviewFortuneCardFreeze_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FortuneCardServiceServer).PreviewFortuneCardFreeze(ctx, req.(*PreviewFortuneCardFreezeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FortuneCardService_ServiceDesc is the grpc.ServiceDesc for FortuneCardService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FortuneCardService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "panda.account.v1.FortuneCardService",
	HandlerType: (*FortuneCardServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetFortuneCardBalance",
			Handler:    _FortuneCardService_GetFortuneCardBalance_Handler,
		},
		{
			MethodName: "DeductFortuneCards",
			Handler:    _FortuneCardService_DeductFortuneCards_Handler,
		},
		{
			MethodName: "ReverseFortuneCardEntry",
			Handler:    _FortuneCardService_ReverseFortuneCardEntry_Handler,
		},
		{
			MethodName: "PreviewFortuneCardFreeze",
			Handler:    _FortuneCardService_PreviewFortuneCardFreeze_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "account/v1/fortune_card.proto",
}
