receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch:

exporters:
  otlp/tempo:
    endpoint: ${TEMPO_ENDPOINT:-tempo:4317}
    tls:
      insecure: true
  prometheus:
    endpoint: ${PROMETHEUS_ENDPOINT:-0.0.0.0:8889}
  opensearch:
    http:
      endpoint: ${OPENSEARCH_ENDPOINT:-http://opensearch:9200}

service:
  pipelines:
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [opensearch]
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/tempo]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus]
