-- membership/002：会员表和关键字段中文注释

COMMENT ON TABLE membership_plans IS '会员套餐定义：连续包月与年度会员；权益只有会员价一项';
COMMENT ON COLUMN membership_plans.code IS '稳定的套餐编码（monthly_auto / annual），创建后不可修改';
COMMENT ON COLUMN membership_plans.description IS '套餐说明文案';
COMMENT ON COLUMN membership_plans.benefits IS '权益文案列表（JSON 数组），仅用于展示，不参与权益判定';
COMMENT ON COLUMN membership_plans.price_cents IS '套餐售价，单位为分';
COMMENT ON COLUMN membership_plans.period IS '每期时长的单位：month=月度，year=年度；续期按日历加，不按天数加';
COMMENT ON COLUMN membership_plans.period_count IS '每期几个单位：连续包月与年度会员都是 1';
COMMENT ON COLUMN membership_plans.auto_renew IS '是否自动续费：TRUE=签署微信委托代扣并按期扣款';
COMMENT ON COLUMN membership_plans.wechat_plan_id IS '微信支付委托代扣的签约模板 ID（微信商户平台的 plan_id）；自动续费的套餐必填';
COMMENT ON COLUMN membership_plans.member_price_mode IS '会员价路径：auto=会员自动享，coupon=靠会员价体验券';
COMMENT ON COLUMN membership_plans.member_price_coupon_template_id IS 'coupon 模式发券用的券模板 ID（券类型 MEMBERSHIP_PRICE_EXPERIENCE）；仅作跨库值引用（券服务）';
COMMENT ON COLUMN membership_plans.member_price_coupons_per_period IS 'coupon 模式每期扣款成功后发放的券张数';
COMMENT ON COLUMN membership_plans.sort_order IS '展示排序，数值越小越靠前';
COMMENT ON COLUMN membership_plans.status IS '套餐状态：draft=草稿，active=在售，disabled=下架（不影响已购会员）';
COMMENT ON COLUMN membership_plans.legacy_id IS '老库会员等级 ID；仅迁移映射来的套餐有值';
COMMENT ON COLUMN membership_plans.created_by IS '创建人管理员 ID，仅作跨库值引用（身份库）';

COMMENT ON TABLE memberships IS '用户会员资格：一个用户一条，续费叠加有效期而不新增行';
COMMENT ON COLUMN memberships.user_id IS '小程序用户 ID；仅作跨库值引用';
COMMENT ON COLUMN memberships.legacy_id IS '老库 user_memberships ID；仅迁移过来的会员有值';
COMMENT ON COLUMN memberships.plan_id IS '当前套餐 ID，引用本库 membership_plans';
COMMENT ON COLUMN memberships.plan_code IS '成交时的套餐编码快照';
COMMENT ON COLUMN memberships.plan_name IS '成交时的套餐名称快照';
COMMENT ON COLUMN memberships.member_price_mode IS '会员价路径的成交快照：auto=自动享，coupon=靠会员价体验券';
COMMENT ON COLUMN memberships.member_price_coupon_template_id IS '发券券模板 ID 的成交快照；仅作跨库值引用';
COMMENT ON COLUMN memberships.member_price_coupons_per_period IS '每期发券张数的成交快照';
COMMENT ON COLUMN memberships.status IS '会员状态：active=生效，frozen=权益暂停，expired=已过期，revoked=已撤销';
COMMENT ON COLUMN memberships.start_at IS '会员生效时间';
COMMENT ON COLUMN memberships.expire_at IS '会员到期时间；续费在此之上叠加';
COMMENT ON COLUMN memberships.auto_renew IS '自动续费开关：用户可在小程序关闭或恢复';
COMMENT ON COLUMN memberships.auto_renew_off_at IS '用户最后一次关闭自动续费的时间；从未开启则为空';
COMMENT ON COLUMN memberships.renewal_count IS '累计成功续费次数';
COMMENT ON COLUMN memberships.last_renewed_at IS '最后一次续费成功时间';
COMMENT ON COLUMN memberships.frozen_at IS '权益暂停时间';
COMMENT ON COLUMN memberships.freeze_reason IS '权益暂停原因';
COMMENT ON COLUMN memberships.revoked_at IS '会员撤销时间';
COMMENT ON COLUMN memberships.revoke_reason IS '会员撤销原因';

COMMENT ON TABLE membership_subscriptions IS '连续包月的签约与扣款期次；代扣协议本体在支付服务';
COMMENT ON COLUMN membership_subscriptions.membership_id IS '所属会员资格 ID，引用本库 memberships';
COMMENT ON COLUMN membership_subscriptions.user_id IS '小程序用户 ID；仅作跨库值引用';
COMMENT ON COLUMN membership_subscriptions.plan_id IS '订阅的套餐 ID，引用本库 membership_plans';
COMMENT ON COLUMN membership_subscriptions.status IS '订阅状态：pending_sign=待签约，active=扣款中，suspended=连续失败已暂停，cancelled=已解约，expired=已到期不再续';
COMMENT ON COLUMN membership_subscriptions.agreement_id IS '支付服务的委托代扣协议 ID（payment_agreements.id）；仅作跨库值引用';
COMMENT ON COLUMN membership_subscriptions.contract_code IS '商户协议号，签约时由支付服务返回，用于向渠道对账';
COMMENT ON COLUMN membership_subscriptions.price_cents IS '每期扣款金额快照，单位为分；套餐调价不影响已签约用户';
COMMENT ON COLUMN membership_subscriptions.wechat_plan_id IS '签约模板 ID 快照，取值同套餐；已签协议挂在签约当时那个模板上';
COMMENT ON COLUMN membership_subscriptions.period IS '每期时长的单位快照：month=月度，year=年度';
COMMENT ON COLUMN membership_subscriptions.period_count IS '每期几个单位的快照';
COMMENT ON COLUMN membership_subscriptions.next_charge_at IS '下次应扣款时间；续费扫描按它取任务';
COMMENT ON COLUMN membership_subscriptions.last_charge_at IS '上次扣款时间';
COMMENT ON COLUMN membership_subscriptions.charge_count IS '累计成功扣款次数';
COMMENT ON COLUMN membership_subscriptions.failed_count IS '累计扣款失败次数';
COMMENT ON COLUMN membership_subscriptions.consecutive_failed_count IS '连续扣款失败次数；达到阈值转 suspended，成功一次即清零';
COMMENT ON COLUMN membership_subscriptions.suspended_at IS '因连续扣款失败暂停的时间';
COMMENT ON COLUMN membership_subscriptions.cancel_at IS '解约时间';
COMMENT ON COLUMN membership_subscriptions.cancel_reason IS '解约原因';
COMMENT ON COLUMN membership_subscriptions.cancelled_by IS '解约发起人 ID：用户或后台操作人';

COMMENT ON TABLE membership_changes IS '会员变更流水：只增不改不删，同时作为权益变更的幂等凭据';
COMMENT ON COLUMN membership_changes.membership_id IS '所属会员资格 ID，引用本库 memberships';
COMMENT ON COLUMN membership_changes.user_id IS '小程序用户 ID；仅作跨库值引用';
COMMENT ON COLUMN membership_changes.change_type IS '变更类型：activate=开通，renew=续费，expire=到期，freeze=暂停，unfreeze=恢复，auto_renew_on/off=自动续费开关，subscribe=签约，unsubscribe=解约，refund_adjust=退款调整，admin_adjust=后台调整，revoke=撤销';
COMMENT ON COLUMN membership_changes.from_status IS '变更前状态';
COMMENT ON COLUMN membership_changes.to_status IS '变更后状态';
COMMENT ON COLUMN membership_changes.from_expire_at IS '变更前到期时间';
COMMENT ON COLUMN membership_changes.to_expire_at IS '变更后到期时间';
COMMENT ON COLUMN membership_changes.plan_id IS '变更涉及的套餐 ID，引用本库 membership_plans';
COMMENT ON COLUMN membership_changes.order_id IS '触发本次变更的订单 ID；仅作跨库值引用';
COMMENT ON COLUMN membership_changes.operator_type IS '操作人类型：user=用户，admin=后台，system=系统，worker=后台任务';
COMMENT ON COLUMN membership_changes.operator_id IS '操作人 ID；系统与任务为空';
COMMENT ON COLUMN membership_changes.reason IS '变更原因（枚举化的短语）';
COMMENT ON COLUMN membership_changes.remark IS '补充说明';
COMMENT ON COLUMN membership_changes.metadata IS '变更的扩展明细，低频、不参与查询';
COMMENT ON COLUMN membership_changes.request_id IS '操作留痕串，与后台操作审计对得上';
COMMENT ON COLUMN membership_changes.occurred_at IS '业务发生时间';

COMMENT ON TABLE message_outbox IS '事务性发件箱：与业务行同事务写入，由 relay 投递到消息队列';
COMMENT ON COLUMN message_outbox.event_id IS '事件 ID，消费端幂等依据';
COMMENT ON COLUMN message_outbox.event_type IS '事件类型';
COMMENT ON COLUMN message_outbox.event_version IS '事件版本';
COMMENT ON COLUMN message_outbox.trace_id IS '链路追踪 ID';
COMMENT ON COLUMN message_outbox.payload IS '事件载荷';
COMMENT ON COLUMN message_outbox.attempts IS '已投递尝试次数';
COMMENT ON COLUMN message_outbox.next_attempt_at IS '下次投递时间，重试退避用';
COMMENT ON COLUMN message_outbox.published_at IS '投递成功时间；为空表示待投递';
COMMENT ON COLUMN message_outbox.lease_owner IS '投递租约持有者';
COMMENT ON COLUMN message_outbox.lease_token IS '投递租约令牌，防止过期持有者回写';
COMMENT ON COLUMN message_outbox.lease_until IS '消息处理租约截止时间';
COMMENT ON COLUMN message_outbox.last_error IS '最后一次投递失败原因';
COMMENT ON COLUMN message_outbox.created_at IS '事件写入时间';

COMMENT ON TABLE message_inbox IS '事务性收件箱：消费幂等，与业务更新同事务写入';
COMMENT ON COLUMN message_inbox.event_id IS '事件 ID，唯一约束即消费幂等';
COMMENT ON COLUMN message_inbox.claimed_at IS '认领时间';
COMMENT ON COLUMN message_inbox.lease_owner IS '消费租约持有者';
COMMENT ON COLUMN message_inbox.lease_token IS '消费租约令牌';
COMMENT ON COLUMN message_inbox.lease_until IS '消息消费租约截止时间';
COMMENT ON COLUMN message_inbox.completed_at IS '处理完成时间；为空表示仍在处理';
