ALTER TABLE users
    ADD COLUMN IF NOT EXISTS nickname TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS avatar_url TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS email TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS gender TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS birthday TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS occupation TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS hobbies TEXT[] NOT NULL DEFAULT '{}',
    ADD COLUMN IF NOT EXISTS region_code TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS region_name TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS status TEXT NOT NULL DEFAULT 'active',
    ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW();

UPDATE users SET updated_at = created_at WHERE updated_at IS NULL;
