-- 门店名不再落库：开通只存 location_id，显示时向商户域实时解析。
--
-- 001 里的 location_name 是「开通那一刻的门店名快照」，002 给它写的注释是「之后不订阅
-- 改名事件；列表页显示旧名字是已知代价」。这个代价最后撞上了一个更硬的约束：列表页按
-- **门店名**做模糊搜（`a.location_name ILIKE`），而名字一旦不落库，这个搜索就没法在 SQL
-- 里做；商户域的 gRPC 也没有「按名字查门店」的能力——ListStores 只收 merchant_id，
-- ResolveScopeNames 只收 id。于是「显示时实时查」和「按名字搜」两件事只能留一件。
--
-- 留的是实时查，换掉的是那个交互：筛选改成从门店下拉里选门店（传 location_id，走等值
-- 比较——这条筛选后端本来就有），名字只在显示时由 ResolveScopeNames 批量取一页回来。
-- 名字列因此没有存在的理由：留着它就等于留着第二份会和商户域走偏的事实。
--
-- 顺带把「幽灵门店」堵掉：开通前先向商户域要一次 GetStore，不存在的门店直接回 404，
-- 而不是把一条查无此店的开通记录建出来（见 service.Activate）。
--
-- 没有 down 段：本仓所有迁移都是单向下发（见 migrations/migrations.go 的包注释）。
ALTER TABLE lottery_activations DROP COLUMN location_name;
